const Joi = require('joi');
const { VALID_EMAIL_MODULES } = require('../../constants/emailModuleConstants');

// Loose opaque-string check rather than hex/length - templateId here refers
// to EmailTemplateMaster, whose ids are now common.encodeId-encoded (not raw
// hex). Other id fields sharing this helper (currencyId/countryId/stateId
// etc.) still hold raw ObjectIds for now - this check accepts both, since
// it's a superset, not a narrowing.
const objectId = () => Joi.string().trim().min(1).messages({
    'string.min': '{{#label}} must be a valid id.',
});

// currencyId/orderCancellationNotAllowedAfterStep may legitimately arrive as
// an empty string or the literal "null" when sent via multipart/form-data
// (companyLogo/paymentScanner uploads force the request into multipart, so
// every other field arrives as a string) - normalize those to actual null
// before Joi sees them, same convention as categoryValidations.js.
const nullableObjectId = () => Joi.alternatives().try(
    objectId(),
    Joi.string().valid('', 'null')
).custom((value) => (value === '' || value === 'null' ? null : value)).allow(null);

const phonePattern = /^[0-9+\-\s()]{7,15}$/;

const companySettingsFieldsSchema = {
    currencyId: nullableObjectId().label('Currency'),
    storeCountryId: nullableObjectId().label('Store country'),
    storeStateId: nullableObjectId().label('Store state'),
    adminName: Joi.string().trim().min(2).max(100).label('Admin name'),
    adminWhatsappNumber: Joi.string().trim().pattern(phonePattern).allow('', null).label('Admin WhatsApp number'),
    adminPhoneNumber: Joi.string().trim().pattern(phonePattern).allow('', null).label('Admin phone number'),
    adminAddress: Joi.string().trim().max(300).allow('', null).label('Admin address'),
    adminCity: Joi.string().trim().max(100).allow('', null).label('Admin city'),
    adminState: Joi.string().trim().max(100).allow('', null).label('Admin state'),
    adminPincode: Joi.string().trim().max(10).allow('', null).label('Admin pincode'),
    adminEmail: Joi.string().trim().lowercase().email().label('Admin email'),
    companyName: Joi.string().trim().max(150).allow('', null).label('Company name'),
    instagramId: Joi.string().trim().max(100).allow('', null).label('Instagram ID'),
    facebookId: Joi.string().trim().max(100).allow('', null).label('Facebook ID'),
    privacyPolicy: Joi.string().allow('', null).label('Privacy policy'),
    cancelPolicy: Joi.string().allow('', null).label('Cancel policy'),
    termsAndConditions: Joi.string().allow('', null).label('Terms and conditions'),
    aboutUs: Joi.string().allow('', null).label('About us'),
    showAnnouncements: Joi.boolean().label('Show announcements'),
    isAnnouncementRotationOn: Joi.boolean().label('Announcement rotation'),
    showBanners: Joi.boolean().label('Show banners'),
    isBannerRotationOn: Joi.boolean().label('Banner rotation'),
    isTaxRegistrationOnSignupEnabled: Joi.boolean().label('Ask for tax registration at signup'),
    // Seller-side invoice details (see invoiceService.js). All optional; blank clears them.
    taxRegistrationNumber: Joi.string().trim().pattern(/^\d{15}$/).allow('', null)
        .messages({ 'string.pattern.base': '{{#label}} must be exactly 15 digits.' })
        .label('Tax Registration Number (TRN)'),
    invoicePrefix: Joi.string().trim().uppercase().pattern(/^[A-Z0-9]{1,10}$/).allow('', null)
        .messages({ 'string.pattern.base': '{{#label}} may only contain letters and numbers (up to 10).' })
        .label('Invoice prefix'),
    invoiceDeclaration: Joi.string().trim().max(500).allow('', null).label('Invoice declaration'),
    invoicePrintDuplicateCopy: Joi.boolean().label('Print original and duplicate copies'),
    invoiceRoundOffToWhole: Joi.boolean().label('Round invoice total to a whole amount'),
    emailInvoiceOnOrderPlaced: Joi.boolean().label('Email invoice when an order is placed'),
    showReviewsToCustomers: Joi.boolean().label('Show reviews to customers'),
    isProductCodeAutoGenerated: Joi.boolean().label('Auto-generate product code'),
    isVariantCodeAutoGenerated: Joi.boolean().label('Auto-generate variant code'),
    isSizeCodeAutoGenerated: Joi.boolean().label('Auto-generate size code'),
    shouldProductsBeHiddenWhenLocationsAreExcluded: Joi.boolean().label('Hide products for excluded locations'),
    useShortNameForBrand: Joi.boolean().label('Use short name for brand'),
    allowOutOfStockProductsAdding: Joi.boolean().label('Allow out-of-stock products to be added to cart'),
    fewItemsReturnOnly: Joi.boolean().label('Few items return only'),
    fewItemsExchangeOnly: Joi.boolean().label('Few items exchange only'),
    isOrderCancellationAllowed: Joi.boolean().label('Order cancellation allowed'),
    orderCancellationNotAllowedAfterStep: Joi.alternatives().try(
        Joi.string().valid('ACCEPTED', 'REJECTED', 'COMPLETED', 'DELIVERED', 'DISPATCHED', 'READY_FOR_DELIVERY'),
        Joi.string().valid('', 'null')
    ).custom((value) => (value === '' || value === 'null' ? null : value)).allow(null).label('Order cancellation cutoff step'),
    isOrderNumberAutoGenerated: Joi.boolean().label('Auto-generate order number'),
    senderEmail: Joi.string().trim().lowercase().email().allow('', null).label('Sender email'),
    ccList: Joi.array().items(Joi.string().trim().lowercase().email()).single().label('CC list'),
    bccList: Joi.array().items(Joi.string().trim().lowercase().email()).single().label('BCC list'),
    isPaymentGatewayFeatureOn: Joi.boolean().label('Online payment enabled'),
    isFreeCashFeatureOn: Joi.boolean().label('Show Free Cash'),
    isFreeCashStackingAllowed: Joi.boolean().label('Allow Free Cash stacking'),
    isMultipleFreeCashUsageAllowed: Joi.boolean().label('Allow multiple Free Cash usage per order'),
    isStoringRemainingFreeCashAmountAllowed: Joi.boolean().label('Store remaining Free Cash amount for reuse'),
    returnFreeCashOnOrderReturn: Joi.boolean().label('Refund Free Cash on order return'),
    refundWholeFreeCashAmount: Joi.boolean().label('Refund the whole Free Cash amount used'),
    // Only meaningful (and only ever stored) when returnFreeCashOnOrderReturn
    // is true and refundWholeFreeCashAmount is false - companySettingsService
    // normalizes it back to null server-side whenever either condition
    // doesn't hold. Rejected here only when it contradicts
    // refundWholeFreeCashAmount within the SAME request.
    amountToRefund: Joi.number().min(0).max(100).allow(null)
        .when('refundWholeFreeCashAmount', {
            is: true,
            then: Joi.valid(null).messages({ 'any.only': 'amountToRefund is not applicable when refundWholeFreeCashAmount is true.' })
        })
        .label('Free Cash refund percentage'),
    timeForAbondonedCartReflection: Joi.number().integer().min(1).max(10080).label('Abandoned cart reflection time (minutes)'),
    abondonedCartOnlyForLoggedInUsers: Joi.boolean().label('Show abandoned carts for logged-in users only'),

    // Bank Transfer - gated by CompanyMaster.showPaymentQRCodeAndBankDetails
    // (+ WebsiteMaster.isShowingPaymentQRCodeAndBankDetailsFeatureOn),
    // enforced in companySettingsService.js, not here. Each field is
    // independently optional - a vendor may save partial bank info and fill
    // in the rest later, same convention as adminAddress/instagramId etc.
    bankAccountHolderName: Joi.string().trim().min(2).max(150).allow('', null).label('Bank account holder name'),
    bankName: Joi.string().trim().min(2).max(150).allow('', null).label('Bank name'),
    // Alphanumeric to also accommodate IBAN-style account numbers, not just
    // numeric domestic account numbers.
    bankAccountNumber: Joi.string().trim().pattern(/^[A-Za-z0-9]{4,34}$/).allow('', null)
        .messages({ 'string.pattern.base': '{{#label}} must be 4-34 alphanumeric characters.' })
        .label('Bank account number'),
    // Indian IFSC format: 4 letters, a literal 0, then 6 alphanumeric chars.
    ifscCode: Joi.string().trim().uppercase().pattern(/^[A-Z]{4}0[A-Z0-9]{6}$/).allow('', null)
        .messages({ 'string.pattern.base': '{{#label}} must be a valid IFSC code (e.g. ABCD0123456).' })
        .label('IFSC code'),
    branchName: Joi.string().trim().max(150).allow('', null).label('Branch name'),
    // SWIFT/BIC format: 8 chars, optionally 11 with a branch code suffix.
    swiftCode: Joi.string().trim().uppercase().pattern(/^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/).allow('', null)
        .messages({ 'string.pattern.base': '{{#label}} must be a valid SWIFT/BIC code (8 or 11 characters).' })
        .label('SWIFT code'),
    bankAccountType: Joi.alternatives().try(
        Joi.string().valid('SAVINGS', 'CURRENT'),
        Joi.string().valid('', 'null')
    ).custom((value) => (value === '' || value === 'null' ? null : value)).allow(null).label('Bank account type')
};

const createCompanySettingsSchema = Joi.object({
    ...companySettingsFieldsSchema,
    adminName: companySettingsFieldsSchema.adminName.required(),
    adminEmail: companySettingsFieldsSchema.adminEmail.required()
});

// Deliberately no .min(1) here - an update may legitimately carry zero body
// fields when it's only replacing companyLogo/paymentScanner (files live on
// req.files, not req.body, so Joi can't see them). The "nothing to update at
// all" case (no fields AND no files) is instead checked in the controller,
// which can see both.
const updateCompanySettingsSchema = Joi.object(companySettingsFieldsSchema);

const assignEmailTemplateSchema = Joi.object({
    module: Joi.string().valid(...VALID_EMAIL_MODULES).required().label('Module'),
    templateId: objectId().required().label('Template ID')
});

const unassignEmailTemplateSchema = Joi.object({
    module: Joi.string().valid(...VALID_EMAIL_MODULES).required().label('Module')
});

module.exports = {
    createCompanySettingsSchema,
    updateCompanySettingsSchema,
    assignEmailTemplateSchema,
    unassignEmailTemplateSchema
};
