const Joi = require('joi');
const { VALID_EMAIL_MODULES } = require('../../constants/emailModuleConstants');

const objectId = () => Joi.string().hex().length(24).messages({
    'string.hex': '{{#label}} must be a valid id.',
    'string.length': '{{#label}} must be a valid id.'
});

// currencyId/orderCancellationNotAllowedAfterStep may legitimately arrive as
// an empty string or the literal "null" when sent via multipart/form-data
// (companyLogo/paymentScanner uploads force the request into multipart, so
// every other field arrives as a string) - normalize those to actual null
// before Joi sees them, same convention as categoryValidations.js.
const nullableObjectId = () => Joi.alternatives().try(
    objectId(),
    Joi.string().valid('', 'null')
).custom((value) => (value === '' || value === 'null' ? null : value)).allow(null);

const phonePattern = /^[0-9+\-\s()]{7,15}$/;

const companySettingsFieldsSchema = {
    currencyId: nullableObjectId().label('Currency'),
    adminName: Joi.string().trim().min(2).max(100).label('Admin name'),
    adminWhatsappNumber: Joi.string().trim().pattern(phonePattern).allow('', null).label('Admin WhatsApp number'),
    adminPhoneNumber: Joi.string().trim().pattern(phonePattern).allow('', null).label('Admin phone number'),
    adminAddress: Joi.string().trim().max(300).allow('', null).label('Admin address'),
    adminCity: Joi.string().trim().max(100).allow('', null).label('Admin city'),
    adminState: Joi.string().trim().max(100).allow('', null).label('Admin state'),
    adminPincode: Joi.string().trim().max(10).allow('', null).label('Admin pincode'),
    adminEmail: Joi.string().trim().lowercase().email().label('Admin email'),
    companyName: Joi.string().trim().max(150).allow('', null).label('Company name'),
    instagramId: Joi.string().trim().max(100).allow('', null).label('Instagram ID'),
    facebookId: Joi.string().trim().max(100).allow('', null).label('Facebook ID'),
    privacyPolicy: Joi.string().allow('', null).label('Privacy policy'),
    cancelPolicy: Joi.string().allow('', null).label('Cancel policy'),
    termsAndConditions: Joi.string().allow('', null).label('Terms and conditions'),
    aboutUs: Joi.string().allow('', null).label('About us'),
    showAnnouncements: Joi.boolean().label('Show announcements'),
    isAnnouncementRotationOn: Joi.boolean().label('Announcement rotation'),
    showBanners: Joi.boolean().label('Show banners'),
    isBannerRotationOn: Joi.boolean().label('Banner rotation'),
    showReviewsToCustomers: Joi.boolean().label('Show reviews to customers'),
    isProductCodeAutoGenerated: Joi.boolean().label('Auto-generate product code'),
    isVariantCodeAutoGenerated: Joi.boolean().label('Auto-generate variant code'),
    isSizeCodeAutoGenerated: Joi.boolean().label('Auto-generate size code'),
    shouldProductsBeHiddenWhenLocationsAreExcluded: Joi.boolean().label('Hide products for excluded locations'),
    useShortNameForBrand: Joi.boolean().label('Use short name for brand'),
    allowOutOfStockProductsAdding: Joi.boolean().label('Allow out-of-stock products to be added to cart'),
    fewItemsReturnOnly: Joi.boolean().label('Few items return only'),
    fewItemsExchangeOnly: Joi.boolean().label('Few items exchange only'),
    isOrderCancellationAllowed: Joi.boolean().label('Order cancellation allowed'),
    orderCancellationNotAllowedAfterStep: Joi.alternatives().try(
        Joi.string().valid('ACCEPTED', 'REJECTED', 'COMPLETED', 'DELIVERED', 'DISPATCHED', 'READY_FOR_DELIVERY'),
        Joi.string().valid('', 'null')
    ).custom((value) => (value === '' || value === 'null' ? null : value)).allow(null).label('Order cancellation cutoff step'),
    isOrderNumberAutoGenerated: Joi.boolean().label('Auto-generate order number'),
    senderEmail: Joi.string().trim().lowercase().email().allow('', null).label('Sender email'),
    ccList: Joi.array().items(Joi.string().trim().lowercase().email()).single().label('CC list'),
    bccList: Joi.array().items(Joi.string().trim().lowercase().email()).single().label('BCC list'),
    isPaymentGatewayFeatureOn: Joi.boolean().label('Online payment enabled')
};

const createCompanySettingsSchema = Joi.object({
    ...companySettingsFieldsSchema,
    adminName: companySettingsFieldsSchema.adminName.required(),
    adminEmail: companySettingsFieldsSchema.adminEmail.required()
});

// Deliberately no .min(1) here - an update may legitimately carry zero body
// fields when it's only replacing companyLogo/paymentScanner (files live on
// req.files, not req.body, so Joi can't see them). The "nothing to update at
// all" case (no fields AND no files) is instead checked in the controller,
// which can see both.
const updateCompanySettingsSchema = Joi.object(companySettingsFieldsSchema);

const assignEmailTemplateSchema = Joi.object({
    module: Joi.string().valid(...VALID_EMAIL_MODULES).required().label('Module'),
    templateId: objectId().required().label('Template ID')
});

const unassignEmailTemplateSchema = Joi.object({
    module: Joi.string().valid(...VALID_EMAIL_MODULES).required().label('Module')
});

module.exports = {
    createCompanySettingsSchema,
    updateCompanySettingsSchema,
    assignEmailTemplateSchema,
    unassignEmailTemplateSchema
};
