const Joi = require('joi');

const objectId = () => Joi.string().hex().length(24).messages({
    'string.hex': '{{#label}} must be a valid id.',
    'string.length': '{{#label}} must be a valid id.'
});

const createOrderSchema = Joi.object({
    shippingAddressId: objectId().required().label('Shipping address'),
    billingAddressId: objectId().allow(null, '').label('Billing address'),
    // Only used when the vendor's CompanySettings.isOrderNumberAutoGenerated
    // is off - resolveOrderNumber (orderService.js) rejects it otherwise.
    orderNumber: Joi.string().trim().max(50).allow(null, '').label('Order number')
});

const orderIdParamSchema = Joi.object({
    id: objectId().required().label('Order ID')
});

const advanceOrderStepSchema = Joi.object({
    targetStepCode: Joi.string().trim().uppercase().required().label('Target step'),
    remarks: Joi.string().trim().max(500).allow(null, '').label('Remarks')
});

const assignDeliveryAgentSchema = Joi.object({
    deliveryAgentUserId: objectId().required().label('Delivery agent')
});

const cancelOrderSchema = Joi.object({
    cancellationReason: Joi.string().trim().min(1).max(500).required().label('Cancellation reason')
});

module.exports = {
    createOrderSchema,
    orderIdParamSchema,
    advanceOrderStepSchema,
    assignDeliveryAgentSchema,
    cancelOrderSchema
};
