const Joi = require('joi');
const { money } = require('./adminPlaceOrderValidations');

// Order-related ids are common.encodeId-encoded (see formatOrderForResponse
// in orderController.js), never raw hex ObjectIds - opaque-string check,
// decoded via common.decodeId in the controller before reaching the service.
const objectId = () => Joi.string().trim().min(1).messages({
    'string.min': '{{#label}} must be a valid id.',
});

const createOrderSchema = Joi.object({
    shippingAddressId: objectId().required().label('Shipping address'),
    billingAddressId: objectId().allow(null, '').label('Billing address'),
    // Only used when the vendor's CompanySettings.isOrderNumberAutoGenerated
    // is off - resolveOrderNumber (orderService.js) rejects it otherwise.
    orderNumber: Joi.string().trim().max(50).allow(null, '').label('Order number')
});

const orderIdParamSchema = Joi.object({
    id: objectId().required().label('Order ID')
});

// Step codes (and the RESTART action) are letters, digits and underscores -
// what the step dropdown offers is decided server-side per order.
const advanceOrderStepSchema = Joi.object({
    targetStepCode: Joi.string().trim().uppercase().max(50).pattern(/^[A-Z0-9_]+$/)
        .messages({ 'string.pattern.base': '{{#label}} is not a valid step.' })
        .required().label('Target step'),
    remarks: Joi.string().trim().max(500).allow(null, '').label('Remarks')
});

// 'YYYY-MM-DD', a real calendar date, today or later. "Today" is checked
// against UTC with one day of slack, because the admin picks the date in
// their own time zone (which can be a day behind UTC); the date picker
// already stops earlier days in the browser.
const deliveryDate = () => Joi.string()
    .trim()
    .pattern(/^\d{4}-\d{2}-\d{2}$/)
    .custom((value, helpers) => {
        const date = new Date(`${value}T00:00:00.000Z`);
        if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value) {
            return helpers.error('date.invalidDay');
        }
        const earliest = new Date();
        earliest.setUTCHours(0, 0, 0, 0);
        earliest.setUTCDate(earliest.getUTCDate() - 1);
        if (date < earliest) {
            return helpers.error('date.past');
        }
        return value;
    })
    .messages({
        'string.pattern.base': '{{#label}} must be a date in the format YYYY-MM-DD.',
        'date.invalidDay': '{{#label}} is not a valid date.',
        'date.past': '{{#label}} must be today or a later date.'
    });

const assignDeliveryAgentSchema = Joi.object({
    deliveryAgentUserId: objectId().required().label('Delivery agent'),
    deliveryDate: deliveryDate().required().label('Delivery date')
});

const changeDeliveryDateSchema = Joi.object({
    deliveryDate: deliveryDate().required().label('Delivery date')
});

// courierId null = remove the order's courier.
const setOrderCourierSchema = Joi.object({
    courierId: objectId().allow(null).required().label('Courier')
});

const setShippingPriceSchema = Joi.object({
    shippingAmount: Joi.number().min(0).max(10000000).precision(2).required().label('Shipping price')
});

// Exactly one of: switch to one of the customer's saved addresses, or an
// open-text address typed by the admin (stored on the order only, never
// saved to the customer's address book).
const setShippingAddressSchema = Joi.object({
    addressId: objectId().label('Address'),
    addressText: Joi.string().trim().min(5).max(1000).label('Address')
})
    .xor('addressId', 'addressText')
    .messages({ 'object.missing': 'Choose a saved address or enter a new address.', 'object.xor': 'Provide either a saved address or a new address, not both.' });

// Products an admin adds to an already-placed order. Same fields as Place Order's items.
const addOrderProductItemsSchema = Joi.array().items(
    Joi.object({
        productId: objectId().required().label('Product'),
        variantId: objectId().required().label('Variant'),
        sizeId: objectId().required().label('Size'),
        quantity: Joi.number().integer().min(1).max(100000).required().label('Quantity')
    })
).min(1).max(50).required().label('Items');

const addOrderProductsSchema = Joi.object({
    items: addOrderProductItemsSchema,
    // Same "Apply Bulk Pricing" choice as Place Order - off means normal price.
    applyBulkPricing: Joi.boolean().default(false).label('Apply bulk pricing'),
    // Same "Enter tax manually" choice as Place Order: one tax total for the added products.
    isTaxManual: Joi.boolean().default(false).label('Enter tax manually'),
    manualTaxAmount: Joi.when('isTaxManual', {
        is: true,
        then: money().required().label('Tax amount'),
        otherwise: Joi.forbidden().messages({ 'any.unknown': 'Tax amount is only allowed when "Enter tax manually" is ticked.' })
    })
});

// Live tax preview for the products being added (nothing is saved).
const addOrderProductsTaxPreviewSchema = Joi.object({
    items: addOrderProductItemsSchema,
    applyBulkPricing: Joi.boolean().default(false).label('Apply bulk pricing')
});

const cancelOrderSchema = Joi.object({
    cancellationReason: Joi.string().trim().min(1).max(500).required().label('Cancellation reason')
});

module.exports = {
    createOrderSchema,
    orderIdParamSchema,
    advanceOrderStepSchema,
    assignDeliveryAgentSchema,
    changeDeliveryDateSchema,
    setOrderCourierSchema,
    cancelOrderSchema,
    setShippingPriceSchema,
    setShippingAddressSchema,
    addOrderProductsSchema,
    addOrderProductsTaxPreviewSchema
};
