const Joi = require('joi');

// Order-related ids are common.encodeId-encoded (see formatOrderForResponse
// in orderController.js), never raw hex ObjectIds - opaque-string check,
// decoded via common.decodeId in the controller before reaching the service.
const objectId = () => Joi.string().trim().min(1).messages({
    'string.min': '{{#label}} must be a valid id.',
});

const createOrderSchema = Joi.object({
    shippingAddressId: objectId().required().label('Shipping address'),
    billingAddressId: objectId().allow(null, '').label('Billing address'),
    // Only used when the vendor's CompanySettings.isOrderNumberAutoGenerated
    // is off - resolveOrderNumber (orderService.js) rejects it otherwise.
    orderNumber: Joi.string().trim().max(50).allow(null, '').label('Order number')
});

const orderIdParamSchema = Joi.object({
    id: objectId().required().label('Order ID')
});

const advanceOrderStepSchema = Joi.object({
    targetStepCode: Joi.string().trim().uppercase().required().label('Target step'),
    remarks: Joi.string().trim().max(500).allow(null, '').label('Remarks')
});

const assignDeliveryAgentSchema = Joi.object({
    deliveryAgentUserId: objectId().required().label('Delivery agent')
});

const setShippingPriceSchema = Joi.object({
    shippingAmount: Joi.number().min(0).max(10000000).precision(2).required().label('Shipping price')
});

// Exactly one of: switch to one of the customer's saved addresses, or an
// open-text address typed by the admin (stored on the order only, never
// saved to the customer's address book).
const setShippingAddressSchema = Joi.object({
    addressId: objectId().label('Address'),
    addressText: Joi.string().trim().min(5).max(1000).label('Address')
})
    .xor('addressId', 'addressText')
    .messages({ 'object.missing': 'Choose a saved address or enter a new address.', 'object.xor': 'Provide either a saved address or a new address, not both.' });

// Products an admin adds to an already-placed order. Same fields as Place Order's items.
const addOrderProductsSchema = Joi.object({
    items: Joi.array().items(
        Joi.object({
            productId: objectId().required().label('Product'),
            variantId: objectId().required().label('Variant'),
            sizeId: objectId().required().label('Size'),
            quantity: Joi.number().integer().min(1).max(100000).required().label('Quantity')
        })
    ).min(1).max(50).required().label('Items'),
    // Same "Apply Bulk Pricing" choice as Place Order - off means normal price.
    applyBulkPricing: Joi.boolean().default(false).label('Apply bulk pricing')
});

const cancelOrderSchema = Joi.object({
    cancellationReason: Joi.string().trim().min(1).max(500).required().label('Cancellation reason')
});

module.exports = {
    createOrderSchema,
    orderIdParamSchema,
    advanceOrderStepSchema,
    assignDeliveryAgentSchema,
    cancelOrderSchema,
    setShippingPriceSchema,
    setShippingAddressSchema,
    addOrderProductsSchema
};
