import Switch from '../../../../components/common/Switch';
import Dropdown from '../../../../components/common/DropDown';
import theme from '../theme/theme';

const CANCELLATION_CUTOFF_OPTIONS = [
  { value: 'ACCEPTED', label: 'Accepted' },
  { value: 'READY_FOR_DELIVERY', label: 'Ready for Delivery' },
  { value: 'DISPATCHED', label: 'Dispatched' },
  { value: 'DELIVERED', label: 'Delivered' },
  { value: 'COMPLETED', label: 'Completed' },
  { value: 'REJECTED', label: 'Rejected' },
];

/**
 * @param {Object} props.draft
 * @param {(patch: Object) => void} props.onChange
 */
const CartOrderSection = ({ draft, onChange }) => {
  const set = (patch) => onChange(patch);

  return (
    <div className="space-y-6">
      <div>
        <h3 className={`text-sm font-semibold ${theme.text.heading} mb-3`}>Cart</h3>
        <Switch
          label="Allow Out-of-Stock Products to Be Added to Cart"
          checked={draft.allowOutOfStockProductsAdding}
          onChange={(e) => set({ allowOutOfStockProductsAdding: e.target.checked })}
          color={theme.switch.color}
        />
      </div>

      <div className="pt-4 border-t border-gray-100">
        <h3 className={`text-sm font-semibold ${theme.text.heading} mb-3`}>Return / Exchange</h3>
        <p className={`text-xs ${theme.text.muted} mb-3`}>
          Only meaningful when the Return/Exchange features themselves are enabled for this account. When off, a
          customer can only request a return/exchange for the whole order at once.
        </p>
        <div className="space-y-3">
          <Switch
            label="Allow Return of a Few Items Only"
            checked={draft.fewItemsReturnOnly}
            onChange={(e) => set({ fewItemsReturnOnly: e.target.checked })}
            color={theme.switch.color}
          />
          <Switch
            label="Allow Exchange of a Few Items Only"
            checked={draft.fewItemsExchangeOnly}
            onChange={(e) => set({ fewItemsExchangeOnly: e.target.checked })}
            color={theme.switch.color}
          />
        </div>
      </div>

      <div className="pt-4 border-t border-gray-100">
        <h3 className={`text-sm font-semibold ${theme.text.heading} mb-3`}>Order</h3>
        <div className="space-y-3">
          <Switch
            label="Allow Order Cancellation"
            checked={draft.isOrderCancellationAllowed}
            onChange={(e) => set({ isOrderCancellationAllowed: e.target.checked })}
            color={theme.switch.color}
          />
          {draft.isOrderCancellationAllowed && (
            <Dropdown
              label="Cancellation Not Allowed After Step"
              placeholder="No cutoff - cancellable until delivered/completed"
              options={CANCELLATION_CUTOFF_OPTIONS}
              value={draft.orderCancellationNotAllowedAfterStep}
              onChange={(val) => set({ orderCancellationNotAllowedAfterStep: val })}
              clearable
            />
          )}
          <Switch
            label="Auto-generate Order Number"
            checked={draft.isOrderNumberAutoGenerated}
            onChange={(e) => set({ isOrderNumberAutoGenerated: e.target.checked })}
            color={theme.switch.color}
          />
        </div>
      </div>
    </div>
  );
};

export default CartOrderSection;
