import Switch from '../../../../components/common/Switch';
import theme from '../theme/theme';

/**
 * @param {Object} props.draft
 * @param {(patch: Object) => void} props.onChange
 */
const ProductSection = ({ draft, onChange }) => {
  const set = (patch) => onChange(patch);

  return (
    <div className="space-y-3">
      <Switch
        label="Auto-generate Product Code"
        checked={draft.isProductCodeAutoGenerated}
        onChange={(e) => set({ isProductCodeAutoGenerated: e.target.checked })}
        color={theme.switch.color}
      />
      <Switch
        label="Auto-generate Variant Code"
        checked={draft.isVariantCodeAutoGenerated}
        onChange={(e) => set({ isVariantCodeAutoGenerated: e.target.checked })}
        color={theme.switch.color}
      />
      <Switch
        label="Auto-generate Size Code"
        checked={draft.isSizeCodeAutoGenerated}
        onChange={(e) => set({ isSizeCodeAutoGenerated: e.target.checked })}
        color={theme.switch.color}
      />
      <Switch
        label="Hide Products for Excluded Locations"
        description="A product excluded from a customer's location won't show up in their storefront at all."
        checked={draft.shouldProductsBeHiddenWhenLocationsAreExcluded}
        onChange={(e) => set({ shouldProductsBeHiddenWhenLocationsAreExcluded: e.target.checked })}
        color={theme.switch.color}
      />
      <Switch
        label="Use Short Name for Brand"
        description="Show a brand's short name on storefront product pages, falling back to its full name when no short name is set."
        checked={draft.useShortNameForBrand}
        onChange={(e) => set({ useShortNameForBrand: e.target.checked })}
        color={theme.switch.color}
      />
    </div>
  );
};

export default ProductSection;
