const CompanySettings = require('../models/CompanySettings');
const EmailTemplateMaster = require('../models/EmailTemplateMaster');
const redisService = require('./redisService');
const redisKeys = require('../utils/redisKeys');
const logger = require('../utils/logger');
const common = require('../utils/common');
const imageUploadService = require('./imageUploadService');
const fileUploadService = require('./fileUploadService');
const emailService = require('./emailService');
const vendorSmtpProvider = require('./emailProviders/vendorSmtpProvider');
const emailTemplateMasterService = require('./emailTemplateMasterService');
const CountryMaster = require('../models/CountryMaster');
const StateMaster = require('../models/StateMaster');
const CityMaster = require('../models/CityMaster');
const CurrencyMaster = require('../models/CurrencyMaster');
const currencyService = require('./currencyService');
const orderStepService = require('./orderStepService');
const FileAsset = require('../models/FileAsset');
const { readStoredAsset } = require('./storedFileReader');

// The store currency (every price is entered in it - see currencyService.js)
// must be an active currency of a country the vendor serves
// (CompanyMaster.allowedCountries), and can be changed but never cleared:
// orders can't be placed without one. A currency saved before this rule that
// is resubmitted unchanged is left alone, so the rest of the page still saves.
const validateStoreCurrency = async (data, companyMasterData, existingSettings = null) => {
    try {
        if (data.currencyId === undefined) return null;
        if (!data.currencyId) {
            return existingSettings?.currencyId
                ? common.returnResult(false, 400, 'The store currency cannot be removed - choose another currency instead.')
                : null;
        }
        const currency = await CurrencyMaster.findOne({ _id: data.currencyId, status: 'A' }).select('_id').lean();
        if (!currency) {
            return common.returnResult(false, 400, 'The selected store currency is not available.');
        }
        const isUnchanged = existingSettings?.currencyId?.toString() === data.currencyId.toString();
        if (!isUnchanged && !(await currencyService.isCurrencyAllowedForCountries(data.currencyId, companyMasterData?.allowedCountries))) {
            return common.returnResult(false, 400, 'The selected store currency does not belong to any of the countries your store serves.');
        }
        return null;
    } catch (err) {
        throw err;
    }
};

// Every field a vendor is allowed to set directly through create/update -
// deliberately excludes vendorId, companyLogo/paymentScanner/partnerCertificate
// (handled separately as file uploads) and emailTemplateAssignments (owned by
// the dedicated assign/unassign endpoints above).
const SIMPLE_FIELDS = [
    'currencyId', 'storeCountryId', 'storeStateId', 'storeCityId', 'adminName', 'adminWhatsappNumber', 'adminPhoneNumber', 'adminAddress',
    'adminCity', 'adminState', 'adminPincode', 'adminEmail', 'companyName', 'instagramId',
    'facebookId', 'privacyPolicy', 'cancelPolicy', 'termsAndConditions', 'aboutUs', 'returnRefundPolicy', 'policyDisplayMode',
    'contactEmail', 'contactPhoneNumber', 'contactAddress',
    'showAnnouncements', 'isAnnouncementRotationOn', 'showBanners', 'isBannerRotationOn',
    'isTaxRegistrationOnSignupEnabled', 'isCityOptional',
    'taxRegistrationNumber', 'invoicePrefix', 'invoiceDeclaration',
    'invoicePrintDuplicateCopy', 'invoiceRoundOffToWhole', 'emailInvoiceOnOrderPlaced',
    'showReviewsToCustomers', 'isProductCodeAutoGenerated', 'isVariantCodeAutoGenerated',
    'isSizeCodeAutoGenerated', 'shouldProductsBeHiddenWhenLocationsAreExcluded',
    'useShortNameForBrand', 'allowOutOfStockProductsAdding', 'fewItemsReturnOnly',
    'fewItemsExchangeOnly', 'isOrderCancellationAllowed', 'orderCancellationNotAllowedAfterStep',
    'markPaymentCompletedAtStep', 'deliveryAgentFromStep', 'deliveryAgentToStep',
    'isOrderNumberAutoGenerated', 'senderEmail', 'ccList', 'bccList', 'useDefaultEmailTemplate', 'discountEmailRecipients', 'discountExpiryReminderDays',
    'freeCashEmailRecipients', 'freeCashExpiryReminderDays', 'isPaymentGatewayFeatureOn',
    'isFreeCashFeatureOn', 'isFreeCashStackingAllowed', 'isMultipleFreeCashUsageAllowed',
    'isStoringRemainingFreeCashAmountAllowed', 'returnFreeCashOnOrderReturn', 'refundWholeFreeCashAmount',
    'amountToRefund', 'timeForAbondonedCartReflection', 'abondonedCartOnlyForLoggedInUsers',
    'bankAccountHolderName', 'bankName', 'bankAccountNumber', 'ifscCode', 'branchName',
    'swiftCode', 'bankAccountType'
];

// Fields gated together with paymentScanner behind
// CompanyMaster.showPaymentQRCodeAndBankDetails (+
// WebsiteMaster.isShowingPaymentQRCodeAndBankDetailsFeatureOn).
const BANK_TRANSFER_FIELDS = [
    'bankAccountHolderName', 'bankName', 'bankAccountNumber', 'ifscCode', 'branchName',
    'swiftCode', 'bankAccountType'
];

// '' and undefined/null are the same "empty" value for this comparison -
// Joi normalizes bankAccountType's '' to null before this runs, but the
// plain string bank fields (bankAccountHolderName etc.) are only
// .allow('', null), so an untouched form field can legitimately arrive as
// either depending on which one the caller used.
const normalizeEmpty = (value) => (value === undefined || value === '' ? null : value);

// Checks whether the request is actually CHANGING the bank-transfer group
// (any bank field whose incoming value differs from what's already stored,
// or a new paymentScanner file) or the partnerCertificate file, and if so,
// verifies the vendor is entitled to it. Returns null when nothing gated
// was actually touched (caller proceeds normally), otherwise returns the
// first failing returnResult().
//
// Deliberately diff-based rather than presence-based: a caller that sends
// its whole settings object on every save (not just the fields it means to
// change) would otherwise trip this gate on every single save, for a group
// it isn't even trying to edit - confirmed live via the admin Company
// Settings page, which 403'd on saving an unrelated toggle for a vendor not
// entitled to Bank Transfer, purely because it sent bankAccountHolderName:
// '' etc. alongside everything else.
const checkPaymentDetailsEntitlements = async (vendorId, data, files, companyMasterData, websiteMasterData, existingSettings = null) => {
    try {
        const bankGroupTouched = BANK_TRANSFER_FIELDS.some((field) => {
            if (data[field] === undefined) return false;
            const currentValue = existingSettings ? existingSettings[field] : undefined;
            return normalizeEmpty(data[field]) !== normalizeEmpty(currentValue);
        }) || !!files?.paymentScanner?.[0];
        if (bankGroupTouched) {
            const check = await common.checkFeatureOnOrOff(
                vendorId, websiteMasterData, companyMasterData,
                'isShowingPaymentQRCodeAndBankDetailsFeatureOn', 'showPaymentQRCodeAndBankDetails'
            );
            if (!check.isSuccess) return check;
        }

        const certificateTouched = !!files?.partnerCertificate?.[0];
        if (certificateTouched) {
            const check = await common.checkFeatureOnOrOff(
                vendorId, websiteMasterData, companyMasterData,
                'isShowingPartnerCertificateFeatureOn', 'isShowingPartnerCertificateFeatureOn'
            );
            if (!check.isSuccess) return check;
        }

        return null;
    } catch (err) {
        throw err;
    }
};

// Keeps the 3 return-Free-Cash fields internally consistent regardless of
// which subset of them a given create/update request actually touched -
// refundWholeFreeCashAmount/amountToRefund are meaningless (and forced back
// to their inapplicable default) whenever returnFreeCashOnOrderReturn is
// off, and amountToRefund specifically is meaningless whenever the whole
// amount is being refunded.
const normalizeFreeCashReturnFields = (target) => {
    if (target.returnFreeCashOnOrderReturn !== true) {
        target.refundWholeFreeCashAmount = false;
        target.amountToRefund = null;
    } else if (target.refundWholeFreeCashAmount === true) {
        target.amountToRefund = null;
    }
};

// Store country/state/city (the tax location when a customer's is unknown -
// see taxCalculationService.js) must be a consistent, active chain the vendor
// serves: country in CompanyMaster.allowedCountries, state inside that
// country, city inside that state. A state/city needs its parent set.
// Checked against the values the document will END UP with, so a partial
// update can't leave a state pointing at a different country.
const validateStoreLocation = async (data, companyMasterData, existingSettings = null) => {
    try {
        const pick = (field) => (data[field] !== undefined ? data[field] : (existingSettings ? existingSettings[field] : null)) || null;
        const countryId = pick('storeCountryId');
        const stateId = pick('storeStateId');
        const cityId = pick('storeCityId');

        if (!countryId && (stateId || cityId)) {
            return common.returnResult(false, 400, 'Select a store country before choosing a store state or city.');
        }
        if (!stateId && cityId) {
            return common.returnResult(false, 400, 'Select a store state before choosing a store city.');
        }
        if (!countryId) {
            return null;
        }

        const allowedCountryIds = (companyMasterData?.allowedCountries || []).map((id) => id.toString());
        if (!allowedCountryIds.includes(countryId.toString())) {
            return common.returnResult(false, 400, 'The selected store country is not one of the countries your store serves.');
        }
        const country = await CountryMaster.findOne({ _id: countryId, status: 'A' }).select('_id').lean();
        if (!country) {
            return common.returnResult(false, 400, 'The selected store country is not available.');
        }
        if (stateId) {
            const state = await StateMaster.findOne({ _id: stateId, country_id: countryId, status: 'A' }).select('_id').lean();
            if (!state) {
                return common.returnResult(false, 400, 'The selected store state does not belong to the selected store country.');
            }
        }
        if (cityId) {
            const city = await CityMaster.findOne({ _id: cityId, state_id: stateId, status: 'A' }).select('_id').lean();
            if (!city) {
                return common.returnResult(false, 400, 'The selected store city does not belong to the selected store state.');
            }
        }
        return null;
    } catch (err) {
        throw err;
    }
};

const ORDER_STEP_FIELD_LABELS = {
    orderCancellationNotAllowedAfterStep: 'Cancellation not allowed after step',
    markPaymentCompletedAtStep: 'Mark payment as done at step',
    deliveryAgentFromStep: 'Delivery agent - from step',
    deliveryAgentToStep: 'Delivery agent - to step'
};

// The order-step settings must name steps of the workflow the platform
// assigned to this vendor (CompanyMaster.orderSteps). Diff-based like
// checkPaymentDetailsEntitlements: the admin page sends every field on every
// save, and a value saved before the vendor was given a different workflow
// must not block saving something unrelated - only a CHANGED value is checked.
// The delivery-agent pair is re-checked as a pair whenever either half changes.
const validateOrderStepSettings = async (data, companyMasterData, websiteMasterData, existingSettings = null) => {
    try {
        const changedFields = Object.keys(ORDER_STEP_FIELD_LABELS).filter((field) =>
            data[field] !== undefined && normalizeEmpty(data[field]) !== normalizeEmpty(existingSettings ? existingSettings[field] : undefined)
        );
        if (changedFields.length === 0) return null;

        const pick = (field) => (data[field] !== undefined ? data[field] : (existingSettings ? existingSettings[field] : null)) || null;
        const hasAnyValue = changedFields.some((field) => pick(field));
        if (!hasAnyValue) return null;

        const stepMaster = await orderStepService.loadActiveStepMaster(companyMasterData?.orderSteps);
        if (!stepMaster) {
            return common.returnResult(false, 400, "No order steps are assigned to your store yet, so the order step settings can't be saved. Please contact support.");
        }

        for (const field of changedFields) {
            const code = pick(field);
            if (code && !orderStepService.findStepByCode(stepMaster, code)) {
                return common.returnResult(false, 400, `${ORDER_STEP_FIELD_LABELS[field]}: "${code}" is not one of your store's order steps.`);
            }
        }

        const agentPairChanged = changedFields.includes('deliveryAgentFromStep') || changedFields.includes('deliveryAgentToStep');
        const fromCode = pick('deliveryAgentFromStep');
        const toCode = pick('deliveryAgentToStep');
        if (agentPairChanged && (fromCode || toCode)) {
            if (!orderStepService.isDeliveryAgentFeatureOn(websiteMasterData, companyMasterData)) {
                return common.returnResult(false, 403, 'Delivery agents are not enabled for your store.');
            }
            if (!fromCode || !toCode) {
                return common.returnResult(false, 400, 'Choose both the step a delivery agent moves an order from and the step it moves it to.');
            }
            const fromStep = orderStepService.findStepByCode(stepMaster, fromCode);
            const toStep = orderStepService.findStepByCode(stepMaster, toCode);
            const nextStep = orderStepService.getNextStep(stepMaster, fromStep.sequence);
            if (!nextStep) {
                return common.returnResult(false, 400, `"${fromStep.name}" is your last order step, so a delivery agent can't move an order on from it.`);
            }
            if (nextStep.code !== toStep.code) {
                return common.returnResult(false, 400, `A delivery agent can only move an order to the very next step - after "${fromStep.name}" that is "${nextStep.name}".`);
            }
        }
        return null;
    } catch (err) {
        throw err;
    }
};

// The vendor's assigned workflow, for the Company Settings step dropdowns.
const fetchAssignedOrderSteps = async (companyMasterData, websiteMasterData) => {
    try {
        const isDeliveryAgentAccessOn = orderStepService.isDeliveryAgentFeatureOn(websiteMasterData, companyMasterData);
        const stepMaster = await orderStepService.loadActiveStepMaster(companyMasterData?.orderSteps);
        if (!stepMaster) {
            return common.returnResult(true, 200, 'No order steps are assigned to this store yet', {
                steps: [], lastStepCode: null, isDeliveryAgentAccessOn
            });
        }

        const steps = orderStepService.getSortedSteps(stepMaster).map((step) => ({ code: step.code, name: step.name, sequence: step.sequence }));
        return common.returnResult(true, 200, 'Order steps fetched successfully', {
            steps,
            lastStepCode: orderStepService.getLastStep(stepMaster)?.code || null,
            isDeliveryAgentAccessOn
        });
    } catch (err) {
        throw err;
    }
};

const invalidateCompanySettingsCache = async (vendorId) => {
    try {
        await redisService.del(redisKeys.companySettings(vendorId));
        logger.logInfo(1, 0, 'Company settings cache invalidated', { vendorId });
    } catch (err) {
        throw err;
    }
};

const createCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const existing = await CompanySettings.findOne({ vendorId });
        if (existing) {
            return common.returnResult(false, 409, 'Company settings already exist for this vendor. Use update instead.');
        }

        dropDisabledEmailFields(data, companyMasterData, websiteMasterData);

        const entitlementFailure = await checkPaymentDetailsEntitlements(vendorId, data, files, companyMasterData, websiteMasterData);
        if (entitlementFailure) {
            return entitlementFailure;
        }

        const storeLocationFailure = await validateStoreLocation(data, companyMasterData);
        if (storeLocationFailure) {
            return storeLocationFailure;
        }

        const storeCurrencyFailure = await validateStoreCurrency(data, companyMasterData);
        if (storeCurrencyFailure) {
            return storeCurrencyFailure;
        }

        const orderStepFailure = await validateOrderStepSettings(data, companyMasterData, websiteMasterData);
        if (orderStepFailure) {
            return orderStepFailure;
        }

        const settingsData = { vendorId };
        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settingsData[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settingsData);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        const certificateFile = files?.partnerCertificate?.[0];
        if (certificateFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'partnerCertificate', file: certificateFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.partnerCertificate = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        settingsData.createdBy = { userID: userId, vendorID: vendorId };
        settingsData.updatedBy = { userID: userId, vendorID: vendorId };

        const settings = new CompanySettings(settingsData);
        const saved = await settings.save();

        logger.logInfo(1, 0, 'Company settings created successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 201, 'Company settings created successfully', { settings: saved });
    } catch (err) {
        throw err;
    }
};

const updateCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            return common.returnResult(false, 404, 'Company settings not found. Please create them first.');
        }

        dropDisabledEmailFields(data, companyMasterData, websiteMasterData);

        const entitlementFailure = await checkPaymentDetailsEntitlements(vendorId, data, files, companyMasterData, websiteMasterData, settings);
        if (entitlementFailure) {
            return entitlementFailure;
        }

        const storeLocationFailure = await validateStoreLocation(data, companyMasterData, settings);
        if (storeLocationFailure) {
            return storeLocationFailure;
        }

        const storeCurrencyFailure = await validateStoreCurrency(data, companyMasterData, settings);
        if (storeCurrencyFailure) {
            return storeCurrencyFailure;
        }

        const orderStepFailure = await validateOrderStepSettings(data, companyMasterData, websiteMasterData, settings);
        if (orderStepFailure) {
            return orderStepFailure;
        }

        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settings[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settings);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            if (settings.companyLogo?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.companyLogo.imageAssetId, file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.companyLogo = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            if (settings.paymentScanner?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.paymentScanner.imageAssetId, file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.paymentScanner = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        const certificateFile = files?.partnerCertificate?.[0];
        if (certificateFile) {
            if (settings.partnerCertificate?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.partnerCertificate.imageAssetId, file: certificateFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.partnerCertificate = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'partnerCertificate', file: certificateFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.partnerCertificate = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        settings.updatedBy = { userID: userId, vendorID: vendorId };

        const updated = await settings.save();
        logger.logInfo(1, 0, 'Company settings updated successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 200, 'Company settings updated successfully', { settings: updated });
    } catch (err) {
        throw err;
    }
};

const fetchCompanySettingsByVendorId = async (vendorId) => {
    try {
        logger.logInfo(null,null,'Fetching company settings from DB', { vendorId });
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            logger.logInfo(0,1,'Company settings not found', { vendorId });
            return null;
        }
        logger.logInfo(1,0,'Company settings fetched successfully', { vendorId });
        return settings;
    } catch (err) {
        throw err;
    }
}

// Tags the vendor's own templateId against `module` - at most one entry per
// module (replaces any existing entry for that module). Invalidates the
// Redis cache afterwards so ensureVendorDataCached picks up the change on
// the very next request instead of serving stale companySettingsData for
// up to an hour.
const assignEmailTemplate = async (vendorId, module, templateId, userId) => {
    try {
        const template = await EmailTemplateMaster.findOne({ _id: templateId, vendorId, status: { $ne: 'D' } });
        if (!template) {
            return common.returnResult(false, 404, 'Email template not found');
        }
        // Same rules as the Email Templates page's Change Module action
        // (emailTemplateMasterService.changeTemplateModule): only Active
        // templates, and only to the module the template itself belongs to.
        if (template.status !== 'A') {
            return common.returnResult(false, 400, 'Only active templates can be assigned to a module.');
        }
        if (template.module !== module) {
            return common.returnResult(false, 400, "This template belongs to a different module. Change the template's module from the Email Templates page instead.");
        }

        const settingsExists = await CompanySettings.exists({ vendorId });
        if (!settingsExists) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        // Targeted updates rather than load-and-save(): save() revalidates every
        // required field on the whole document, so an unrelated gap in the
        // vendor's settings (e.g. adminName not filled in yet) would block a
        // change that only touches emailTemplateAssignments.
        const updatedBy = { userID: userId, vendorID: vendorId };
        await CompanySettings.updateOne({ vendorId }, { $pull: { emailTemplateAssignments: { module } } });
        await CompanySettings.updateOne({ vendorId }, { $pull: { emailTemplateAssignments: { templateId } } });
        await CompanySettings.updateOne({ vendorId }, { $push: { emailTemplateAssignments: { module, templateId } }, $set: { updatedBy } });
        await redisService.del(redisKeys.companySettings(vendorId));

        const settings = await CompanySettings.findOne({ vendorId });

        logger.logInfo(1, 0, 'Email template assigned to module', { vendorId, module, templateId });
        return common.returnResult(true, 200, 'Email template assigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};

const unassignEmailTemplate = async (vendorId, module, userId) => {
    try {
        const settingsExists = await CompanySettings.exists({ vendorId });
        if (!settingsExists) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        await CompanySettings.updateOne(
            { vendorId },
            { $pull: { emailTemplateAssignments: { module } }, $set: { updatedBy: { userID: userId, vendorID: vendorId } } }
        );
        await redisService.del(redisKeys.companySettings(vendorId));

        const settings = await CompanySettings.findOne({ vendorId });

        logger.logInfo(1, 0, 'Email template unassigned from module', { vendorId, module });
        return common.returnResult(true, 200, 'Email template unassigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};


/*
|--------------------------------------------------------------------------
| EMAIL TAB: CC/BCC, ATTACHMENTS AND IMAGES
|--------------------------------------------------------------------------
| Each is a two-level feature (WebsiteMaster AND CompanyMaster):
| isCcAndBccFeatureOn, isAddingOfAttachmentAllowed, isAddingOfImageAllowed.
| Attachments and images are stored here ready to use; whether a given email
| includes them is decided per email/template (a later step). Limits come
| from CompanyMaster: numberOfAttachmentsAllowed / attachmentSizeAllowed /
| allowedAttachmentExtensions and numberOfImageAllowed / imageSizeAllowed /
| allowedImageExtensions.
*/

const EMAIL_ATTACHMENT_MODULE = 'emailAttachment';
const EMAIL_IMAGE_MODULE = 'emailImage';

const isTwoLevelOn = (flag, companyMasterData, websiteMasterData) => {
    try {
        return websiteMasterData?.[flag] === true && companyMasterData?.[flag] === true;
    } catch (err) {
        throw err;
    }
};

// What the Email tab may show, and the limits it should enforce - the
// frontend only has CompanyMaster, so the effective (both-level) state is
// worked out here.
const getEmailFeatureAccess = (companyMasterData, websiteMasterData) => {
    try {
        return {
            // The master email switch - off = no email at all, so the Email and
            // "Discount and Free Cash" tabs are hidden.
            isEmailOn: isTwoLevelOn('isSendingEmailFeatureOn', companyMasterData, websiteMasterData),
            isCcAndBccOn: isTwoLevelOn('isCcAndBccFeatureOn', companyMasterData, websiteMasterData),
            attachments: {
                isOn: isTwoLevelOn('isAddingOfAttachmentAllowed', companyMasterData, websiteMasterData),
                maxCount: companyMasterData?.numberOfAttachmentsAllowed ?? null,
                maxSizeMB: companyMasterData?.attachmentSizeAllowed ?? null,
                allowedExtensions: companyMasterData?.allowedAttachmentExtensions || []
            },
            images: {
                isOn: isTwoLevelOn('isAddingOfImageAllowed', companyMasterData, websiteMasterData),
                maxCount: companyMasterData?.numberOfImageAllowed ?? null,
                maxSizeMB: companyMasterData?.imageSizeAllowed ?? null,
                allowedExtensions: companyMasterData?.allowedImageExtensions || []
            },
            // Every email goes through the vendor's own SMTP account, which
            // carries attachments and images.
            emailProvider: 'smtp',
            canSendAttachments: true
        };
    } catch (err) {
        throw err;
    }
};

// With CC/BCC off, the lists can't be changed (what's saved is kept, just unused/hidden).
const dropDisabledEmailFields = (data, companyMasterData, websiteMasterData) => {
    try {
        if (!isTwoLevelOn('isCcAndBccFeatureOn', companyMasterData, websiteMasterData)) {
            delete data.ccList;
            delete data.bccList;
        }
    } catch (err) {
        throw err;
    }
};

const emailContentLists = (settings) => ({
    emailAttachments: settings?.emailAttachments || [],
    emailImages: settings?.emailImages || []
});

const addEmailAttachment = async (vendorId, userId, file, displayName, companyMasterData, websiteMasterData) => {
    try {
        if (!isTwoLevelOn('isAddingOfAttachmentAllowed', companyMasterData, websiteMasterData)) {
            return common.returnResult(false, 403, 'Email attachments are not available for your account.');
        }
        const settings = await CompanySettings.findOne({ vendorId }, { emailAttachments: 1 }).lean();
        if (!settings) {
            return common.returnResult(false, 404, 'Please save your company settings first, then add attachments.');
        }
        const maxCount = companyMasterData?.numberOfAttachmentsAllowed;
        if (maxCount != null && (settings.emailAttachments || []).length >= maxCount) {
            return common.returnResult(false, 400, `You can keep at most ${maxCount} attachment(s). Remove one to add another.`);
        }

        const upload = await fileUploadService.uploadFile({
            vendorId,
            module: EMAIL_ATTACHMENT_MODULE,
            file,
            userId,
            maxSizeField: 'attachmentSizeAllowed',
            allowedFormatsField: 'allowedAttachmentExtensions',
            maxCountField: 'numberOfAttachmentsAllowed',
            companyMasterData,
            websiteMasterData
        });
        if (!upload.isSuccess) {
            return upload;
        }
        const asset = upload.meta.file;

        const updated = await CompanySettings.findOneAndUpdate(
            { vendorId },
            {
                $push: {
                    emailAttachments: {
                        fileAssetId: asset._id,
                        url: asset.url,
                        originalName: asset.originalName,
                        displayName: (displayName && displayName.trim()) || asset.originalName,
                        mimeType: asset.mimeType,
                        size: asset.size,
                        uploadedAt: new Date()
                    }
                }
            },
            { new: true, projection: { emailAttachments: 1, emailImages: 1 } }
        ).lean();
        await redisService.del(redisKeys.companySettings(vendorId));

        logger.logInfo(1, 0, 'Email attachment added', { vendorId, fileAssetId: asset._id });
        return common.returnResult(true, 201, 'Attachment added successfully', emailContentLists(updated));
    } catch (err) {
        throw err;
    }
};

// Removal isn't gated by the feature - a vendor can always clear out files.
const removeEmailAttachment = async (vendorId, userId, attachmentId) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId, 'emailAttachments._id': attachmentId }, { emailAttachments: 1 }).lean();
        const entry = settings && settings.emailAttachments.find((a) => String(a._id) === String(attachmentId));
        if (!entry) {
            return common.returnResult(false, 404, 'Attachment not found.');
        }

        const removal = await fileUploadService.deleteFile({ vendorId, fileId: entry.fileAssetId, userId });
        if (!removal.isSuccess && removal.statusCode !== 404) {
            return removal;
        }

        const updated = await CompanySettings.findOneAndUpdate(
            { vendorId },
            { $pull: { emailAttachments: { _id: entry._id } } },
            { new: true, projection: { emailAttachments: 1, emailImages: 1 } }
        ).lean();
        await redisService.del(redisKeys.companySettings(vendorId));

        await emailTemplateMasterService.removeLibraryFileFromTemplates(vendorId, { attachmentId: entry._id });

        logger.logInfo(1, 0, 'Email attachment removed', { vendorId, attachmentId });
        return common.returnResult(true, 200, 'Attachment removed successfully', emailContentLists(updated));
    } catch (err) {
        throw err;
    }
};

// name: the short name a template uses to place the image, e.g. {{image:logo}}.
const addEmailImage = async (vendorId, userId, file, name, companyMasterData, websiteMasterData) => {
    try {
        if (!isTwoLevelOn('isAddingOfImageAllowed', companyMasterData, websiteMasterData)) {
            return common.returnResult(false, 403, 'Email images are not available for your account.');
        }
        const settings = await CompanySettings.findOne({ vendorId }, { emailImages: 1 }).lean();
        if (!settings) {
            return common.returnResult(false, 404, 'Please save your company settings first, then add images.');
        }
        const images = settings.emailImages || [];
        const maxCount = companyMasterData?.numberOfImageAllowed;
        if (maxCount != null && images.length >= maxCount) {
            return common.returnResult(false, 400, `You can keep at most ${maxCount} image(s). Remove one to add another.`);
        }
        const imageName = String(name).trim().toLowerCase();
        if (images.some((img) => img.name === imageName)) {
            return common.returnResult(false, 409, `An image named "${imageName}" already exists. Please choose another name.`);
        }

        const upload = await imageUploadService.uploadImage({
            vendorId,
            module: EMAIL_IMAGE_MODULE,
            file,
            userId,
            maxSizeField: 'imageSizeAllowed',
            allowedFormatsField: 'allowedImageExtensions',
            maxCountField: 'numberOfImageAllowed',
            companyMasterData,
            websiteMasterData
        });
        if (!upload.isSuccess) {
            return upload;
        }
        const asset = upload.meta.image;

        const updated = await CompanySettings.findOneAndUpdate(
            { vendorId },
            {
                $push: {
                    emailImages: {
                        imageAssetId: asset._id,
                        name: imageName,
                        url: asset.url,
                        originalName: asset.originalName,
                        mimeType: asset.mimeType,
                        size: asset.size,
                        uploadedAt: new Date()
                    }
                }
            },
            { new: true, projection: { emailAttachments: 1, emailImages: 1 } }
        ).lean();
        await redisService.del(redisKeys.companySettings(vendorId));

        logger.logInfo(1, 0, 'Email image added', { vendorId, imageAssetId: asset._id, name: imageName });
        return common.returnResult(true, 201, 'Image added successfully', emailContentLists(updated));
    } catch (err) {
        throw err;
    }
};

const removeEmailImage = async (vendorId, userId, imageId) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId, 'emailImages._id': imageId }, { emailImages: 1 }).lean();
        const entry = settings && settings.emailImages.find((img) => String(img._id) === String(imageId));
        if (!entry) {
            return common.returnResult(false, 404, 'Image not found.');
        }

        const removal = await imageUploadService.deleteImage({ imageId: entry.imageAssetId, userId });
        if (!removal.isSuccess && removal.statusCode !== 404) {
            return removal;
        }

        const updated = await CompanySettings.findOneAndUpdate(
            { vendorId },
            { $pull: { emailImages: { _id: entry._id } } },
            { new: true, projection: { emailAttachments: 1, emailImages: 1 } }
        ).lean();
        await redisService.del(redisKeys.companySettings(vendorId));

        await emailTemplateMasterService.removeLibraryFileFromTemplates(vendorId, { imageId: entry._id });

        logger.logInfo(1, 0, 'Email image removed', { vendorId, imageId });
        return common.returnResult(true, 200, 'Image removed successfully', emailContentLists(updated));
    } catch (err) {
        throw err;
    }
};


/*
|--------------------------------------------------------------------------
| THE VENDOR'S OWN EMAIL ACCOUNT (SMTP)
|--------------------------------------------------------------------------
| Only while email is granted to the vendor (isSendingEmailFeatureOn at both
| levels). Saved only after the server accepted the sign-in, so a wrong
| password is caught at once. The password is encrypted and never returned.
*/

// What the page may see of the account - never the password.
const toPublicEmailAccount = (account) => {
    try {
        if (!account || !account.host) return null;
        return {
            host: account.host,
            port: account.port,
            security: account.security,
            username: account.username,
            fromEmail: account.fromEmail,
            fromName: account.fromName,
            hasPassword: !!account.encryptedPassword,
            verifiedAt: account.verifiedAt
        };
    } catch (err) {
        throw err;
    }
};

const checkEmailGranted = (companyMasterData, websiteMasterData) => {
    try {
        if (!isTwoLevelOn('isSendingEmailFeatureOn', companyMasterData, websiteMasterData)) {
            return common.returnResult(false, 403, 'Email is not available for your account.');
        }
        return common.returnResult(true, 200, 'Email is on');
    } catch (err) {
        throw err;
    }
};

const fetchEmailAccount = async (vendorId, companyMasterData, websiteMasterData) => {
    try {
        const gate = checkEmailGranted(companyMasterData, websiteMasterData);
        if (!gate.isSuccess) return gate;
        const settings = await CompanySettings.findOne({ vendorId }, { emailAccount: 1 }).lean();
        return common.returnResult(true, 200, 'Email account fetched successfully', { emailAccount: toPublicEmailAccount(settings?.emailAccount) });
    } catch (err) {
        throw err;
    }
};

// Turns an SMTP sign-in failure into something a vendor can act on.
const describeSmtpError = (err) => {
    try {
        const raw = String((err && (err.response || err.message)) || 'Unknown error');
        if (err && (err.code === 'EAUTH' || /535|534|auth/i.test(raw))) {
            return `The email server rejected the username or password (${raw.slice(0, 160)}). For Gmail, use an App Password - not your normal password - and make sure 2-Step Verification is on.`;
        }
        if (err && (['ECONNECTION', 'ETIMEDOUT', 'ESOCKET', 'ENOTFOUND', 'ECONNREFUSED', 'EDNS', 'EHOSTUNREACH'].includes(err.code)
            || /ENOTFOUND|ECONNREFUSED|ETIMEDOUT|EHOSTUNREACH/.test(raw))) {
            return `Could not connect to ${err.address || 'the email server'} - check the server, port and security setting (${raw.slice(0, 160)}).`;
        }
        return `The email server said: ${raw.slice(0, 200)}`;
    } catch (e) {
        throw e;
    }
};

// data: { host, port, security, username, password?, fromEmail?, fromName? }.
// password may be left out to keep the saved one.
const saveEmailAccount = async (vendorId, userId, data, companyMasterData, websiteMasterData) => {
    try {
        const gate = checkEmailGranted(companyMasterData, websiteMasterData);
        if (!gate.isSuccess) return gate;

        const settings = await CompanySettings.findOne({ vendorId }, { emailAccount: 1 }).lean();
        if (!settings) {
            return common.returnResult(false, 404, 'Please save your company settings first, then add your email account.');
        }
        const saved = settings.emailAccount || {};

        const password = data.password
            ? data.password
            : (saved.encryptedPassword ? common.decryptSecret(saved.encryptedPassword) : null);
        if (!password) {
            return common.returnResult(false, 400, 'Please enter the password (for Gmail, the App Password).');
        }
        const account = {
            host: data.host,
            port: data.port,
            security: data.security,
            username: data.username,
            fromEmail: data.fromEmail || (String(data.username).includes('@') ? String(data.username).toLowerCase() : null),
            fromName: data.fromName || null
        };
        if (!account.fromEmail) {
            return common.returnResult(false, 400, 'Please enter the From address - the username is not an email address.');
        }

        try {
            await vendorSmtpProvider.verifyAccount(account, password);
        } catch (smtpErr) {
            logger.logInfo(0, 1, 'Vendor email account sign-in failed', { vendorId, host: account.host, code: smtpErr && smtpErr.code });
            return common.returnResult(false, 400, describeSmtpError(smtpErr));
        }

        const emailAccount = { ...account, encryptedPassword: common.encryptSecret(password), verifiedAt: new Date() };
        await CompanySettings.updateOne({ vendorId }, { $set: { emailAccount, updatedBy: { userID: userId, vendorID: vendorId } } });
        await redisService.del(redisKeys.companySettings(vendorId));
        vendorSmtpProvider.forgetVendor(vendorId);

        logger.logInfo(1, 0, 'Vendor email account saved', { vendorId, host: account.host });
        return common.returnResult(true, 200, 'Email account saved - the server accepted the sign-in.', { emailAccount: toPublicEmailAccount(emailAccount) });
    } catch (err) {
        throw err;
    }
};

// Removing it stops every email of the vendor until a new one is added.
const removeEmailAccount = async (vendorId, userId) => {
    try {
        await CompanySettings.updateOne({ vendorId }, { $unset: { emailAccount: 1 }, $set: { updatedBy: { userID: userId, vendorID: vendorId } } });
        await redisService.del(redisKeys.companySettings(vendorId));
        vendorSmtpProvider.forgetVendor(vendorId);
        logger.logInfo(1, 0, 'Vendor email account removed', { vendorId });
        return common.returnResult(true, 200, 'Email account removed. No emails will be sent until you add one again.', { emailAccount: null });
    } catch (err) {
        throw err;
    }
};

// Sends a short test email through the saved account (to `to`, else the
// account's own address) - goes through the normal checks (feature, quota).
const sendTestEmail = async (vendorId, userId, to, companyMasterData, websiteMasterData) => {
    try {
        const gate = checkEmailGranted(companyMasterData, websiteMasterData);
        if (!gate.isSuccess) return gate;
        const settings = await CompanySettings.findOne({ vendorId }).lean();
        if (!vendorSmtpProvider.isAccountReady(settings?.emailAccount)) {
            return common.returnResult(false, 400, 'Save your email account first.');
        }
        const recipient = to || settings.emailAccount.fromEmail || settings.emailAccount.username;
        const result = await emailService.sendEmail({
            vendorId,
            module: 'emailAccountTest',
            to: recipient,
            subject: 'Test email from your store',
            html: '<p>This is a test email. Your email account is set up correctly - your store\'s emails will be sent from this account.</p>',
            text: 'This is a test email. Your email account is set up correctly - your store\'s emails will be sent from this account.',
            userId,
            companyMasterData,
            websiteMasterData,
            companySettingsData: settings,
            isDefaultTemplate: true,
            includeCompanyCc: false,
            includeCompanyBcc: false
        }).catch((sendErr) => common.returnResult(false, 400, describeSmtpError(sendErr)));
        if (!result.isSuccess) return result;
        return common.returnResult(true, 200, `Test email sent to ${recipient}.`);
    } catch (err) {
        throw err;
    }
};

// --- Catalogue (storefront "Download catalogue" icon) ----------------------
const CATALOGUE_MODULE = 'catalogue';
const CATALOGUE_MAX_MB = 25;

const CATALOGUE_FLAG = 'isCatalogueDownloadFeatureOn';

// Vendor-level only - there is deliberately no WebsiteMaster switch for this.
const isCatalogueOn = (companyMasterData) => companyMasterData?.[CATALOGUE_FLAG] === true;

// Uploads (or replaces) the vendor's catalogue PDF.
const setCatalogue = async (vendorId, userId, file, companyMasterData, websiteMasterData) => {
    try {
        if (!isCatalogueOn(companyMasterData)) {
            return common.returnResult(false, 403, 'Catalogue download is not available for your account.');
        }
        if (!file || !file.buffer) {
            return common.returnResult(false, 400, 'Choose a PDF file to upload.');
        }
        if (!/\.pdf$/i.test(file.originalname || '')) {
            return common.returnResult(false, 400, 'The catalogue must be a PDF file.');
        }
        if (file.size > CATALOGUE_MAX_MB * 1024 * 1024) {
            return common.returnResult(false, 400, `The catalogue must be ${CATALOGUE_MAX_MB}MB or smaller.`);
        }
        const existing = await CompanySettings.findOne({ vendorId }, { catalogue: 1 }).lean();
        if (!existing) {
            return common.returnResult(false, 404, 'Please save your company settings first, then upload the catalogue.');
        }

        // Content is verified too (a renamed non-PDF is rejected) by uploadFile.
        const upload = await fileUploadService.uploadFile({
            vendorId, module: CATALOGUE_MODULE, file, userId, companyMasterData, websiteMasterData
        });
        if (!upload.isSuccess) {
            return upload;
        }
        const asset = upload.meta.file;
        if (asset.mimeType !== 'application/pdf') {
            await fileUploadService.deleteFile({ vendorId, fileId: asset._id, userId });
            return common.returnResult(false, 400, 'The catalogue must be a PDF file.');
        }

        const updated = await CompanySettings.findOneAndUpdate(
            { vendorId },
            { $set: { catalogue: { fileAssetId: asset._id, originalName: asset.originalName, size: asset.size, uploadedAt: new Date() } } },
            { new: true, projection: { catalogue: 1 } }
        ).lean();
        await redisService.del(redisKeys.companySettings(vendorId));

        // The replaced file is no longer referenced anywhere - remove it.
        if (existing.catalogue?.fileAssetId) {
            const removal = await fileUploadService.deleteFile({ vendorId, fileId: existing.catalogue.fileAssetId, userId });
            if (!removal.isSuccess && removal.statusCode !== 404) {
                logger.logInfo(1, 0, 'Old catalogue file could not be removed', { vendorId, fileAssetId: existing.catalogue.fileAssetId });
            }
        }

        logger.logInfo(1, 0, 'Catalogue uploaded', { vendorId, fileAssetId: asset._id });
        return common.returnResult(true, 201, 'Catalogue uploaded successfully', { catalogue: updated.catalogue });
    } catch (err) {
        throw err;
    }
};

const removeCatalogue = async (vendorId, userId) => {
    try {
        const existing = await CompanySettings.findOne({ vendorId }, { catalogue: 1 }).lean();
        if (!existing?.catalogue?.fileAssetId) {
            return common.returnResult(false, 404, 'There is no catalogue to remove.');
        }
        const removal = await fileUploadService.deleteFile({ vendorId, fileId: existing.catalogue.fileAssetId, userId });
        if (!removal.isSuccess && removal.statusCode !== 404) {
            return removal;
        }
        await CompanySettings.updateOne(
            { vendorId },
            { $set: { catalogue: { fileAssetId: null, originalName: null, size: null, uploadedAt: null } } }
        );
        await redisService.del(redisKeys.companySettings(vendorId));

        logger.logInfo(1, 0, 'Catalogue removed', { vendorId });
        return common.returnResult(true, 200, 'Catalogue removed successfully', { catalogue: null });
    } catch (err) {
        throw err;
    }
};

// Bytes of the catalogue for the public download route; 404 when the
// feature is off or nothing is uploaded.
const getCatalogueFile = async (vendorId, companyMasterData, websiteMasterData) => {
    try {
        if (!isCatalogueOn(companyMasterData)) {
            return common.returnResult(false, 404, 'Catalogue not available.');
        }
        const settings = await CompanySettings.findOne({ vendorId }, { catalogue: 1 }).lean();
        if (!settings?.catalogue?.fileAssetId) {
            return common.returnResult(false, 404, 'Catalogue not available.');
        }
        const asset = await FileAsset.findOne({ _id: settings.catalogue.fileAssetId, vendorId, status: 'A' }).lean();
        if (!asset) {
            return common.returnResult(false, 404, 'Catalogue not available.');
        }
        const buffer = await readStoredAsset(asset);
        return common.returnResult(true, 200, 'OK', { buffer, fileName: asset.originalName || 'catalogue.pdf' });
    } catch (err) {
        throw err;
    }
};

module.exports = {
  setCatalogue,
  removeCatalogue,
  getCatalogueFile,
  isCatalogueOn,
  createCompanySettings,
  updateCompanySettings,
  fetchCompanySettingsByVendorId,
  assignEmailTemplate,
  unassignEmailTemplate,
  fetchAssignedOrderSteps,
  getEmailFeatureAccess,
  addEmailAttachment,
  removeEmailAttachment,
  addEmailImage,
  removeEmailImage,
  fetchEmailAccount,
  saveEmailAccount,
  removeEmailAccount,
  sendTestEmail
};