const CompanySettings = require('../models/CompanySettings');
const EmailTemplateMaster = require('../models/EmailTemplateMaster');
const redisService = require('./redisService');
const redisKeys = require('../utils/redisKeys');
const logger = require('../utils/logger');
const common = require('../utils/common');
const imageUploadService = require('./imageUploadService');
const CountryMaster = require('../models/CountryMaster');
const StateMaster = require('../models/StateMaster');
const CityMaster = require('../models/CityMaster');
const CurrencyMaster = require('../models/CurrencyMaster');

// The store currency (every price is entered in it - see currencyService.js)
// must be an active currency, and can be changed but never cleared: orders
// can't be placed without one.
const validateStoreCurrency = async (data, existingSettings = null) => {
    try {
        if (data.currencyId === undefined) return null;
        if (!data.currencyId) {
            return existingSettings?.currencyId
                ? common.returnResult(false, 400, 'The store currency cannot be removed - choose another currency instead.')
                : null;
        }
        const currency = await CurrencyMaster.findOne({ _id: data.currencyId, status: 'A' }).select('_id').lean();
        if (!currency) {
            return common.returnResult(false, 400, 'The selected store currency is not available.');
        }
        return null;
    } catch (err) {
        throw err;
    }
};

// Every field a vendor is allowed to set directly through create/update -
// deliberately excludes vendorId, companyLogo/paymentScanner/partnerCertificate
// (handled separately as file uploads) and emailTemplateAssignments (owned by
// the dedicated assign/unassign endpoints above).
const SIMPLE_FIELDS = [
    'currencyId', 'storeCountryId', 'storeStateId', 'storeCityId', 'adminName', 'adminWhatsappNumber', 'adminPhoneNumber', 'adminAddress',
    'adminCity', 'adminState', 'adminPincode', 'adminEmail', 'companyName', 'instagramId',
    'facebookId', 'privacyPolicy', 'cancelPolicy', 'termsAndConditions', 'aboutUs',
    'showAnnouncements', 'isAnnouncementRotationOn', 'showBanners', 'isBannerRotationOn',
    'isTaxRegistrationOnSignupEnabled',
    'taxRegistrationNumber', 'invoicePrefix', 'invoiceDeclaration',
    'invoicePrintDuplicateCopy', 'invoiceRoundOffToWhole', 'emailInvoiceOnOrderPlaced',
    'showReviewsToCustomers', 'isProductCodeAutoGenerated', 'isVariantCodeAutoGenerated',
    'isSizeCodeAutoGenerated', 'shouldProductsBeHiddenWhenLocationsAreExcluded',
    'useShortNameForBrand', 'allowOutOfStockProductsAdding', 'fewItemsReturnOnly',
    'fewItemsExchangeOnly', 'isOrderCancellationAllowed', 'orderCancellationNotAllowedAfterStep',
    'isOrderNumberAutoGenerated', 'senderEmail', 'ccList', 'bccList', 'isPaymentGatewayFeatureOn',
    'isFreeCashFeatureOn', 'isFreeCashStackingAllowed', 'isMultipleFreeCashUsageAllowed',
    'isStoringRemainingFreeCashAmountAllowed', 'returnFreeCashOnOrderReturn', 'refundWholeFreeCashAmount',
    'amountToRefund', 'timeForAbondonedCartReflection', 'abondonedCartOnlyForLoggedInUsers',
    'bankAccountHolderName', 'bankName', 'bankAccountNumber', 'ifscCode', 'branchName',
    'swiftCode', 'bankAccountType'
];

// Fields gated together with paymentScanner behind
// CompanyMaster.showPaymentQRCodeAndBankDetails (+
// WebsiteMaster.isShowingPaymentQRCodeAndBankDetailsFeatureOn).
const BANK_TRANSFER_FIELDS = [
    'bankAccountHolderName', 'bankName', 'bankAccountNumber', 'ifscCode', 'branchName',
    'swiftCode', 'bankAccountType'
];

// '' and undefined/null are the same "empty" value for this comparison -
// Joi normalizes bankAccountType's '' to null before this runs, but the
// plain string bank fields (bankAccountHolderName etc.) are only
// .allow('', null), so an untouched form field can legitimately arrive as
// either depending on which one the caller used.
const normalizeEmpty = (value) => (value === undefined || value === '' ? null : value);

// Checks whether the request is actually CHANGING the bank-transfer group
// (any bank field whose incoming value differs from what's already stored,
// or a new paymentScanner file) or the partnerCertificate file, and if so,
// verifies the vendor is entitled to it. Returns null when nothing gated
// was actually touched (caller proceeds normally), otherwise returns the
// first failing returnResult().
//
// Deliberately diff-based rather than presence-based: a caller that sends
// its whole settings object on every save (not just the fields it means to
// change) would otherwise trip this gate on every single save, for a group
// it isn't even trying to edit - confirmed live via the admin Company
// Settings page, which 403'd on saving an unrelated toggle for a vendor not
// entitled to Bank Transfer, purely because it sent bankAccountHolderName:
// '' etc. alongside everything else.
const checkPaymentDetailsEntitlements = async (vendorId, data, files, companyMasterData, websiteMasterData, existingSettings = null) => {
    try {
        const bankGroupTouched = BANK_TRANSFER_FIELDS.some((field) => {
            if (data[field] === undefined) return false;
            const currentValue = existingSettings ? existingSettings[field] : undefined;
            return normalizeEmpty(data[field]) !== normalizeEmpty(currentValue);
        }) || !!files?.paymentScanner?.[0];
        if (bankGroupTouched) {
            const check = await common.checkFeatureOnOrOff(
                vendorId, websiteMasterData, companyMasterData,
                'isShowingPaymentQRCodeAndBankDetailsFeatureOn', 'showPaymentQRCodeAndBankDetails'
            );
            if (!check.isSuccess) return check;
        }

        const certificateTouched = !!files?.partnerCertificate?.[0];
        if (certificateTouched) {
            const check = await common.checkFeatureOnOrOff(
                vendorId, websiteMasterData, companyMasterData,
                'isShowingPartnerCertificateFeatureOn', 'isShowingPartnerCertificateFeatureOn'
            );
            if (!check.isSuccess) return check;
        }

        return null;
    } catch (err) {
        throw err;
    }
};

// Keeps the 3 return-Free-Cash fields internally consistent regardless of
// which subset of them a given create/update request actually touched -
// refundWholeFreeCashAmount/amountToRefund are meaningless (and forced back
// to their inapplicable default) whenever returnFreeCashOnOrderReturn is
// off, and amountToRefund specifically is meaningless whenever the whole
// amount is being refunded.
const normalizeFreeCashReturnFields = (target) => {
    if (target.returnFreeCashOnOrderReturn !== true) {
        target.refundWholeFreeCashAmount = false;
        target.amountToRefund = null;
    } else if (target.refundWholeFreeCashAmount === true) {
        target.amountToRefund = null;
    }
};

// Store country/state/city (the tax location when a customer's is unknown -
// see taxCalculationService.js) must be a consistent, active chain the vendor
// serves: country in CompanyMaster.allowedCountries, state inside that
// country, city inside that state. A state/city needs its parent set.
// Checked against the values the document will END UP with, so a partial
// update can't leave a state pointing at a different country.
const validateStoreLocation = async (data, companyMasterData, existingSettings = null) => {
    try {
        const pick = (field) => (data[field] !== undefined ? data[field] : (existingSettings ? existingSettings[field] : null)) || null;
        const countryId = pick('storeCountryId');
        const stateId = pick('storeStateId');
        const cityId = pick('storeCityId');

        if (!countryId && (stateId || cityId)) {
            return common.returnResult(false, 400, 'Select a store country before choosing a store state or city.');
        }
        if (!stateId && cityId) {
            return common.returnResult(false, 400, 'Select a store state before choosing a store city.');
        }
        if (!countryId) {
            return null;
        }

        const allowedCountryIds = (companyMasterData?.allowedCountries || []).map((id) => id.toString());
        if (!allowedCountryIds.includes(countryId.toString())) {
            return common.returnResult(false, 400, 'The selected store country is not one of the countries your store serves.');
        }
        const country = await CountryMaster.findOne({ _id: countryId, status: 'A' }).select('_id').lean();
        if (!country) {
            return common.returnResult(false, 400, 'The selected store country is not available.');
        }
        if (stateId) {
            const state = await StateMaster.findOne({ _id: stateId, country_id: countryId, status: 'A' }).select('_id').lean();
            if (!state) {
                return common.returnResult(false, 400, 'The selected store state does not belong to the selected store country.');
            }
        }
        if (cityId) {
            const city = await CityMaster.findOne({ _id: cityId, state_id: stateId, status: 'A' }).select('_id').lean();
            if (!city) {
                return common.returnResult(false, 400, 'The selected store city does not belong to the selected store state.');
            }
        }
        return null;
    } catch (err) {
        throw err;
    }
};

const invalidateCompanySettingsCache = async (vendorId) => {
    try {
        await redisService.del(redisKeys.companySettings(vendorId));
        logger.logInfo(1, 0, 'Company settings cache invalidated', { vendorId });
    } catch (err) {
        throw err;
    }
};

const createCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const existing = await CompanySettings.findOne({ vendorId });
        if (existing) {
            return common.returnResult(false, 409, 'Company settings already exist for this vendor. Use update instead.');
        }

        const entitlementFailure = await checkPaymentDetailsEntitlements(vendorId, data, files, companyMasterData, websiteMasterData);
        if (entitlementFailure) {
            return entitlementFailure;
        }

        const storeLocationFailure = await validateStoreLocation(data, companyMasterData);
        if (storeLocationFailure) {
            return storeLocationFailure;
        }

        const storeCurrencyFailure = await validateStoreCurrency(data);
        if (storeCurrencyFailure) {
            return storeCurrencyFailure;
        }

        const settingsData = { vendorId };
        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settingsData[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settingsData);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        const certificateFile = files?.partnerCertificate?.[0];
        if (certificateFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'partnerCertificate', file: certificateFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.partnerCertificate = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        settingsData.createdBy = { userID: userId, vendorID: vendorId };
        settingsData.updatedBy = { userID: userId, vendorID: vendorId };

        const settings = new CompanySettings(settingsData);
        const saved = await settings.save();

        logger.logInfo(1, 0, 'Company settings created successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 201, 'Company settings created successfully', { settings: saved });
    } catch (err) {
        throw err;
    }
};

const updateCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            return common.returnResult(false, 404, 'Company settings not found. Please create them first.');
        }

        const entitlementFailure = await checkPaymentDetailsEntitlements(vendorId, data, files, companyMasterData, websiteMasterData, settings);
        if (entitlementFailure) {
            return entitlementFailure;
        }

        const storeLocationFailure = await validateStoreLocation(data, companyMasterData, settings);
        if (storeLocationFailure) {
            return storeLocationFailure;
        }

        const storeCurrencyFailure = await validateStoreCurrency(data, settings);
        if (storeCurrencyFailure) {
            return storeCurrencyFailure;
        }

        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settings[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settings);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            if (settings.companyLogo?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.companyLogo.imageAssetId, file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.companyLogo = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            if (settings.paymentScanner?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.paymentScanner.imageAssetId, file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.paymentScanner = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        const certificateFile = files?.partnerCertificate?.[0];
        if (certificateFile) {
            if (settings.partnerCertificate?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.partnerCertificate.imageAssetId, file: certificateFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.partnerCertificate = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'partnerCertificate', file: certificateFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.partnerCertificate = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        settings.updatedBy = { userID: userId, vendorID: vendorId };

        const updated = await settings.save();
        logger.logInfo(1, 0, 'Company settings updated successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 200, 'Company settings updated successfully', { settings: updated });
    } catch (err) {
        throw err;
    }
};

const fetchCompanySettingsByVendorId = async (vendorId) => {
    try {
        logger.logInfo(null,null,'Fetching company settings from DB', { vendorId });
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            logger.logInfo(0,1,'Company settings not found', { vendorId });
            return null;
        }
        logger.logInfo(1,0,'Company settings fetched successfully', { vendorId });
        return settings;
    } catch (err) {
        throw err;
    }
}

// Tags the vendor's own templateId against `module` - at most one entry per
// module (replaces any existing entry for that module). Invalidates the
// Redis cache afterwards so ensureVendorDataCached picks up the change on
// the very next request instead of serving stale companySettingsData for
// up to an hour.
const assignEmailTemplate = async (vendorId, module, templateId, userId) => {
    try {
        const template = await EmailTemplateMaster.findOne({ _id: templateId, vendorId, status: { $ne: 'D' } });
        if (!template) {
            return common.returnResult(false, 404, 'Email template not found');
        }

        const settingsExists = await CompanySettings.exists({ vendorId });
        if (!settingsExists) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        // Targeted updates rather than load-and-save(): save() revalidates every
        // required field on the whole document, so an unrelated gap in the
        // vendor's settings (e.g. adminName not filled in yet) would block a
        // change that only touches emailTemplateAssignments.
        const updatedBy = { userID: userId, vendorID: vendorId };
        await CompanySettings.updateOne({ vendorId }, { $pull: { emailTemplateAssignments: { module } } });
        await CompanySettings.updateOne({ vendorId }, { $push: { emailTemplateAssignments: { module, templateId } }, $set: { updatedBy } });
        await redisService.del(redisKeys.companySettings(vendorId));

        const settings = await CompanySettings.findOne({ vendorId });

        logger.logInfo(1, 0, 'Email template assigned to module', { vendorId, module, templateId });
        return common.returnResult(true, 200, 'Email template assigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};

const unassignEmailTemplate = async (vendorId, module, userId) => {
    try {
        const settingsExists = await CompanySettings.exists({ vendorId });
        if (!settingsExists) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        await CompanySettings.updateOne(
            { vendorId },
            { $pull: { emailTemplateAssignments: { module } }, $set: { updatedBy: { userID: userId, vendorID: vendorId } } }
        );
        await redisService.del(redisKeys.companySettings(vendorId));

        const settings = await CompanySettings.findOne({ vendorId });

        logger.logInfo(1, 0, 'Email template unassigned from module', { vendorId, module });
        return common.returnResult(true, 200, 'Email template unassigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};

module.exports = {
  createCompanySettings,
  updateCompanySettings,
  fetchCompanySettingsByVendorId,
  assignEmailTemplate,
  unassignEmailTemplate
};