const CompanySettings = require('../models/CompanySettings');
const EmailTemplateMaster = require('../models/EmailTemplateMaster');
const redisService = require('./redisService');
const redisKeys = require('../utils/redisKeys');
const logger = require('../utils/logger');
const common = require('../utils/common');
const imageUploadService = require('./imageUploadService');

// Every field a vendor is allowed to set directly through create/update -
// deliberately excludes vendorId, companyLogo/paymentScanner (handled
// separately as file uploads) and emailTemplateAssignments (owned by the
// dedicated assign/unassign endpoints above).
const SIMPLE_FIELDS = [
    'currencyId', 'adminName', 'adminWhatsappNumber', 'adminPhoneNumber', 'adminAddress',
    'adminCity', 'adminState', 'adminPincode', 'adminEmail', 'companyName', 'instagramId',
    'facebookId', 'privacyPolicy', 'cancelPolicy', 'termsAndConditions', 'aboutUs',
    'showAnnouncements', 'isAnnouncementRotationOn', 'showBanners', 'isBannerRotationOn',
    'showReviewsToCustomers', 'isProductCodeAutoGenerated', 'isVariantCodeAutoGenerated',
    'isSizeCodeAutoGenerated', 'shouldProductsBeHiddenWhenLocationsAreExcluded',
    'useShortNameForBrand', 'allowOutOfStockProductsAdding', 'fewItemsReturnOnly',
    'fewItemsExchangeOnly', 'isOrderCancellationAllowed', 'orderCancellationNotAllowedAfterStep',
    'isOrderNumberAutoGenerated', 'senderEmail', 'ccList', 'bccList', 'isPaymentGatewayFeatureOn',
    'isFreeCashFeatureOn', 'isFreeCashStackingAllowed', 'isMultipleFreeCashUsageAllowed',
    'isStoringRemainingFreeCashAmountAllowed', 'returnFreeCashOnOrderReturn', 'refundWholeFreeCashAmount',
    'amountToRefund', 'timeForAbondonedCartReflection', 'abondonedCartOnlyForLoggedInUsers'
];

// Keeps the 3 return-Free-Cash fields internally consistent regardless of
// which subset of them a given create/update request actually touched -
// refundWholeFreeCashAmount/amountToRefund are meaningless (and forced back
// to their inapplicable default) whenever returnFreeCashOnOrderReturn is
// off, and amountToRefund specifically is meaningless whenever the whole
// amount is being refunded.
const normalizeFreeCashReturnFields = (target) => {
    if (target.returnFreeCashOnOrderReturn !== true) {
        target.refundWholeFreeCashAmount = false;
        target.amountToRefund = null;
    } else if (target.refundWholeFreeCashAmount === true) {
        target.amountToRefund = null;
    }
};

const invalidateCompanySettingsCache = async (vendorId) => {
    try {
        await redisService.del(redisKeys.companySettings(vendorId));
        logger.logInfo(1, 0, 'Company settings cache invalidated', { vendorId });
    } catch (err) {
        throw err;
    }
};

const createCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const existing = await CompanySettings.findOne({ vendorId });
        if (existing) {
            return common.returnResult(false, 409, 'Company settings already exist for this vendor. Use update instead.');
        }

        const settingsData = { vendorId };
        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settingsData[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settingsData);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            const uploadResult = await imageUploadService.uploadImage({
                vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
            });
            if (!uploadResult.isSuccess) {
                return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
            }
            settingsData.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
        }

        settingsData.createdBy = { userID: userId, vendorID: vendorId };
        settingsData.updatedBy = { userID: userId, vendorID: vendorId };

        const settings = new CompanySettings(settingsData);
        const saved = await settings.save();

        logger.logInfo(1, 0, 'Company settings created successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 201, 'Company settings created successfully', { settings: saved });
    } catch (err) {
        throw err;
    }
};

const updateCompanySettings = async (vendorId, userId, data, files, companyMasterData, websiteMasterData) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            return common.returnResult(false, 404, 'Company settings not found. Please create them first.');
        }

        for (const field of SIMPLE_FIELDS) {
            if (data[field] !== undefined) {
                settings[field] = data[field];
            }
        }
        normalizeFreeCashReturnFields(settings);

        const logoFile = files?.companyLogo?.[0];
        if (logoFile) {
            if (settings.companyLogo?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.companyLogo.imageAssetId, file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.companyLogo = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'companyLogo', file: logoFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.companyLogo = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        const scannerFile = files?.paymentScanner?.[0];
        if (scannerFile) {
            if (settings.paymentScanner?.imageAssetId) {
                const imageUpdateResult = await imageUploadService.updateImage({
                    imageId: settings.paymentScanner.imageAssetId, file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!imageUpdateResult.isSuccess) {
                    return common.returnResult(false, imageUpdateResult.statusCode, imageUpdateResult.message);
                }
                settings.paymentScanner = { url: imageUpdateResult.meta.image.url, imageAssetId: imageUpdateResult.meta.image._id };
            } else {
                const uploadResult = await imageUploadService.uploadImage({
                    vendorId, module: 'paymentScanner', file: scannerFile, userId, companyMasterData, websiteMasterData
                });
                if (!uploadResult.isSuccess) {
                    return common.returnResult(false, uploadResult.statusCode, uploadResult.message);
                }
                settings.paymentScanner = { url: uploadResult.meta.image.url, imageAssetId: uploadResult.meta.image._id };
            }
        }

        settings.updatedBy = { userID: userId, vendorID: vendorId };

        const updated = await settings.save();
        logger.logInfo(1, 0, 'Company settings updated successfully', { vendorId });
        await invalidateCompanySettingsCache(vendorId);

        return common.returnResult(true, 200, 'Company settings updated successfully', { settings: updated });
    } catch (err) {
        throw err;
    }
};

const fetchCompanySettingsByVendorId = async (vendorId) => {
    try {
        logger.logInfo(null,null,'Fetching company settings from DB', { vendorId });
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            logger.logInfo(0,1,'Company settings not found', { vendorId });
            return null;
        }
        logger.logInfo(1,0,'Company settings fetched successfully', { vendorId });
        return settings;
    } catch (err) {
        throw err;
    }
}

// Tags the vendor's own templateId against `module` - at most one entry per
// module (replaces any existing entry for that module). Invalidates the
// Redis cache afterwards so ensureVendorDataCached picks up the change on
// the very next request instead of serving stale companySettingsData for
// up to an hour.
const assignEmailTemplate = async (vendorId, module, templateId, userId) => {
    try {
        const template = await EmailTemplateMaster.findOne({ _id: templateId, vendorId, status: { $ne: 'D' } });
        if (!template) {
            return common.returnResult(false, 404, 'Email template not found');
        }

        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        settings.emailTemplateAssignments = settings.emailTemplateAssignments.filter((a) => a.module !== module);
        settings.emailTemplateAssignments.push({ module, templateId });
        settings.updatedBy = { userID: userId, vendorID: vendorId };

        await settings.save();
        await redisService.del(redisKeys.companySettings(vendorId));

        logger.logInfo(1, 0, 'Email template assigned to module', { vendorId, module, templateId });
        return common.returnResult(true, 200, 'Email template assigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};

const unassignEmailTemplate = async (vendorId, module, userId) => {
    try {
        const settings = await CompanySettings.findOne({ vendorId });
        if (!settings) {
            return common.returnResult(false, 404, 'Company settings not found');
        }

        settings.emailTemplateAssignments = settings.emailTemplateAssignments.filter((a) => a.module !== module);
        settings.updatedBy = { userID: userId, vendorID: vendorId };

        await settings.save();
        await redisService.del(redisKeys.companySettings(vendorId));

        logger.logInfo(1, 0, 'Email template unassigned from module', { vendorId, module });
        return common.returnResult(true, 200, 'Email template unassigned successfully', { settings });
    } catch (err) {
        throw err;
    }
};

module.exports = {
  createCompanySettings,
  updateCompanySettings,
  fetchCompanySettingsByVendorId,
  assignEmailTemplate,
  unassignEmailTemplate
};