const mongoose = require('mongoose');
const Order = require('../models/Order');
const Address = require('../models/Address');
const User = require('../models/User');
const CurrencyMaster = require('../models/CurrencyMaster');
const OrderStepMaster = require('../models/OrderStepMaster');
const cartService = require('./cartService');
const counterService = require('./counterService');
const common = require('../utils/common');
const logger = require('../utils/logger');
const {
    RESERVED_STEP_CODES,
    TERMINAL_STEP_CODES,
    DELIVERY_AGENT_FROM_STEP_CODE,
    DELIVERY_AGENT_TO_STEP_CODE
} = require('../constants/orderStepConstants');

/*
|--------------------------------------------------------------------------
| ORDER NUMBER
|--------------------------------------------------------------------------
| Same auto/manual pattern as resolveProductCode/resolveVariantCode/
| resolveSizeCode in productService.js.
*/
const resolveOrderNumber = async ({ vendorId, orderNumber, companySettingsData }) => {
    try {
        if (companySettingsData?.isOrderNumberAutoGenerated !== false) {
            if (orderNumber) {
                return common.returnResult(false, 400, 'Order number is auto-generated for this store and should not be provided.');
            }
            const nextValue = await counterService.getNextSequenceValue(vendorId, 'orderNumber');
            const generatedOrderNumber = `ORD-${String(nextValue).padStart(6, '0')}`;
            return common.returnResult(true, 200, 'All Good', { orderNumber: generatedOrderNumber });
        }

        if (!orderNumber) {
            return common.returnResult(false, 400, 'Order number is required.');
        }

        const normalizedOrderNumber = orderNumber.trim().toUpperCase();
        const existing = await Order.findOne({ vendorId, orderNumber: normalizedOrderNumber });
        if (existing) {
            return common.returnResult(false, 409, 'Order number already exists.');
        }

        return common.returnResult(true, 200, 'All Good', { orderNumber: normalizedOrderNumber });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| CURRENCY
|--------------------------------------------------------------------------
| Precedence: the logged-in user's own country's currency, falling back to
| the vendor's own base currency (CompanySettings.currencyId) when the
| user's country has no CurrencyMaster configured, or the user has no
| country on file at all.
*/
const resolveOrderCurrency = async (userCountryId, companySettingsData) => {
    try {
        let currency = null;

        if (userCountryId && mongoose.Types.ObjectId.isValid(userCountryId)) {
            currency = await CurrencyMaster.findOne({ country_id: userCountryId, status: 'A' });
        }

        if (!currency && companySettingsData?.currencyId) {
            currency = await CurrencyMaster.findOne({ _id: companySettingsData.currencyId, status: 'A' });
        }

        if (!currency) {
            return { error: 'Store currency is not configured. Please contact support.' };
        }

        return { currency };
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| ADDRESS SNAPSHOT
|--------------------------------------------------------------------------
*/
const buildAddressSnapshot = async (addressDoc) => {
    try {
        const locationNames = await common.resolveLocationNames({
            countryId: addressDoc.country_id,
            stateId: addressDoc.state_id,
            cityId: addressDoc.city_id
        });

        if (!locationNames.countryName || !locationNames.stateName || !locationNames.cityName) {
            return { error: 'Your address references a country/state/city that no longer exists. Please update your address.' };
        }

        return {
            snapshot: {
                addressName: addressDoc.address_name,
                roomNo: addressDoc.room_no,
                building: addressDoc.building,
                addressInWords: addressDoc.address_in_words,
                floor: addressDoc.floor || null,
                countryName: locationNames.countryName,
                stateName: locationNames.stateName,
                cityName: locationNames.cityName,
                pincode: addressDoc.pincode
            }
        };
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| ORDER CREATION (cart -> order)
|--------------------------------------------------------------------------
*/
const createOrderFromCart = async (vendorId, userId, userCountryId, locationContext, companyMasterData, websiteMasterData, companySettingsData, payload) => {
    try {
        const { shippingAddressId, billingAddressId, orderNumber } = payload;

        // --- Resolve + validate addresses (cheap, fail fast) ---
        const shippingAddress = await Address.findOne({ _id: shippingAddressId, userId, vendorId, status: 'A' });
        if (!shippingAddress) {
            return common.returnResult(false, 404, 'Shipping address not found.');
        }

        let billingAddress = null;
        if (billingAddressId) {
            billingAddress = await Address.findOne({ _id: billingAddressId, userId, vendorId, status: 'A' });
            if (!billingAddress) {
                return common.returnResult(false, 404, 'Billing address not found.');
            }
        }

        // --- Order caps ---
        const lifetimeLimit = companyMasterData?.numberOfOrdersAllowed;
        if (lifetimeLimit !== null && lifetimeLimit !== undefined) {
            const lifetimeCount = await Order.countDocuments({ vendorId, status: { $ne: 'D' } });
            if (lifetimeCount >= lifetimeLimit) {
                return common.returnResult(false, 403, 'This store has reached the maximum number of orders allowed on its current plan.');
            }
        }

        const monthlyLimit = companyMasterData?.numberOfOrdersAllowedPerMonth;
        if (monthlyLimit !== null && monthlyLimit !== undefined) {
            const startOfMonth = new Date();
            startOfMonth.setDate(1);
            startOfMonth.setHours(0, 0, 0, 0);
            const monthlyCount = await Order.countDocuments({ vendorId, status: { $ne: 'D' }, orderPlacedAt: { $gte: startOfMonth } });
            if (monthlyCount >= monthlyLimit) {
                return common.returnResult(false, 403, 'This store has reached the maximum number of orders allowed this month.');
            }
        }

        // --- Order step workflow (admin-assigned per vendor, not built by vendor) ---
        const orderStepMasterId = companyMasterData?.orderSteps;
        if (!orderStepMasterId) {
            return common.returnResult(false, 500, 'Order workflow is not configured for this store yet. Please contact support.');
        }

        const stepMaster = await OrderStepMaster.findOne({ _id: orderStepMasterId, status: 'A' });
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is not configured correctly for this store. Please contact support.');
        }

        const firstStep = stepMaster.steps.find((step) => step.sequence === 1);
        if (!firstStep) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this store (no starting step). Please contact support.');
        }

        // --- Currency ---
        const currencyResult = await resolveOrderCurrency(userCountryId, companySettingsData);
        if (currencyResult.error) {
            return common.returnResult(false, 500, currencyResult.error);
        }
        const currency = currencyResult.currency;

        // --- Order number (auto or vendor-configured manual) ---
        const orderNumberResult = await resolveOrderNumber({ vendorId, orderNumber, companySettingsData });
        if (!orderNumberResult.isSuccess) {
            return common.returnResult(false, orderNumberResult.statusCode, orderNumberResult.message);
        }

        // --- Address snapshots ---
        const shippingSnapshotResult = await buildAddressSnapshot(shippingAddress);
        if (shippingSnapshotResult.error) {
            return common.returnResult(false, 400, shippingSnapshotResult.error);
        }

        let billingSnapshot = null;
        if (billingAddress) {
            const billingSnapshotResult = await buildAddressSnapshot(billingAddress);
            if (billingSnapshotResult.error) {
                return common.returnResult(false, 400, billingSnapshotResult.error);
            }
            billingSnapshot = billingSnapshotResult.snapshot;
        }

        // --- Re-validate + price the cart one final time at the moment of commit ---
        const checkoutResult = await cartService.checkoutCart(
            vendorId,
            { type: 'user', id: userId },
            userId,
            locationContext,
            companyMasterData,
            websiteMasterData,
            companySettingsData
        );
        if (!checkoutResult.isSuccess) {
            return common.returnResult(false, checkoutResult.statusCode, checkoutResult.message);
        }

        const { cart, eligibleSubtotal, grandTotal, ineligibleItems } = checkoutResult.meta;

        // Narrows (but per the double-submit race, cannot fully close - the
        // unique {vendorId, cartId} index on Order is the hard backstop)
        // the window where the same cart could produce two orders.
        const existingOrderForCart = await Order.findOne({ vendorId, cartId: cart._id });
        if (existingOrderForCart) {
            return common.returnResult(false, 409, 'An order has already been placed for this cart.');
        }

        const order = new Order({
            orderNumber: orderNumberResult.meta.orderNumber,
            cartId: cart._id,
            vendorId,
            userId,
            orderStepMasterId: stepMaster._id,
            currentStepId: firstStep._id,
            currentStepCode: firstStep.code,
            currentStepName: firstStep.name,
            currentStepSequence: firstStep.sequence,
            statusHistory: [{
                stepId: firstStep._id,
                stepCode: firstStep.code,
                stepName: firstStep.name,
                sequence: firstStep.sequence,
                startedAt: new Date(),
                isManualUpdate: false
            }],
            subtotal: eligibleSubtotal,
            totalDiscountAmount: cart.totalDiscountAmount,
            totalTaxAmount: cart.totalTaxAmount,
            totalFreeCashAmount: cart.totalFreeCashAmount,
            // No shipping-fee-calculation service exists yet - defaults to 0
            // until one is built (same posture as payment method).
            shippingAmount: 0,
            additionalCharges: 0,
            grandTotal,
            currencyId: currency._id,
            currencyCode: currency.short_name,
            currencySymbol: currency.symbol,
            currencySymbolPosition: currency.symbol_position,
            currencyDecimalPlaces: currency.decimal_places,
            shippingAddressId: shippingAddress._id,
            shippingAddressSnapshot: shippingSnapshotResult.snapshot,
            billingAddressId: billingAddress ? billingAddress._id : null,
            billingAddressSnapshot: billingSnapshot,
            orderPlacedAt: new Date(),
            createdBy: userId
        });

        await order.save();

        // Locks the cart out of every existing cart route (all of which
        // filter on status:'A') so it can never be mutated or re-checked-out
        // again, and the user's next add-to-cart starts a fresh active cart.
        cart.status = 'D';
        cart.updatedBy = userId;
        await cart.save();

        logger.logInfo(1, 0, 'Order created successfully', { vendorId, userId, orderId: order._id });

        return common.returnResult(true, 201, 'Order placed successfully', { order, ineligibleItems });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| STEP TRANSITION HELPERS
|--------------------------------------------------------------------------
*/

// Closes whichever statusHistory entry is still open (completedAt: null)
// and opens a new one for the target step. Mutates `order` in place.
const closeCurrentHistoryEntryAndPushNext = (order, targetStep, changedByUserId, isManualUpdate) => {
    const now = new Date();
    const openEntry = [...order.statusHistory].reverse().find((entry) => entry.completedAt === null);
    if (openEntry) {
        openEntry.completedAt = now;
    }

    order.statusHistory.push({
        stepId: targetStep._id,
        stepCode: targetStep.code,
        stepName: targetStep.name,
        sequence: targetStep.sequence,
        startedAt: now,
        changedBy: changedByUserId,
        isManualUpdate
    });

    order.currentStepId = targetStep._id;
    order.currentStepCode = targetStep.code;
    order.currentStepName = targetStep.name;
    order.currentStepSequence = targetStep.sequence;
};

// No email-sending service exists yet in the codebase (same posture as
// payment method) - this is a placeholder hook, gated the same way every
// other paid feature is, so the call site is already wired up once a real
// email service is built.
const notifyOrderStatusChange = async (order, companyMasterData, websiteMasterData) => {
    try {
        const featureCheck = await common.checkFeatureOnOrOff(
            order.vendorId, websiteMasterData, companyMasterData,
            'isEmailSendingFeatureOnAfterOrderStatusChanges', 'isEmailSendingFeatureOnAfterOrderStatusChanges'
        );
        if (!featureCheck.isSuccess) {
            return;
        }

        logger.logInfo(1, 0, 'Order status change email notification would be sent here (email service not yet implemented)', {
            orderId: order._id, orderNumber: order.orderNumber, newStepCode: order.currentStepCode
        });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| STEP TRANSITIONS (admin)
|--------------------------------------------------------------------------
| Admin can jump to any step in the vendor's assigned workflow (branching
| allowed, not strictly sequential - confirmed design), except once an
| order's current step is COMPLETED or DELIVERED, which are absolute
| terminal states with no further transitions at all.
*/
const advanceOrderStep = async (vendorId, adminUserId, orderId, targetStepCode, remarks, companyMasterData, websiteMasterData) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (TERMINAL_STEP_CODES.includes(order.currentStepCode)) {
            return common.returnResult(false, 400, 'This order has already been finalized and cannot be updated further.');
        }

        const stepMaster = await OrderStepMaster.findById(order.orderStepMasterId);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const targetStep = stepMaster.steps.find((step) => step.code === targetStepCode);
        if (!targetStep) {
            return common.returnResult(false, 400, "That step is not part of this order's workflow.");
        }

        closeCurrentHistoryEntryAndPushNext(order, targetStep, adminUserId, true);

        if (targetStep.code === RESERVED_STEP_CODES.DISPATCHED) {
            order.shippedAt = new Date();
        }
        if (targetStep.code === RESERVED_STEP_CODES.DELIVERED) {
            order.deliveredAt = new Date();
        }
        if (targetStep.code === RESERVED_STEP_CODES.REJECTED) {
            order.cancelledAt = new Date();
            order.cancelledBy = adminUserId;
            order.cancellationReason = remarks || 'Rejected by admin.';
        }
        if (remarks) {
            order.remarks = remarks;
        }

        order.updatedBy = adminUserId;
        await order.save();

        await notifyOrderStatusChange(order, companyMasterData, websiteMasterData);

        logger.logInfo(1, 0, 'Order step advanced', { vendorId, orderId, targetStepCode });
        return common.returnResult(true, 200, 'Order status updated successfully', { order });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| DELIVERY AGENT
|--------------------------------------------------------------------------
*/
const assignDeliveryAgent = async (vendorId, adminUserId, orderId, deliveryAgentUserId, companyMasterData) => {
    try {
        if (companyMasterData?.isOrderStatusUpdationAllowedByDeliveryAgents !== true) {
            return common.returnResult(false, 403, 'Delivery agent order updates are not enabled for this store.');
        }

        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        if (TERMINAL_STEP_CODES.includes(order.currentStepCode)) {
            return common.returnResult(false, 400, 'This order has already been finalized and cannot be reassigned.');
        }

        const agent = await User.findOne({ _id: deliveryAgentUserId, vendorId, role: 'deliveryAgent', status: 'A' });
        if (!agent) {
            return common.returnResult(false, 404, 'Delivery agent not found.');
        }

        order.assignedDeliveryAgentId = agent._id;
        order.deliveryAgentAssignedAt = new Date();
        order.updatedBy = adminUserId;
        await order.save();

        logger.logInfo(1, 0, 'Delivery agent assigned to order', { vendorId, orderId, deliveryAgentUserId });
        return common.returnResult(true, 200, 'Delivery agent assigned successfully', { order });
    } catch (err) {
        throw err;
    }
};

// A delivery agent may only move an order from DISPATCHED to DELIVERED,
// and only when it is assigned to them.
const deliveryAgentMarkDelivered = async (vendorId, deliveryAgentUserId, orderId, companyMasterData, websiteMasterData) => {
    try {
        if (companyMasterData?.isOrderStatusUpdationAllowedByDeliveryAgents !== true) {
            return common.returnResult(false, 403, 'Delivery agent order updates are not enabled for this store.');
        }

        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (!order.assignedDeliveryAgentId || order.assignedDeliveryAgentId.toString() !== deliveryAgentUserId.toString()) {
            return common.returnResult(false, 403, 'This order is not assigned to you.');
        }

        if (order.currentStepCode !== DELIVERY_AGENT_FROM_STEP_CODE) {
            return common.returnResult(false, 400, 'This order is not ready to be marked delivered.');
        }

        const stepMaster = await OrderStepMaster.findById(order.orderStepMasterId);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const deliveredStep = stepMaster.steps.find((step) => step.code === DELIVERY_AGENT_TO_STEP_CODE);
        if (!deliveredStep) {
            return common.returnResult(false, 500, "This store's order workflow has no Delivered step configured. Please contact support.");
        }

        closeCurrentHistoryEntryAndPushNext(order, deliveredStep, deliveryAgentUserId, true);
        order.deliveredAt = new Date();
        order.updatedBy = deliveryAgentUserId;
        await order.save();

        await notifyOrderStatusChange(order, companyMasterData, websiteMasterData);

        logger.logInfo(1, 0, 'Order marked delivered by delivery agent', { vendorId, orderId, deliveryAgentUserId });
        return common.returnResult(true, 200, 'Order marked as delivered', { order });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| CANCELLATION (customer-initiated)
|--------------------------------------------------------------------------
| Uses the same REJECTED reserved step as admin-driven rejection - the
| order's own cancelledBy field is what distinguishes "customer cancelled"
| from "admin rejected" after the fact.
*/
const cancelOrder = async (vendorId, userId, orderId, cancellationReason, companySettingsData) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, userId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (companySettingsData?.isOrderCancellationAllowed !== true) {
            return common.returnResult(false, 403, 'Order cancellation is not available for this store.');
        }

        if (TERMINAL_STEP_CODES.includes(order.currentStepCode)) {
            return common.returnResult(false, 400, 'This order can no longer be cancelled.');
        }

        if (order.currentStepCode === RESERVED_STEP_CODES.REJECTED) {
            return common.returnResult(false, 400, 'This order has already been rejected.');
        }

        const stepMaster = await OrderStepMaster.findById(order.orderStepMasterId);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const cutoffCode = companySettingsData?.orderCancellationNotAllowedAfterStep;
        if (cutoffCode) {
            const cutoffStep = stepMaster.steps.find((step) => step.code === cutoffCode);
            if (cutoffStep && order.currentStepSequence >= cutoffStep.sequence) {
                return common.returnResult(false, 400, `This order can no longer be cancelled since it has already reached "${cutoffStep.name}".`);
            }
        }

        const rejectedStep = stepMaster.steps.find((step) => step.code === RESERVED_STEP_CODES.REJECTED);
        if (!rejectedStep) {
            return common.returnResult(false, 500, "This store's order workflow has no Reject step configured. Please contact support.");
        }

        closeCurrentHistoryEntryAndPushNext(order, rejectedStep, userId, true);
        order.cancelledAt = new Date();
        order.cancelledBy = userId;
        order.cancellationReason = cancellationReason;
        order.updatedBy = userId;
        await order.save();

        logger.logInfo(1, 0, 'Order cancelled by customer', { vendorId, orderId, userId });
        return common.returnResult(true, 200, 'Order cancelled successfully', { order });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| LISTING / DETAIL
|--------------------------------------------------------------------------
*/
const fetchMyOrders = async (vendorId, userId) => {
    try {
        const orders = await Order.find({ vendorId, userId, status: { $ne: 'D' } }).sort({ orderPlacedAt: -1 });
        return common.returnResult(true, 200, 'Orders fetched successfully', { orders });
    } catch (err) {
        throw err;
    }
};

const fetchOrderById = async (vendorId, orderId, userId, isAdmin) => {
    try {
        const filter = { _id: orderId, vendorId, status: { $ne: 'D' } };
        if (!isAdmin) {
            filter.userId = userId;
        }
        const order = await Order.findOne(filter);
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        return common.returnResult(true, 200, 'Order fetched successfully', { order });
    } catch (err) {
        throw err;
    }
};

const fetchAllOrdersAdmin = async (vendorId) => {
    try {
        const orders = await Order.find({ vendorId, status: { $ne: 'D' } }).sort({ orderPlacedAt: -1 });
        return common.returnResult(true, 200, 'Orders fetched successfully', { orders });
    } catch (err) {
        throw err;
    }
};

module.exports = {
    createOrderFromCart,
    advanceOrderStep,
    assignDeliveryAgent,
    deliveryAgentMarkDelivered,
    cancelOrder,
    fetchMyOrders,
    fetchOrderById,
    fetchAllOrdersAdmin
};
