const mongoose = require('mongoose');
const Order = require('../models/Order');
const Address = require('../models/Address');
const User = require('../models/User');
const OrderStepMaster = require('../models/OrderStepMaster');
const Product = require('../models/Product');
const Cart = require('../models/Cart');
const OrderReturn = require('../models/OrderReturn');
const OrderExchange = require('../models/OrderExchange');
const cartService = require('./cartService');
const counterService = require('./counterService');
const emailService = require('./emailService');
const emailTemplateMasterService = require('./emailTemplateMasterService');
const commissionService = require('./commissionService');
const invoiceService = require('./invoiceService');
const adminPlaceOrderService = require('./adminPlaceOrderService');
const addressService = require('./addressService');
const currencyService = require('./currencyService');
const orderStepService = require('./orderStepService');
const common = require('../utils/common');
const logger = require('../utils/logger');
const { RESERVED_STEP_CODES, CLOSED_STEP_CODES, SIDE_STEP_NAMES } = require('../constants/orderStepConstants');
const { EMAIL_MODULES } = require('../constants/emailModuleConstants');
const { ORDER_NOTIFICATION_TYPES } = require('../constants/orderRealtimeConstants');
const { notifyOrderChanged } = require('./orderRealtimeService');

/*
|--------------------------------------------------------------------------
| ORDER NUMBER
|--------------------------------------------------------------------------
| Same auto/manual pattern as resolveProductCode/resolveVariantCode/
| resolveSizeCode in productService.js.
*/
const resolveOrderNumber = async ({ vendorId, orderNumber, companySettingsData }) => {
    try {
        if (companySettingsData?.isOrderNumberAutoGenerated !== false) {
            if (orderNumber) {
                return common.returnResult(false, 400, 'Order number is auto-generated for this store and should not be provided.');
            }
            const nextValue = await counterService.getNextSequenceValue(vendorId, 'orderNumber');
            const generatedOrderNumber = `ORD-${String(nextValue).padStart(6, '0')}`;
            return common.returnResult(true, 200, 'All Good', { orderNumber: generatedOrderNumber });
        }

        if (!orderNumber) {
            return common.returnResult(false, 400, 'Order number is required.');
        }

        const normalizedOrderNumber = orderNumber.trim().toUpperCase();
        const existing = await Order.findOne({ vendorId, orderNumber: normalizedOrderNumber });
        if (existing) {
            return common.returnResult(false, 409, 'Order number already exists.');
        }

        return common.returnResult(true, 200, 'All Good', { orderNumber: normalizedOrderNumber });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| ADDRESS SNAPSHOT
|--------------------------------------------------------------------------
*/
const buildAddressSnapshot = async (addressDoc) => {
    try {
        const locationNames = await common.resolveLocationNames({
            countryId: addressDoc.country_id,
            stateId: addressDoc.state_id,
            cityId: addressDoc.city_id
        });

        if (!locationNames.countryName || !locationNames.stateName || !locationNames.cityName) {
            return { error: 'Your address references a country/state/city that no longer exists. Please update your address.' };
        }

        return {
            snapshot: {
                addressName: addressDoc.address_name,
                roomNo: addressDoc.room_no,
                building: addressDoc.building,
                addressInWords: addressDoc.address_in_words,
                floor: addressDoc.floor || null,
                countryName: locationNames.countryName,
                stateName: locationNames.stateName,
                cityName: locationNames.cityName,
                pincode: addressDoc.pincode
            }
        };
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| ORDER CREATION (cart -> order)
|--------------------------------------------------------------------------
*/
const createOrderFromCart = async (vendorId, userId, userCountryId, companyMasterData, websiteMasterData, companySettingsData, shippingPriceSettingsData, payload) => {
    try {
        const { shippingAddressId, billingAddressId, orderNumber } = payload;

        // --- Resolve + validate addresses (cheap, fail fast) ---
        const shippingAddress = await Address.findOne({ _id: shippingAddressId, userId, vendorId, status: 'A' });
        if (!shippingAddress) {
            return common.returnResult(false, 404, 'Shipping address not found.');
        }

        let billingAddress = null;
        if (billingAddressId) {
            billingAddress = await Address.findOne({ _id: billingAddressId, userId, vendorId, status: 'A' });
            if (!billingAddress) {
                return common.returnResult(false, 404, 'Billing address not found.');
            }
        }

        // --- Order caps ---
        const lifetimeLimit = companyMasterData?.numberOfOrdersAllowed;
        if (lifetimeLimit !== null && lifetimeLimit !== undefined) {
            const lifetimeCount = await Order.countDocuments({ vendorId, status: { $ne: 'D' } });
            if (lifetimeCount >= lifetimeLimit) {
                return common.returnResult(false, 403, 'This store has reached the maximum number of orders allowed on its current plan.');
            }
        }

        const monthlyLimit = companyMasterData?.numberOfOrdersAllowedPerMonth;
        if (monthlyLimit !== null && monthlyLimit !== undefined) {
            const startOfMonth = new Date();
            startOfMonth.setDate(1);
            startOfMonth.setHours(0, 0, 0, 0);
            const monthlyCount = await Order.countDocuments({ vendorId, status: { $ne: 'D' }, orderPlacedAt: { $gte: startOfMonth } });
            if (monthlyCount >= monthlyLimit) {
                return common.returnResult(false, 403, 'This store has reached the maximum number of orders allowed this month.');
            }
        }

        // --- Order step workflow (admin-assigned per vendor, not built by vendor) ---
        const orderStepMasterId = companyMasterData?.orderSteps;
        if (!orderStepMasterId) {
            return common.returnResult(false, 500, 'Order workflow is not configured for this store yet. Please contact support.');
        }

        const stepMaster = await orderStepService.loadActiveStepMaster(orderStepMasterId);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is not configured correctly for this store. Please contact support.');
        }

        const firstStep = orderStepService.getFirstStep(stepMaster);
        if (!firstStep) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this store (no starting step). Please contact support.');
        }

        // --- Currency: the customer's own country's, converted from the store
        // currency at the current rate (else the store currency) - the same one
        // the storefront showed them (currencyService.resolveCustomerCurrency).
        const currencyResult = await currencyService.resolveCustomerCurrency({ countryId: userCountryId, companyMasterData, companySettingsData });
        if (!currencyResult.isSuccess) {
            return common.returnResult(false, currencyResult.statusCode, currencyResult.message);
        }
        const currencyMeta = currencyResult.meta;

        // --- Order number (auto or vendor-configured manual) ---
        const orderNumberResult = await resolveOrderNumber({ vendorId, orderNumber, companySettingsData });
        if (!orderNumberResult.isSuccess) {
            return common.returnResult(false, orderNumberResult.statusCode, orderNumberResult.message);
        }

        // --- Address snapshots ---
        const shippingSnapshotResult = await buildAddressSnapshot(shippingAddress);
        if (shippingSnapshotResult.error) {
            return common.returnResult(false, 400, shippingSnapshotResult.error);
        }

        let billingSnapshot = null;
        if (billingAddress) {
            const billingSnapshotResult = await buildAddressSnapshot(billingAddress);
            if (billingSnapshotResult.error) {
                return common.returnResult(false, 400, billingSnapshotResult.error);
            }
            billingSnapshot = billingSnapshotResult.snapshot;
        }

        // --- Re-validate + price the cart one final time at the moment of commit ---
        // Priced against the ACTUAL chosen shipping address (not the user's
        // profile/cookie location) so both tax and shipping are exact at the
        // moment the order is placed - the cart/checkout-summary views only
        // ever show an estimate off the browsing location.
        const orderLocationContext = {
            countryId: shippingAddress.country_id,
            stateId: shippingAddress.state_id,
            cityId: shippingAddress.city_id,
            zipCode: shippingAddress.pincode
        };

        const checkoutResult = await cartService.checkoutCart(
            vendorId,
            { type: 'user', id: userId },
            userId,
            orderLocationContext,
            companyMasterData,
            websiteMasterData,
            companySettingsData,
            shippingPriceSettingsData
        );
        if (!checkoutResult.isSuccess) {
            return common.returnResult(false, checkoutResult.statusCode, checkoutResult.message);
        }

        const { cart, eligibleLineItems, shippingBreakdown, ineligibleItems } = checkoutResult.meta;

        // Manual (CUSTOM) shipping: the admin enters the price after the order
        // is placed, so shipping stays null and the total excludes it (including
        // any per-product custom charge checkout added) until then.
        const isShippingPending = shippingBreakdown?.isShippingPending === true;

        // Checkout priced everything in the store currency; the order is saved
        // (and charged) in the customer's currency - every amount converted once,
        // here, at the rate saved on the order.
        const currencyFields = currencyService.buildOrderCurrencyFields(currencyMeta);
        const { exchangeRate, currencyDecimalPlaces } = currencyFields;
        const toOrderCurrency = (amount) => currencyService.convertAmount(amount, exchangeRate, currencyDecimalPlaces);
        const roundOrder = (amount) => Math.round(amount * 10 ** currencyDecimalPlaces) / 10 ** currencyDecimalPlaces;

        currencyService.convertLines(eligibleLineItems, exchangeRate, currencyDecimalPlaces);
        const orderSubtotal = roundOrder(eligibleLineItems.reduce((sum, item) => sum + item.amount, 0));
        const orderTaxAmount = roundOrder(eligibleLineItems.reduce((sum, item) => sum + item.taxBreakdown.reduce((s, t) => s + t.taxAmount, 0), 0));
        const orderDiscountAmount = toOrderCurrency(cart.totalDiscountAmount);
        const orderFreeCashAmount = toOrderCurrency(cart.totalFreeCashAmount);
        const shippingAmount = isShippingPending ? null : toOrderCurrency(checkoutResult.meta.shippingAmount);
        // Same formula as checkoutCart: deductions can never take the items below zero.
        const orderDeductions = Math.min(orderDiscountAmount + orderFreeCashAmount, orderSubtotal);
        const grandTotal = roundOrder(orderSubtotal - orderDeductions + orderTaxAmount + (shippingAmount || 0));

        const orderItems = eligibleLineItems.map((item) => ({
            productId: item.productId,
            variantId: item.variantId,
            sizeId: item.sizeId,
            productName: item.productName,
            variantName: item.variantName,
            sizeName: item.sizeName,
            sku: item.sku,
            unitPrice: item.unitPrice,
            quantity: item.quantity,
            lineAmount: item.amount,
            taxBreakdown: item.taxBreakdown,
            lineTaxAmount: Math.round(item.taxBreakdown.reduce((sum, t) => sum + t.taxAmount, 0) * 100) / 100
        }));

        // Narrows (but per the double-submit race, cannot fully close - the
        // unique {vendorId, cartId} index on Order is the hard backstop)
        // the window where the same cart could produce two orders.
        const existingOrderForCart = await Order.findOne({ vendorId, cartId: cart._id });
        if (existingOrderForCart) {
            return common.returnResult(false, 409, 'An order has already been placed for this cart.');
        }

        // Reserves stock for every checked-out line item before the Order
        // document (or the cart's deactivation) is ever written, so a lost
        // stock race fails the order cleanly instead of overselling.
        const stockResult = await cartService.decrementStockForOrder(cart);
        if (!stockResult.isSuccess) {
            return common.returnResult(false, stockResult.statusCode, stockResult.message);
        }

        const order = new Order({
            orderNumber: orderNumberResult.meta.orderNumber,
            cartId: cart._id,
            vendorId,
            userId,
            orderStepMasterId: stepMaster._id,
            currentStepId: firstStep._id,
            currentStepCode: firstStep.code,
            currentStepName: firstStep.name,
            currentStepSequence: firstStep.sequence,
            statusHistory: [{
                stepId: firstStep._id,
                stepCode: firstStep.code,
                stepName: firstStep.name,
                sequence: firstStep.sequence,
                startedAt: new Date(),
                isManualUpdate: false
            }],
            items: orderItems,
            subtotal: orderSubtotal,
            totalDiscountAmount: orderDiscountAmount,
            totalTaxAmount: orderTaxAmount,
            totalFreeCashAmount: orderFreeCashAmount,
            shippingAmount,
            shippingPriceBreakdown: shippingBreakdown ? {
                method: shippingBreakdown.method,
                customAmount: toOrderCurrency(shippingBreakdown.customAmount),
                companyAmount: toOrderCurrency(shippingBreakdown.companyAmount),
                isShippingPending,
                isFreeAboveApplied: shippingBreakdown.isFreeAboveApplied === true
            } : null,
            additionalCharges: 0,
            grandTotal,
            ...currencyFields,
            shippingAddressId: shippingAddress._id,
            shippingAddressSnapshot: shippingSnapshotResult.snapshot,
            billingAddressId: billingAddress ? billingAddress._id : null,
            billingAddressSnapshot: billingSnapshot,
            orderPlacedAt: new Date(),
            createdBy: userId
        });
        // The first step may itself be the payment step (paid on placement) or the only step (final at once).
        orderStepService.applyFlowStepEffects(order, firstStep, stepMaster, companySettingsData);

        try {
            await order.save();

            await cartService.consumeFreeCashForOrder(vendorId, cart.freeCash, order._id, userId, companySettingsData);

            await commissionService.recordCommissionForOrder(order, companyMasterData);

            // Locks the cart out of every existing cart route (all of which
            // filter on status:'A') so it can never be mutated or re-checked-out
            // again, and the user's next add-to-cart starts a fresh active cart.
            cart.status = 'D';
            cart.updatedBy = userId;
            await cart.save();
        } catch (err) {
            // Stock was already reserved above - give it back since no order
            // actually made it through.
            await cartService.restoreStockForOrder(cart._id);
            throw err;
        }

        notifyOrderChanged(order, ORDER_NOTIFICATION_TYPES.NEW);

        // Never fails the order: if this can't issue the invoice now, it is issued on first download.
        await invoiceService.tryIssueInvoiceForOrder(order, { companySettingsData, companyMasterData, websiteMasterData });

        logger.logInfo(1, 0, 'Order created successfully', { vendorId, userId, orderId: order._id });

        return common.returnResult(true, 201, 'Order placed successfully', { order, ineligibleItems });
    } catch (err) {
        throw err;
    }
};

// Normal orders give stock back from their linked Cart. Admin-placed orders
// have no Cart - they restore exactly what was deducted, per item.
const restoreStockForCancelledOrder = async (order) => {
    try {
        if (order.isPlacedByAdmin) {
            await adminPlaceOrderService.restoreStockForAdminOrder(order);
            return;
        }
        await cartService.restoreStockForOrder(order.cartId);
        // Products added by an admin after placement (Edit Order) aren't on the
        // cart; they carry their own stockDeductedQuantity. Cart-based items
        // have none (null), so this only gives back the added ones.
        await adminPlaceOrderService.restoreStockForAdminOrder(order);
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| STOCK ON RESTART
|--------------------------------------------------------------------------
| Rejecting/cancelling an order gave its stock back (restoreStockForCancelledOrder),
| so restarting it takes the stock again - exactly the lines that restore gives
| back: the cart's checked-out lines for a normal order, plus every line that
| carries its own stockDeductedQuantity (admin-placed orders, and products an
| admin added later). Checked up front so the admin is told every product that
| is short, then taken line by line; a line lost to a race undoes the rest.
*/
const buildRestartStockLines = async (order, allowOutOfStock) => {
    try {
        const lines = [];
        if (!order.isPlacedByAdmin && order.cartId) {
            const cart = await Cart.findById(order.cartId);
            if (cart) {
                for (const productEntry of cart.products) {
                    for (const variantEntry of productEntry.variants) {
                        for (const sizeEntry of variantEntry.sizes) {
                            if (!sizeEntry.isCheckedOut) continue;
                            lines.push({
                                productId: productEntry.productId,
                                variantId: variantEntry.variantId,
                                sizeId: sizeEntry.sizeId,
                                quantity: sizeEntry.quantity,
                                label: `"${productEntry.productName}" - ${variantEntry.variantName} - ${sizeEntry.sizeName}`,
                                itemIndex: null,
                                allowPartial: false
                            });
                        }
                    }
                }
            }
        }

        (order.items || []).forEach((item, index) => {
            if (item.stockDeductedQuantity === null || item.stockDeductedQuantity === undefined) return;
            lines.push({
                productId: item.productId,
                variantId: item.variantId,
                sizeId: item.sizeId,
                quantity: item.quantity,
                label: `"${item.productName}" - ${item.variantName} - ${item.sizeName}`,
                itemIndex: index,
                // Same rule as when it was first added: the vendor may allow taking what's left.
                allowPartial: allowOutOfStock
            });
        });
        return lines;
    } catch (err) {
        throw err;
    }
};

// Labels of the lines that can't be fully taken right now (the size is gone,
// or has too little stock). Quantities of the same size across lines add up.
const findRestartStockShortages = async (lines) => {
    try {
        const productIds = [...new Set(lines.map((line) => line.productId.toString()))];
        const products = await Product.find({ _id: { $in: productIds } }).select('variants').lean();
        const productMap = new Map(products.map((product) => [product._id.toString(), product]));

        const neededBySize = new Map();
        const shortLabels = [];
        for (const line of lines) {
            const variant = productMap.get(line.productId.toString())?.variants?.find((v) => v._id.toString() === line.variantId.toString());
            const size = variant?.sizes?.find((sz) => sz._id.toString() === line.sizeId.toString());
            if (!size) {
                shortLabels.push(`${line.label} (no longer available)`);
                continue;
            }
            if (line.allowPartial) continue;

            const sizeKey = line.sizeId.toString();
            const needed = (neededBySize.get(sizeKey) || 0) + line.quantity;
            neededBySize.set(sizeKey, needed);
            if (size.stock < needed) {
                shortLabels.push(`${line.label} (needs ${line.quantity}, ${Math.max(0, size.stock)} in stock)`);
            }
        }
        return shortLabels;
    } catch (err) {
        throw err;
    }
};

const reserveStockForRestart = async (order, companySettingsData) => {
    try {
        const allowOutOfStock = companySettingsData?.allowOutOfStockProductsAdding === true;
        const lines = await buildRestartStockLines(order, allowOutOfStock);

        const shortLabels = await findRestartStockShortages(lines);
        if (shortLabels.length > 0) {
            return common.returnResult(false, 409, `This order can't be restarted because these products don't have enough stock: ${shortLabels.join('; ')}. Restock them and try again.`);
        }

        const deductions = [];
        let unexpectedError = null;
        for (const line of lines) {
            const deducted = await adminPlaceOrderService.deductStockForLine(line, line.allowPartial).catch((err) => {
                unexpectedError = err;
                return null;
            });
            if (deducted === null) {
                await adminPlaceOrderService.restoreDeductedStock(deductions);
                if (unexpectedError) throw unexpectedError;
                return common.returnResult(false, 409, `This order can't be restarted because ${line.label} just went out of stock. Please try again.`);
            }
            deductions.push({ productId: line.productId, variantId: line.variantId, sizeId: line.sizeId, deducted });
            if (line.itemIndex !== null) {
                order.items[line.itemIndex].stockDeductedQuantity = deducted;
            }
        }
        return common.returnResult(true, 200, 'Stock reserved for restarted order', { deductions });
    } catch (err) {
        throw err;
    }
};

// Saves a step change. Resolves false (instead of throwing) when another step
// change on the same order won the race - see Order's optimisticConcurrency.
const saveStepChange = async (order) => {
    try {
        return await order.save().then(() => true, (err) => {
            if (orderStepService.isVersionConflict(err)) return false;
            throw err;
        });
    } catch (err) {
        throw err;
    }
};

const STEP_CONFLICT_MESSAGE = 'This order was just updated by someone else. Please refresh it and try again.';

// Resolves the vendor's tagged 'order' template (or the platform default -
// see resolveTemplateForModule) and sends it to the customer, with
// {{stepName}}/{{orderNumber}}/etc. tokens filled in for the step that was
// just reached. A missing template, missing customer email, or a failed send
// is logged and swallowed rather than thrown - the order status change
// itself already succeeded and was already saved before this is called, so a
// notification hiccup must never fail the whole request back to the caller.
// (The `.catch()` below is a promise-level catch, not a try/catch block, so
// it doesn't run afoul of the house rule that a service catch block may only
// `throw err;` - that rule still holds for this function's own try/catch,
// which only guards genuinely unexpected errors, e.g. a DB query blowing up.)
const notifyOrderStatusChange = async (order, companyMasterData, websiteMasterData, companySettingsData, changedByUserId) => {
    try {
        const featureCheck = await common.checkFeatureOnOrOff(
            order.vendorId, websiteMasterData, companyMasterData,
            'isEmailSendingFeatureOnAfterOrderStatusChanges', 'isEmailSendingFeatureOnAfterOrderStatusChanges'
        );
        if (!featureCheck.isSuccess) {
            return;
        }

        const templateResult = await emailTemplateMasterService.resolveTemplateForModule(order.vendorId, EMAIL_MODULES.ORDER, companyMasterData, companySettingsData);
        if (!templateResult.isSuccess) {
            logger.logInfo(0, 1, 'No email template (vendor or default) available for the order module - skipping notification', {
                orderId: order._id, orderNumber: order.orderNumber, stepCode: order.currentStepCode
            });
            return;
        }
        const template = templateResult.meta.template;
        const isDefaultTemplate = templateResult.meta.isDefault;

        const customer = await User.findById(order.userId);
        if (!customer || !customer.email) {
            logger.logInfo(0, 1, 'Order customer has no email on file - skipping notification', { orderId: order._id });
            return;
        }

        const tokens = {
            customerName: customer.name || '',
            orderNumber: order.orderNumber,
            stepName: order.currentStepName,
            trackingNumber: order.trackingNumber || '',
            courierName: order.courierName || '',
            estimatedDeliveryDate: order.estimatedDeliveryDate ? order.estimatedDeliveryDate.toDateString() : '',
            remarks: order.remarks || ''
        };

        const subject = emailService.renderTemplateString(template.subject, tokens);
        const html = emailService.renderTemplateString(template.htmlBody, tokens);
        const text = template.textBody ? emailService.renderTemplateString(template.textBody, tokens) : undefined;

        const sendResult = await emailService.sendEmail({
            vendorId: order.vendorId,
            module: EMAIL_MODULES.ORDER,
            to: customer.email,
            subject,
            html,
            text,
            userId: changedByUserId,
            companyMasterData,
            websiteMasterData,
            companySettingsData,
            isDefaultTemplate
        }).catch((err) => {
            logger.logWarning('Order status change email threw while sending', { orderId: order._id, stepCode: order.currentStepCode, err });
            return null;
        });

        if (sendResult && !sendResult.isSuccess) {
            logger.logInfo(0, 1, 'Order status change email was not sent', { orderId: order._id, reason: sendResult.message });
        }
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| STEP TRANSITIONS (admin)
|--------------------------------------------------------------------------
| The admin can only do what orderStepService.getAvailableActions offers for
| the order right now (the same list the step dropdown shows):
|   NEXT                - the next step of the workflow (no skipping, no going back)
|   PAYMENT_AT_DELIVERY - instead of the payment step, for agent-collected payments
|   REJECTED            - close the order (stock back, commission + invoice voided)
|   REFUNDED            - a closed order's PAID payment was given back
|   RESTART             - a closed order starts again from the first step
| Nothing at all once the order is on its workflow's last step.
*/

// Side effects shared by admin rejection and customer cancellation, run once
// the closing step is saved.
const releaseClosedOrder = async (order, reason) => {
    try {
        await commissionService.voidCommissionForOrder(order.vendorId, order._id, reason);
        await restoreStockForCancelledOrder(order);
        // Voids the invoice (if one was issued) and raises its credit note; never fails the close.
        await invoiceService.tryVoidInvoiceForOrder(order, reason);
    } catch (err) {
        throw err;
    }
};

const rejectOrderByAdmin = async (order, adminUserId, remarks) => {
    try {
        const rejectedStep = orderStepService.buildSideStep(RESERVED_STEP_CODES.REJECTED, order.currentStepSequence);
        orderStepService.moveOrderToStep(order, rejectedStep, adminUserId, true, remarks);
        order.cancelledAt = new Date();
        order.cancelledBy = adminUserId;
        order.cancellationReason = remarks || 'Rejected by admin.';
        order.updatedBy = adminUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }

        await releaseClosedOrder(order, order.cancellationReason);
        return common.returnResult(true, 200, 'Order rejected successfully', { order });
    } catch (err) {
        throw err;
    }
};

// The payment of a rejected/cancelled order was given back to the customer.
// Nothing else changes - stock, commission and invoice were already settled
// when the order was closed.
const refundOrderByAdmin = async (order, adminUserId, remarks) => {
    try {
        const refundedStep = orderStepService.buildSideStep(RESERVED_STEP_CODES.REFUNDED, order.currentStepSequence);
        orderStepService.moveOrderToStep(order, refundedStep, adminUserId, true, remarks);
        order.payment.status = 'REFUNDED';
        order.payment.refundedAmount = order.payment.amount || order.grandTotal;
        order.payment.refundedAt = new Date();
        order.updatedBy = adminUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }
        return common.returnResult(true, 200, 'Order marked as refunded', { order });
    } catch (err) {
        throw err;
    }
};

// Payment at Delivery stands in for the payment step (it takes that step's
// place in the sequence, so "next" carries on from the step after it). The
// payment is marked PAID later, when the delivery-agent transition happens.
const takePaymentAtDelivery = async (order, paymentStep, adminUserId, remarks) => {
    try {
        const padStep = orderStepService.buildSideStep(RESERVED_STEP_CODES.PAYMENT_AT_DELIVERY, paymentStep.sequence);
        orderStepService.moveOrderToStep(order, padStep, adminUserId, true, remarks);
        order.isPaymentAtDelivery = true;
        order.updatedBy = adminUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }
        return common.returnResult(true, 200, 'Order moved to Payment at Delivery', { order });
    } catch (err) {
        throw err;
    }
};

const moveOrderToNextStep = async (order, nextStep, stepMaster, adminUserId, remarks, companySettingsData) => {
    try {
        orderStepService.enterNextFlowStep(order, nextStep, stepMaster, companySettingsData, adminUserId, remarks);
        order.updatedBy = adminUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }
        return common.returnResult(true, 200, 'Order status updated successfully', { order });
    } catch (err) {
        throw err;
    }
};

// A rejected/cancelled/refunded order starts over from the first step: the
// stock is taken again (refused, naming the short products, if it isn't
// there), the commission is owed again and a new invoice is issued. A payment
// that was refunded is due again; one that was never refunded stays PAID.
const restartOrderByAdmin = async (order, firstStep, stepMaster, adminUserId, remarks, companyMasterData, websiteMasterData, companySettingsData) => {
    try {
        const stockResult = await reserveStockForRestart(order, companySettingsData);
        if (!stockResult.isSuccess) {
            return stockResult;
        }

        const wasRefunded = order.currentStepCode === RESERVED_STEP_CODES.REFUNDED;
        orderStepService.moveOrderToStep(order, firstStep, adminUserId, true, remarks);
        order.cancelledAt = null;
        order.cancelledBy = null;
        order.cancellationReason = null;
        order.cancellationRemarks = null;
        order.isPaymentAtDelivery = false;
        order.isFinalized = false;
        order.shippedAt = null;
        order.deliveredAt = null;
        // The delivery starts over too: the agent is taken off (the admin
        // assigns one again) and their step change is undone. Both stay in the history.
        orderStepService.releaseDeliveryAgent(order, adminUserId);
        order.deliveryAgentTransitionAt = null;
        order.deliveryAgentTransitionBy = null;
        order.deliveryAgentTransitionByRole = null;
        if (wasRefunded) {
            order.payment.status = 'PENDING';
            order.payment.paidAt = null;
            order.payment.refundedAmount = 0;
            order.payment.refundedAt = null;
        }
        orderStepService.applyFlowStepEffects(order, firstStep, stepMaster, companySettingsData);
        order.updatedBy = adminUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            await adminPlaceOrderService.restoreDeductedStock(stockResult.meta.deductions);
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }

        await commissionService.reinstateCommissionForOrder(order, companyMasterData);
        // Never fails the restart: if it can't be issued now, it is issued on first download.
        await invoiceService.tryIssueInvoiceForOrder(order, { companySettingsData, companyMasterData, websiteMasterData });

        return common.returnResult(true, 200, 'Order restarted successfully', { order });
    } catch (err) {
        throw err;
    }
};

const advanceOrderStep = async (vendorId, adminUserId, orderId, targetStepCode, remarks, companyMasterData, websiteMasterData, companySettingsData) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (order.isFinalized) {
            return common.returnResult(false, 400, 'This order has reached the last step of its workflow and can no longer be updated.');
        }

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const actions = orderStepService.getAvailableActions(order, stepMaster, companySettingsData, companyMasterData, websiteMasterData);
        // A restart takes the agent off - they still need to hear about it.
        const agentBefore = order.assignedDeliveryAgentId;
        const action = actions.find((candidate) => candidate.code === targetStepCode);
        if (!action) {
            const allowed = actions.map((candidate) => `"${candidate.name}"`).join(', ');
            return common.returnResult(false, 400, allowed
                ? `This order can't be moved to that step. What it can do now: ${allowed}.`
                : 'This order cannot be updated.');
        }

        const cleanRemarks = remarks || null;
        // Saved together with the step change (each branch saves the order).
        if (cleanRemarks) {
            order.remarks = cleanRemarks;
        }

        let result;
        switch (action.type) {
            case orderStepService.ACTION_TYPES.NEXT:
                result = await moveOrderToNextStep(order, action.step, stepMaster, adminUserId, cleanRemarks, companySettingsData);
                break;
            case orderStepService.ACTION_TYPES.PAYMENT_AT_DELIVERY:
                result = await takePaymentAtDelivery(order, action.step, adminUserId, cleanRemarks);
                break;
            case orderStepService.ACTION_TYPES.REJECT:
                result = await rejectOrderByAdmin(order, adminUserId, cleanRemarks);
                break;
            case orderStepService.ACTION_TYPES.REFUND:
                result = await refundOrderByAdmin(order, adminUserId, cleanRemarks);
                break;
            case orderStepService.ACTION_TYPES.RESTART:
                result = await restartOrderByAdmin(order, action.step, stepMaster, adminUserId, cleanRemarks, companyMasterData, websiteMasterData, companySettingsData);
                break;
            default:
                return common.returnResult(false, 400, 'This order cannot be updated.');
        }
        if (!result.isSuccess) {
            return result;
        }

        notifyOrderChanged(order, ORDER_NOTIFICATION_TYPES.STATUS_CHANGED, { previousAgentId: agentBefore });

        await notifyOrderStatusChange(order, companyMasterData, websiteMasterData, companySettingsData, adminUserId);

        logger.logInfo(1, 0, 'Order step changed by admin', { vendorId, orderId, targetStepCode, actionType: action.type });
        return result;
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| MANUAL SHIPPING PRICE
|--------------------------------------------------------------------------
| For orders placed while the vendor's shipping method is CUSTOM: the admin
| enters the shipping price once, which is added to the grand total. A single
| conditional update (not read-modify-save) so two admins can't both add it.
*/
const setOrderShippingPrice = async (vendorId, adminUserId, orderId, shippingAmount) => {
    try {
        const amount = Math.round(shippingAmount * 100) / 100;

        const updated = await Order.findOneAndUpdate(
            {
                _id: orderId,
                vendorId,
                status: { $ne: 'D' },
                'shippingPriceBreakdown.isShippingPending': true,
                'payment.status': { $in: ['PENDING', 'FAILED'] },
                isFinalized: { $ne: true },
                currentStepCode: { $nin: CLOSED_STEP_CODES },
                cancelledAt: null
            },
            [{
                $set: {
                    shippingAmount: amount,
                    grandTotal: { $round: [{ $add: ['$grandTotal', amount] }, 2] },
                    'shippingPriceBreakdown.companyAmount': amount,
                    'shippingPriceBreakdown.isShippingPending': false,
                    updatedBy: adminUserId,
                    updatedAt: '$$NOW'
                }
            }],
            // Mongoose 9 refuses an aggregation-pipeline update unless told it is one.
            { new: true, updatePipeline: true }
        );

        if (!updated) {
            // Nothing matched - work out why, for a useful message.
            const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
            if (!order) {
                return common.returnResult(false, 404, 'Order not found.');
            }
            if (!order.shippingPriceBreakdown?.isShippingPending) {
                return common.returnResult(false, 400, 'This order does not need a shipping price to be added.');
            }
            if (order.payment?.status && !['PENDING', 'FAILED'].includes(order.payment.status)) {
                return common.returnResult(false, 409, 'Payment has already been made for this order, so its total can no longer change.');
            }
            return common.returnResult(false, 400, 'This order has been finalized, cancelled or rejected and can no longer be updated.');
        }

        notifyOrderChanged(updated, ORDER_NOTIFICATION_TYPES.SHIPPING_UPDATED);
        await invoiceService.tryRefreshInvoiceForOrder(updated);

        logger.logInfo(1, 0, 'Order shipping price added', { vendorId, orderId, shippingAmount: amount });
        return common.returnResult(true, 200, 'Shipping price added successfully', { order: updated });
    } catch (err) {
        throw err;
    }
};

/*
| Edit an order's ALREADY-SET shipping price (feature-gated in the controller
| by isEditingShippingPriceFeatureOn). The new grand total is computed inside
| the update from the order's current values (old shipping is swapped for the
| new one), so it stays correct even if two admins edit at once.
| Not allowed once a payment has been taken (the total would no longer match
| what was paid) or once the order is finalized/cancelled/rejected. Orders
| still waiting for their first price use setOrderShippingPrice instead.
*/
const updateOrderShippingPrice = async (vendorId, adminUserId, orderId, shippingAmount) => {
    try {
        const amount = Math.round(shippingAmount * 100) / 100;

        const updated = await Order.findOneAndUpdate(
            {
                _id: orderId,
                vendorId,
                status: { $ne: 'D' },
                'shippingPriceBreakdown.isShippingPending': { $ne: true },
                'payment.status': { $in: ['PENDING', 'FAILED'] },
                isFinalized: { $ne: true },
                currentStepCode: { $nin: CLOSED_STEP_CODES },
                cancelledAt: null
            },
            [{
                $set: {
                    grandTotal: { $round: [{ $add: [{ $subtract: ['$grandTotal', { $ifNull: ['$shippingAmount', 0] }] }, amount] }, 2] },
                    shippingAmount: amount,
                    shippingPriceBreakdown: {
                        $cond: [
                            { $eq: [{ $type: '$shippingPriceBreakdown' }, 'object'] },
                            { $mergeObjects: ['$shippingPriceBreakdown', { customAmount: 0, companyAmount: amount, isFreeAboveApplied: false }] },
                            '$shippingPriceBreakdown'
                        ]
                    },
                    updatedBy: adminUserId,
                    updatedAt: '$$NOW'
                }
            }],
            { new: true, updatePipeline: true }
        );

        if (!updated) {
            const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
            if (!order) {
                return common.returnResult(false, 404, 'Order not found.');
            }
            if (order.shippingPriceBreakdown?.isShippingPending) {
                return common.returnResult(false, 400, 'This order has no shipping price yet. Use Add Shipping Price instead.');
            }
            if (order.payment?.status && !['PENDING', 'FAILED'].includes(order.payment.status)) {
                return common.returnResult(false, 409, 'Payment has already been made for this order, so its shipping price can no longer be changed.');
            }
            return common.returnResult(false, 400, 'This order has been finalized, cancelled or rejected and can no longer be updated.');
        }

        notifyOrderChanged(updated, ORDER_NOTIFICATION_TYPES.SHIPPING_UPDATED);
        await invoiceService.tryRefreshInvoiceForOrder(updated);

        logger.logInfo(1, 0, 'Order shipping price updated', { vendorId, orderId, shippingAmount: amount });
        return common.returnResult(true, 200, 'Shipping price updated successfully', { order: updated });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| EDIT SHIPPING ADDRESS AFTER PLACEMENT
|--------------------------------------------------------------------------
| Feature-gated in the controller (isEditingShippingAddressAfterOrderIsPlacedFeatureOn).
| The order keeps its own address snapshot, so switching to one of the
| customer's saved addresses re-snapshots it, and a typed address lives only
| on the order (adminEnteredAddress) - neither touches the customer's address
| book. Shipping price and tax are NOT recalculated by an address change.
*/
const fetchUserAddressesForOrder = async (vendorId, orderId) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        if (!order.userId) {
            return common.returnResult(true, 200, 'This order has no customer account, so there are no saved addresses.', { addresses: [] });
        }
        const result = await addressService.listAddresses({ userId: order.userId, vendorId });
        return common.returnResult(true, 200, 'Addresses fetched successfully', { addresses: result.meta.addresses });
    } catch (err) {
        throw err;
    }
};

const updateOrderShippingAddress = async (vendorId, adminUserId, orderId, { addressId, addressText }) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        if (!orderStepService.isOrderActive(order) || order.cancelledAt) {
            return common.returnResult(false, 400, 'This order has been finalized, cancelled or rejected and can no longer be updated.');
        }

        let changes;
        if (addressId) {
            if (!order.userId) {
                return common.returnResult(false, 400, 'This order has no customer account. Enter the address instead.');
            }
            const address = await Address.findOne({ _id: addressId, userId: order.userId, vendorId, status: { $ne: 'D' } });
            if (!address) {
                return common.returnResult(false, 404, 'That address was not found for this customer.');
            }
            const snapshotResult = await buildAddressSnapshot(address);
            if (snapshotResult.error) {
                return common.returnResult(false, 400, snapshotResult.error);
            }
            changes = { shippingAddressId: address._id, shippingAddressSnapshot: snapshotResult.snapshot, adminEnteredAddress: null };
        } else {
            changes = { shippingAddressId: null, shippingAddressSnapshot: null, adminEnteredAddress: addressText };
        }

        const updated = await Order.findOneAndUpdate(
            { _id: orderId, vendorId, status: { $ne: 'D' }, isFinalized: { $ne: true }, currentStepCode: { $nin: CLOSED_STEP_CODES }, cancelledAt: null },
            { $set: { ...changes, updatedBy: adminUserId } },
            { new: true }
        );
        if (!updated) {
            return common.returnResult(false, 400, 'This order has been finalized, cancelled or rejected and can no longer be updated.');
        }

        notifyOrderChanged(updated, ORDER_NOTIFICATION_TYPES.ADDRESS_UPDATED);
        await invoiceService.tryRefreshInvoiceForOrder(updated);

        logger.logInfo(1, 0, 'Order shipping address updated', { vendorId, orderId, usedSavedAddress: !!addressId });
        return common.returnResult(true, 200, 'Shipping address updated successfully', { order: updated });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| DELIVERY AGENT
|--------------------------------------------------------------------------
| Needs the delivery-agent feature on in WebsiteMaster AND the vendor's
| CompanyMaster (isOrderStatusUpdationAllowedByDeliveryAgents), and the
| vendor's one agent step change set in Company Settings
| (deliveryAgentFromStep -> deliveryAgentToStep, the step right after).
| The admin can assign, change or take off the agent until that step change
| has been made; every assignment is kept in Order.deliveryAgentAssignments.
*/
const checkDeliveryAgentFeature = async (vendorId, websiteMasterData, companyMasterData) => {
    try {
        return await common.checkFeatureOnOrOff(
            vendorId, websiteMasterData, companyMasterData,
            orderStepService.DELIVERY_AGENT_FEATURE_FLAG, orderStepService.DELIVERY_AGENT_FEATURE_FLAG
        );
    } catch (err) {
        throw err;
    }
};

// Closes whatever assignment is still open in the history - an aggregation
// expression, so the close and the new entry happen in ONE conditional update.
const closeOpenAssignmentsExpression = (adminUserId) => ({
    $map: {
        input: { $ifNull: ['$deliveryAgentAssignments', []] },
        as: 'entry',
        in: {
            $cond: [
                { $eq: [{ $ifNull: ['$$entry.unassignedAt', null] }, null] },
                { $mergeObjects: ['$$entry', { unassignedAt: '$$NOW', unassignedBy: adminUserId }] },
                '$$entry'
            ]
        }
    }
});

const assignDeliveryAgent = async (vendorId, adminUserId, orderId, deliveryAgentUserId, companyMasterData, companySettingsData, websiteMasterData) => {
    try {
        const featureCheck = await checkDeliveryAgentFeature(vendorId, websiteMasterData, companyMasterData);
        if (!featureCheck.isSuccess) {
            return common.returnResult(false, featureCheck.statusCode, featureCheck.message);
        }

        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        if (!orderStepService.isOrderActive(order)) {
            return common.returnResult(false, 400, 'This order has been finalized, rejected or cancelled and cannot be assigned a delivery agent.');
        }
        if (order.deliveryAgentTransitionAt) {
            return common.returnResult(false, 400, "The delivery agent's step has already been done on this order, so the agent can no longer be changed.");
        }

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }
        if (!orderStepService.resolveAgentTransition(stepMaster, companySettingsData)) {
            return common.returnResult(false, 400, 'Set the delivery agent step change (from step and to step) in Company Settings before assigning delivery agents.');
        }

        const agent = await User.findOne({ _id: deliveryAgentUserId, vendorId, role: 'deliveryAgent', status: 'A' });
        if (!agent) {
            return common.returnResult(false, 404, 'Delivery agent not found, or not active.');
        }
        if (order.assignedDeliveryAgentId && order.assignedDeliveryAgentId.toString() === agent._id.toString()) {
            return common.returnResult(false, 400, `This order is already assigned to ${agent.name}.`);
        }

        // Only goes through if nobody changed the agent (or made the agent step
        // change) since the order was read above - two admins can't both assign.
        const updated = await Order.findOneAndUpdate(
            {
                _id: order._id,
                vendorId,
                assignedDeliveryAgentId: order.assignedDeliveryAgentId || null,
                deliveryAgentTransitionAt: null,
                isFinalized: { $ne: true },
                currentStepCode: { $nin: CLOSED_STEP_CODES }
            },
            [{
                $set: {
                    deliveryAgentAssignments: {
                        $concatArrays: [
                            closeOpenAssignmentsExpression(adminUserId),
                            [{
                                deliveryAgentId: agent._id,
                                deliveryAgentName: { $literal: agent.name },
                                assignedAt: '$$NOW',
                                assignedBy: adminUserId,
                                unassignedAt: null,
                                unassignedBy: null
                            }]
                        ]
                    },
                    assignedDeliveryAgentId: agent._id,
                    deliveryAgentAssignedAt: '$$NOW',
                    updatedBy: adminUserId,
                    updatedAt: '$$NOW'
                }
            }],
            { new: true, updatePipeline: true }
        );
        if (!updated) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }

        notifyOrderChanged(updated, ORDER_NOTIFICATION_TYPES.AGENT_ASSIGNED, { previousAgentId: order.assignedDeliveryAgentId });

        const isChange = !!order.assignedDeliveryAgentId;
        logger.logInfo(1, 0, isChange ? 'Delivery agent changed on order' : 'Delivery agent assigned to order', { vendorId, orderId, deliveryAgentUserId });
        return common.returnResult(true, 200, isChange ? `Delivery agent changed to ${agent.name}` : `Order assigned to ${agent.name}`, { order: updated });
    } catch (err) {
        throw err;
    }
};

// Takes the agent off the order (no agent at all until one is assigned again).
const unassignDeliveryAgent = async (vendorId, adminUserId, orderId, companyMasterData, websiteMasterData) => {
    try {
        const featureCheck = await checkDeliveryAgentFeature(vendorId, websiteMasterData, companyMasterData);
        if (!featureCheck.isSuccess) {
            return common.returnResult(false, featureCheck.statusCode, featureCheck.message);
        }

        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }
        if (!order.assignedDeliveryAgentId) {
            return common.returnResult(false, 400, 'This order has no delivery agent.');
        }
        if (order.deliveryAgentTransitionAt) {
            return common.returnResult(false, 400, "The delivery agent's step has already been done on this order, so the agent can no longer be taken off it.");
        }

        const updated = await Order.findOneAndUpdate(
            { _id: order._id, vendorId, assignedDeliveryAgentId: order.assignedDeliveryAgentId, deliveryAgentTransitionAt: null },
            [{
                $set: {
                    deliveryAgentAssignments: closeOpenAssignmentsExpression(adminUserId),
                    assignedDeliveryAgentId: null,
                    deliveryAgentAssignedAt: null,
                    updatedBy: adminUserId,
                    updatedAt: '$$NOW'
                }
            }],
            { new: true, updatePipeline: true }
        );
        if (!updated) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }

        notifyOrderChanged(updated, ORDER_NOTIFICATION_TYPES.AGENT_ASSIGNED, { previousAgentId: order.assignedDeliveryAgentId });

        logger.logInfo(1, 0, 'Delivery agent taken off order', { vendorId, orderId });
        return common.returnResult(true, 200, 'Delivery agent removed from the order', { order: updated });
    } catch (err) {
        throw err;
    }
};

// A delivery agent may only make the vendor's one configured transition, and
// only on an order assigned to them. A Payment at Delivery order is marked
// PAID by this move (see orderStepService.enterNextFlowStep).
const deliveryAgentAdvanceStep = async (vendorId, deliveryAgentUserId, orderId, companyMasterData, websiteMasterData, companySettingsData) => {
    try {
        const featureCheck = await checkDeliveryAgentFeature(vendorId, websiteMasterData, companyMasterData);
        if (!featureCheck.isSuccess) {
            return common.returnResult(false, featureCheck.statusCode, featureCheck.message);
        }

        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (!order.assignedDeliveryAgentId || order.assignedDeliveryAgentId.toString() !== deliveryAgentUserId.toString()) {
            return common.returnResult(false, 403, 'This order is not assigned to you.');
        }
        if (!orderStepService.isOrderActive(order)) {
            return common.returnResult(false, 400, 'This order has been finalized, rejected or cancelled and can no longer be updated.');
        }
        if (order.deliveryAgentTransitionAt) {
            return common.returnResult(false, 400, 'You have already done your step on this order.');
        }

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const transition = orderStepService.resolveAgentTransition(stepMaster, companySettingsData);
        if (!transition) {
            return common.returnResult(false, 400, 'This store has not set up the delivery agent step change yet.');
        }
        // Compared by position: a Payment at Delivery order sits where the payment step was.
        if (order.currentStepSequence !== transition.fromStep.sequence) {
            return common.returnResult(false, 400, `This order can only be moved to "${transition.toStep.name}" while it is at "${transition.fromStep.name}".`);
        }

        orderStepService.enterNextFlowStep(order, transition.toStep, stepMaster, companySettingsData, deliveryAgentUserId, null, 'deliveryAgent');
        order.updatedBy = deliveryAgentUserId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, STEP_CONFLICT_MESSAGE);
        }

        notifyOrderChanged(order, ORDER_NOTIFICATION_TYPES.STATUS_CHANGED);

        await notifyOrderStatusChange(order, companyMasterData, websiteMasterData, companySettingsData, deliveryAgentUserId);

        logger.logInfo(1, 0, 'Order step changed by delivery agent', { vendorId, orderId, deliveryAgentUserId, toStep: transition.toStep.code });
        return common.returnResult(true, 200, `Order moved to "${transition.toStep.name}"`, { order });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| CANCELLATION (customer-initiated)
|--------------------------------------------------------------------------
| Its own CANCELLED side step (an admin's rejection is REJECTED). Like a
| rejection it gives the stock back and voids the commission and invoice,
| and the admin can later refund (if paid) and/or restart it.
*/
const cancelOrder = async (vendorId, userId, orderId, cancellationReason, companySettingsData, companyMasterData, websiteMasterData) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, userId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        if (companySettingsData?.isOrderCancellationAllowed !== true) {
            return common.returnResult(false, 403, 'Order cancellation is not available for this store.');
        }

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const blockMessage = orderStepService.getCustomerCancellationBlock(order, stepMaster, companySettingsData);
        if (blockMessage) {
            return common.returnResult(false, 400, blockMessage);
        }

        const cancelledStep = orderStepService.buildSideStep(RESERVED_STEP_CODES.CANCELLED, order.currentStepSequence);
        orderStepService.moveOrderToStep(order, cancelledStep, userId, true, cancellationReason);
        order.cancelledAt = new Date();
        order.cancelledBy = userId;
        order.cancellationReason = cancellationReason;
        order.updatedBy = userId;

        const saved = await saveStepChange(order);
        if (!saved) {
            return common.returnResult(false, 409, 'This order was just updated by the store. Please refresh it and try again.');
        }

        await releaseClosedOrder(order, cancellationReason);

        notifyOrderChanged(order, ORDER_NOTIFICATION_TYPES.CANCELLED);

        await notifyOrderStatusChange(order, companyMasterData, websiteMasterData, companySettingsData, userId);

        logger.logInfo(1, 0, 'Order cancelled by customer', { vendorId, orderId, userId });
        return common.returnResult(true, 200, 'Order cancelled successfully', { order });
    } catch (err) {
        throw err;
    }
};

/*
|--------------------------------------------------------------------------
| LISTING / DETAIL
|--------------------------------------------------------------------------
*/
const fetchMyOrders = async (vendorId, userId, companySettingsData) => {
    try {
        // List view stays lightweight - full item breakdown is only built
        // for the single-order detail view below.
        const orderDocs = await Order.find({ vendorId, userId, status: { $ne: 'D' } })
            .select('-items')
            .sort({ orderPlacedAt: -1 });

        // canBeCancelled: the same check cancelOrder makes, so the storefront
        // only offers Cancel when it will work.
        const stepMasterIds = [...new Set(orderDocs.map((order) => order.orderStepMasterId.toString()))];
        const stepMasters = await OrderStepMaster.find({ _id: { $in: stepMasterIds } });
        const stepMasterMap = new Map(stepMasters.map((stepMaster) => [stepMaster._id.toString(), stepMaster]));

        const orders = orderDocs.map((order) => {
            const stepMaster = stepMasterMap.get(order.orderStepMasterId.toString());
            const orderObject = order.toObject();
            orderObject.canBeCancelled = !!stepMaster && !orderStepService.getCustomerCancellationBlock(order, stepMaster, companySettingsData);
            return orderObject;
        });
        return common.returnResult(true, 200, 'Orders fetched successfully', { orders });
    } catch (err) {
        throw err;
    }
};

// Orders placed before Order.items existed have nothing frozen on the order
// itself - best-effort reconstruct the line items from the linked Cart (the
// same source this data always came from pre-migration). No historical tax
// breakdown is possible here since checkoutCart never persisted it, so
// taxBreakdown/lineTaxAmount are left empty for these.
const deriveLegacyOrderItems = async (order) => {
    try {
        const cart = await Cart.findById(order.cartId);
        if (!cart) {
            return [];
        }

        const items = [];
        for (const productEntry of cart.products) {
            for (const variantEntry of productEntry.variants) {
                for (const sizeEntry of variantEntry.sizes) {
                    if (!sizeEntry.isCheckedOut) continue;
                    items.push({
                        productId: productEntry.productId,
                        variantId: variantEntry.variantId,
                        sizeId: sizeEntry.sizeId,
                        productName: productEntry.productName,
                        variantName: variantEntry.variantName,
                        sizeName: sizeEntry.sizeName,
                        sku: sizeEntry.sku,
                        unitPrice: sizeEntry.unitPrice,
                        quantity: sizeEntry.quantity,
                        lineAmount: sizeEntry.unitPrice * sizeEntry.quantity,
                        taxBreakdown: [],
                        lineTaxAmount: 0
                    });
                }
            }
        }
        return items;
    } catch (err) {
        throw err;
    }
};

// Adds the two things intentionally NOT frozen on Order.items: the current
// product/size image (cosmetic - never snapshotted, see Order.js) and each
// item's live return/exchange status (a status, not a historical fact -
// must always reflect the current OrderReturn/OrderExchange record).
const enrichOrderItemsForDetail = async (vendorId, order) => {
    try {
        const baseItems = order.items && order.items.length > 0
            ? order.items.map((item) => item.toObject())
            : await deriveLegacyOrderItems(order);

        if (baseItems.length === 0) {
            return [];
        }

        const productIds = [...new Set(baseItems.map((item) => item.productId.toString()))];
        const [products, returns, exchanges] = await Promise.all([
            Product.find({ _id: { $in: productIds }, vendorId }),
            OrderReturn.find({ vendorId, orderId: order._id, status: { $ne: 'D' } }),
            OrderExchange.find({ vendorId, orderId: order._id, status: { $ne: 'D' } })
        ]);
        const productMap = new Map(products.map((p) => [p._id.toString(), p]));

        const findMatchingRequest = (requests, item) => requests.find((request) =>
            request.items.some((requestItem) =>
                requestItem.productId.toString() === item.productId.toString() &&
                requestItem.variantId.toString() === item.variantId.toString() &&
                requestItem.sizeId.toString() === item.sizeId.toString()
            )
        );

        return baseItems.map((item) => {
            const product = productMap.get(item.productId.toString());
            const variant = product ? product.variants.id(item.variantId) : null;
            const size = variant ? variant.sizes.id(item.sizeId) : null;

            const matchingReturn = findMatchingRequest(returns, item);
            const matchingExchange = findMatchingRequest(exchanges, item);

            return {
                ...item,
                image: size ? size.image : null,
                returnStatus: matchingReturn ? matchingReturn.returnStatus : null,
                returnId: matchingReturn ? matchingReturn._id : null,
                exchangeStatus: matchingExchange ? matchingExchange.exchangeStatus : null,
                exchangeId: matchingExchange ? matchingExchange._id : null
            };
        });
    } catch (err) {
        throw err;
    }
};

const fetchOrderById = async (vendorId, orderId, userId, isAdmin, companySettingsData, companyMasterData, websiteMasterData) => {
    try {
        const filter = { _id: orderId, vendorId, status: { $ne: 'D' } };
        if (!isAdmin) {
            filter.userId = userId;
        }
        const order = await Order.findOne(filter);
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        const items = await enrichOrderItemsForDetail(vendorId, order);
        const orderWithItems = order.toObject();
        // Whether this order can have a PDF invoice: only orders with line items actually stored on
        // them can. Older orders show items rebuilt from their cart (with no tax breakdown), which
        // an invoice cannot be built from - the UI uses this to offer the download only when it works.
        orderWithItems.invoiceAvailable = order.items.length > 0;
        orderWithItems.items = items;

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (isAdmin) {
            // Agents can only be assigned once the vendor's agent step change is set up.
            // Also not once the agent step change has been made (the agent's part is done).
            orderWithItems.canAssignDeliveryAgent = orderStepService.isDeliveryAgentFeatureOn(websiteMasterData, companyMasterData) &&
                orderStepService.isOrderActive(order) &&
                !order.deliveryAgentTransitionAt &&
                !!stepMaster && !!orderStepService.resolveAgentTransition(stepMaster, companySettingsData);
        } else {
            orderWithItems.canBeCancelled = !!stepMaster && !orderStepService.getCustomerCancellationBlock(order, stepMaster, companySettingsData);
        }

        return common.returnResult(true, 200, 'Order fetched successfully', { order: orderWithItems });
    } catch (err) {
        throw err;
    }
};

const fetchAllOrdersAdmin = async (vendorId) => {
    try {
        const orders = await Order.find({ vendorId, status: { $ne: 'D' } })
            .select('-items')
            .sort({ orderPlacedAt: -1 });
        return common.returnResult(true, 200, 'Orders fetched successfully', { orders });
    } catch (err) {
        throw err;
    }
};

// Every status an order of this vendor can be in - the Orders page's status
// filter: the steps of the vendor's assigned workflow in order, then the
// built-in ones (Payment at Delivery only while delivery agents are on).
const fetchOrderStatusOptions = async (companyMasterData, websiteMasterData) => {
    try {
        const stepMaster = await orderStepService.loadActiveStepMaster(companyMasterData?.orderSteps);
        const flowStatuses = orderStepService.getSortedSteps(stepMaster).map((step) => ({ code: step.code, name: step.name }));

        const sideCodes = [
            ...(orderStepService.isDeliveryAgentFeatureOn(websiteMasterData, companyMasterData) ? [RESERVED_STEP_CODES.PAYMENT_AT_DELIVERY] : []),
            RESERVED_STEP_CODES.REJECTED,
            RESERVED_STEP_CODES.CANCELLED,
            RESERVED_STEP_CODES.REFUNDED
        ];
        const sideStatuses = sideCodes.map((code) => ({ code, name: SIDE_STEP_NAMES[code] }));

        return common.returnResult(true, 200, 'Order statuses fetched successfully', { statuses: [...flowStatuses, ...sideStatuses] });
    } catch (err) {
        throw err;
    }
};

// Only what the admin can do with the order right now (advanceOrderStep
// accepts exactly these codes): empty once it is on its last step.
const fetchOrderStepOptions = async (vendorId, orderId, companySettingsData, companyMasterData, websiteMasterData) => {
    try {
        const order = await Order.findOne({ _id: orderId, vendorId, status: { $ne: 'D' } });
        if (!order) {
            return common.returnResult(false, 404, 'Order not found.');
        }

        const stepMaster = await orderStepService.loadOrderStepMaster(order);
        if (!stepMaster) {
            return common.returnResult(false, 500, 'Order workflow is misconfigured for this order. Please contact support.');
        }

        const steps = orderStepService.getAvailableActions(order, stepMaster, companySettingsData, companyMasterData, websiteMasterData)
            .map((action) => ({ code: action.code, name: action.name, type: action.type }));

        return common.returnResult(true, 200, 'Order steps fetched successfully', { steps });
    } catch (err) {
        throw err;
    }
};

module.exports = {
    resolveOrderNumber,
    buildAddressSnapshot,
    createOrderFromCart,
    advanceOrderStep,
    setOrderShippingPrice,
    updateOrderShippingPrice,
    fetchUserAddressesForOrder,
    updateOrderShippingAddress,
    assignDeliveryAgent,
    unassignDeliveryAgent,
    deliveryAgentAdvanceStep,
    cancelOrder,
    fetchMyOrders,
    fetchOrderById,
    deriveLegacyOrderItems,
    fetchAllOrdersAdmin,
    fetchOrderStatusOptions,
    fetchOrderStepOptions
};
