import InputField from '../../../../components/common/InputField';
import TextArea from '../../../../components/common/TextArea';
import Dropdown from '../../../../components/common/DropDown';
import DescriptionListEditor from './DescriptionListEditor';
import BulkPricingListEditor from './BulkPricingListEditor';
import TagInput from './TagInput';
import CategoryPathPicker from './CategoryPathPicker';
import SectionCard from './SectionCard';
import { TagIcon, FolderIcon, DocumentIcon, SearchIcon, CoinsIcon } from './icons';

/**
 * Step 1: product-level fields (everything outside variants/sizes), grouped
 * into named SectionCards so the field list reads as scannable sections
 * instead of one long stack.
 */
const ProductBasicsStep = ({
  draft,
  onChange,
  categories,
  taxOptions,
  recommendedProductOptions,
  isCategoryFeatureOn,
  isCategoryNestingAllowed,
  isBulkPricingFeatureOn,
  isProductCodeAutoGenerated,
}) => {
  const patch = (fields) => onChange({ ...draft, ...fields });
  const isExisting = !!draft._id;

  return (
    <div className="space-y-4">
      <SectionCard icon={<TagIcon />} title="Product Details" description="The name and identity customers will see.">
        <InputField label="Product Name" value={draft.name} onChange={(e) => patch({ name: e.target.value })} required maxLength={200} />
        {!isProductCodeAutoGenerated && !isExisting && (
          <InputField label="Product Code" value={draft.productCode} onChange={(e) => patch({ productCode: e.target.value })} required />
        )}
        <TagInput
          label="Colors"
          placeholder="Type a color and press Enter"
          value={draft.colors}
          onChange={(v) => patch({ colors: v })}
          helperText="Every variant's color must be picked from this list."
          badgeVariant="purple"
        />
      </SectionCard>

      {isCategoryFeatureOn && (
        <SectionCard icon={<FolderIcon />} title="Category" description="Drill down as deep as your category tree goes.">
          <CategoryPathPicker
            categories={categories}
            mainCategoryId={draft.mainCategory}
            subCategoryId={draft.subCategory}
            nestingAllowed={isCategoryNestingAllowed}
            onChange={(mainCategory, subCategory) => patch({ mainCategory, subCategory })}
          />
        </SectionCard>
      )}

      <SectionCard icon={<DocumentIcon />} title="Content">
        <TextArea label="Disclaimer" value={draft.disclaimer} onChange={(e) => patch({ disclaimer: e.target.value })} rows={2} />
        <DescriptionListEditor label="Description" value={draft.description} onChange={(v) => patch({ description: v })} />
      </SectionCard>

      <SectionCard icon={<SearchIcon />} title="Discovery" description="Search, taxes, and cross-sell.">
        <TagInput label="Search Keywords" placeholder="Type a keyword and press Enter" value={draft.searchKeywords} onChange={(v) => patch({ searchKeywords: v })} />
        <Dropdown
          label="Taxes"
          placeholder="Select applicable taxes"
          options={taxOptions}
          value={draft.taxIds}
          onChange={(v) => patch({ taxIds: v })}
          multiple
          searchable
          clearable
        />
        <Dropdown
          label="Recommended Products"
          placeholder="Optional"
          options={recommendedProductOptions}
          value={draft.recommendedProducts}
          onChange={(v) => patch({ recommendedProducts: v })}
          multiple
          searchable
          clearable
        />
        <InputField type="number" label="Precedence" placeholder="Optional display order" value={draft.precedence ?? ''} onChange={(e) => patch({ precedence: e.target.value })} />
      </SectionCard>

      <SectionCard icon={<CoinsIcon />} title="Bulk Pricing" description="Optional quantity-based discount tiers for the whole product.">
        <BulkPricingListEditor value={draft.bulkPricing} onChange={(v) => patch({ bulkPricing: v })} disabled={!isBulkPricingFeatureOn} />
      </SectionCard>
    </div>
  );
};

export default ProductBasicsStep;
