import InputField from '../../../../components/common/InputField';
import Dropdown from '../../../../components/common/DropDown';
import Switch from '../../../../components/common/Switch';
import Checkbox from '../../../../components/common/Checkbox';
import FileUpload from '../../../../components/common/FileUpload';
import Button from '../../../../components/common/Buttons';
import Accordion from '../../../../components/common/Accordion';
import DescriptionListEditor from './DescriptionListEditor';
import BulkPricingListEditor from './BulkPricingListEditor';
import PolicyFields from './PolicyFields';
import ShippingFields from './ShippingFields';
import TagInput from './TagInput';
import SectionCard from './SectionCard';
import { TagIcon, RulerIcon, CoinsIcon, ImageIcon, ShieldIcon, LayersIcon, MapPinIcon } from './icons';
import theme from '../theme/theme';

const TrashIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
  </svg>
);

const AccordionTitle = ({ icon: Icon, children }) => (
  <span className="flex items-center gap-2">
    <Icon />
    {children}
  </span>
);

/**
 * Full editor for one size within a variant - the leaf of the
 * product/variant/size tree. `size` is one entry from productDraft's
 * variant.sizes array (see productDraft.js for the shape). Grouped into
 * named SectionCards so the dense field list reads as sections to scan
 * rather than one long form; the rarely-touched overrides/exclusions live
 * behind a closed-by-default Accordion at the bottom.
 */
const SizeEditor = ({
  size,
  onChange,
  onRemove,
  sizeOptions,
  getSizeMasterById,
  unitOptions,
  countryOptions,
  stateOptions,
  cityOptions,
  isBulkPricingFeatureOn,
  isSizeCodeAutoGenerated,
}) => {
  const patch = (fields) => onChange({ ...size, ...fields });

  const sizeMaster = getSizeMasterById(size.sizeId);
  const isExisting = !!size._id;

  const handleSizeMasterChange = (sizeId) => {
    const master = getSizeMasterById(sizeId);
    patch({
      sizeId,
      sizeType: master?.type || 'LABEL',
      sizeName: size.sizeName || master?.name || '',
      values: [],
      labelValue: '',
    });
  };

  const updateMeasurementValue = (measurementId, field, val) => {
    const existingIndex = size.values.findIndex((v) => v.measurementId === measurementId);
    if (existingIndex === -1) {
      if (val === '' || val == null) return;
      patch({ values: [...size.values, { measurementId, unit: field === 'unit' ? val : '', value: field === 'value' ? val : '' }] });
      return;
    }
    const nextValues = size.values.map((v, i) => (i === existingIndex ? { ...v, [field]: val } : v));
    patch({ values: nextValues });
  };

  const removeMeasurementValue = (measurementId) => patch({ values: size.values.filter((v) => v.measurementId !== measurementId) });

  return (
    <div className="space-y-4">
      <SectionCard
        icon={<TagIcon />}
        title="Size Details"
        description="Which Size Master entry this is, and how it's shown to customers."
        actions={
          <Button type="button" isIconOnly size="sm" variant={theme.button.ghost} ariaLabel="Remove size" onClick={onRemove}>
            <TrashIcon />
          </Button>
        }
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Dropdown
            label="Size (from Size Master)"
            options={sizeOptions}
            value={size.sizeId}
            onChange={handleSizeMasterChange}
            searchable
            required
            disabled={isExisting}
            helperText={isExisting ? 'Size master reference cannot be changed once created.' : undefined}
          />
          <InputField
            label="Size Display Name"
            placeholder="Shown to customers, e.g. 'Medium'"
            value={size.sizeName}
            onChange={(e) => patch({ sizeName: e.target.value })}
            required
          />
        </div>
        <Switch label="Default size for this variant" checked={size.isDefaultSize} onChange={(e) => patch({ isDefaultSize: e.target.checked })} color={theme.switch.color} />
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <InputField label="Brand" placeholder="Optional, free text" value={size.brand} onChange={(e) => patch({ brand: e.target.value })} />
          <InputField label="Precedence" type="number" placeholder="Optional display order" value={size.precedence ?? ''} onChange={(e) => patch({ precedence: e.target.value })} />
        </div>
      </SectionCard>

      {sizeMaster?.type === 'MEASURABLE' && (
        <SectionCard icon={<RulerIcon />} title="Fit &amp; Measurements">
          <div className="space-y-2">
            {(sizeMaster.measurements || []).map((m) => {
              const row = size.values.find((v) => v.measurementId === m.measurementId || v.measurementId === m._id) || {};
              const measurementId = m.measurementId || m._id || m.label;
              return (
                <div key={measurementId} className="rounded-lg border border-gray-100 bg-gray-50/60 p-2.5 sm:bg-transparent sm:border-0 sm:p-0 sm:flex sm:items-center sm:gap-2">
                  <span className="block text-sm font-medium text-gray-700 mb-1.5 sm:mb-0 sm:font-normal sm:text-gray-600 sm:w-32 sm:flex-shrink-0">{m.label}</span>
                  <div className="flex items-center gap-2">
                    <div className="grid grid-cols-2 gap-2 flex-1">
                      <InputField
                        type="number"
                        placeholder="Value"
                        value={row.value ?? ''}
                        onChange={(e) => updateMeasurementValue(measurementId, 'value', e.target.value)}
                      />
                      <Dropdown
                        placeholder="Unit"
                        options={(m.allowedUnits || []).map((u) => ({ value: String(u._id), label: u.name }))}
                        value={row.unit || ''}
                        onChange={(val) => updateMeasurementValue(measurementId, 'unit', val)}
                      />
                    </div>
                    {row.value !== undefined && (
                      <Button type="button" isIconOnly size="sm" variant={theme.button.ghost} ariaLabel="Clear" onClick={() => removeMeasurementValue(measurementId)} className="flex-shrink-0">
                        <TrashIcon />
                      </Button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </SectionCard>
      )}

      {sizeMaster?.type === 'LABEL' && (
        <SectionCard icon={<RulerIcon />} title="Fit &amp; Measurements">
          <Dropdown
            label="Label Value"
            options={(sizeMaster.values || []).map((v) => ({ value: v, label: v }))}
            value={size.labelValue}
            onChange={(val) => patch({ labelValue: val })}
            required
          />
        </SectionCard>
      )}

      <SectionCard icon={<CoinsIcon />} title="Pricing &amp; Stock">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <InputField type="number" label="Price" value={size.price} onChange={(e) => patch({ price: e.target.value })} required />
          <InputField type="number" label="Cancelled Price" placeholder="Optional, must be > price" value={size.cancelledPrice} onChange={(e) => patch({ cancelledPrice: e.target.value })} />
          <InputField type="number" label="Stock" value={size.stock} onChange={(e) => patch({ stock: e.target.value })} />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <InputField label="SKU" value={size.sku} onChange={(e) => patch({ sku: e.target.value })} required />
          <InputField label="Barcode" placeholder="Optional, globally unique" value={size.barcode} onChange={(e) => patch({ barcode: e.target.value })} />
          {!isSizeCodeAutoGenerated && !isExisting && (
            <InputField label="Size Code" value={size.sizeCode} onChange={(e) => patch({ sizeCode: e.target.value })} required />
          )}
        </div>
        <div>
          <span className="block text-sm font-medium text-gray-700 mb-2">Weight (optional)</span>
          <div className="grid grid-cols-2 gap-4">
            <InputField
              type="number"
              placeholder="Value"
              value={size.weight?.value ?? ''}
              onChange={(e) => patch({ weight: { value: e.target.value, unit: size.weight?.unit || '' } })}
            />
            <Dropdown
              placeholder="Unit"
              options={unitOptions}
              value={size.weight?.unit || ''}
              onChange={(val) => patch({ weight: { value: size.weight?.value ?? '', unit: val } })}
            />
          </div>
        </div>
      </SectionCard>

      <SectionCard icon={<ImageIcon />} title="Images">
        <div>
          <span className="block text-sm font-medium text-gray-700 mb-2">Main Image</span>
          {size.existingImage?.url && !size.imageFile && (
            <div className="flex items-center gap-3 mb-2">
              <img src={size.existingImage.url} alt={size.sizeName} className="w-16 h-16 object-cover rounded-lg border border-gray-200" />
              <p className={`text-sm ${theme.text.muted}`}>Current image - upload a new one to replace it.</p>
            </div>
          )}
          <FileUpload accept="image/*" maxSize={5 * 1024 * 1024} onFilesSelected={(files) => patch({ imageFile: files[0] || null })} helperText="JPG, PNG, up to 5MB." />
        </div>
        <div>
          <span className="block text-sm font-medium text-gray-700 mb-2">Additional Images</span>
          {size.existingAdditionalImages?.length > 0 && !size.additionalImageFile && (
            <div className="flex flex-wrap gap-2 mb-2">
              {size.existingAdditionalImages.map((img, i) => (
                <img key={img.imageAssetId || i} src={img.url} alt="" className="w-12 h-12 object-cover rounded border border-gray-200" />
              ))}
            </div>
          )}
          <FileUpload
            accept="image/*,.zip"
            maxSize={20 * 1024 * 1024}
            onFilesSelected={(files) => patch({ additionalImageFile: files[0] || null })}
            helperText="One image, or a single .zip containing multiple images."
          />
        </div>
      </SectionCard>

      <SectionCard icon={<ShieldIcon />} title="Policies &amp; Shipping">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <PolicyFields label="Warranty" value={size.warranty} onChange={(v) => patch({ warranty: v })} />
          <PolicyFields label="Return" value={size.return} onChange={(v) => patch({ return: v })} />
          <PolicyFields label="Exchange" value={size.exchange} onChange={(v) => patch({ exchange: v })} />
        </div>
        <ShippingFields value={size.shipping} onChange={(v) => patch({ shipping: v })} />
      </SectionCard>

      <Accordion
        allowMultiple
        variant="separated"
        items={[
          {
            key: 'overrides',
            title: <AccordionTitle icon={LayersIcon}>Overrides (description, disclaimer, bulk pricing)</AccordionTitle>,
            content: (
              <div className="space-y-3">
                <Checkbox label="Same description as variant" checked={size.isDescriptionSameFromVariantsDetails} onChange={(e) => patch({ isDescriptionSameFromVariantsDetails: e.target.checked })} />
                <DescriptionListEditor label="Additional Description" value={size.sizeAdditionalDescription} onChange={(v) => patch({ sizeAdditionalDescription: v })} />

                <Checkbox label="Same disclaimer as variant" checked={size.isDisclaimerSameFromVariantsDetails} onChange={(e) => patch({ isDisclaimerSameFromVariantsDetails: e.target.checked })} />
                <InputField label="Additional Disclaimer" value={size.sizeAdditionalDisclaimer} onChange={(e) => patch({ sizeAdditionalDisclaimer: e.target.value })} />

                <Checkbox label="Same bulk pricing as variant" checked={size.isBulkPricingSameFromVariantsDetails} onChange={(e) => patch({ isBulkPricingSameFromVariantsDetails: e.target.checked })} />
                <BulkPricingListEditor
                  label="Additional Bulk Pricing"
                  value={size.sizeAdditionalBulkPricing}
                  onChange={(v) => patch({ sizeAdditionalBulkPricing: v })}
                  disabled={!isBulkPricingFeatureOn}
                />
              </div>
            ),
          },
          {
            key: 'exclusions',
            title: <AccordionTitle icon={MapPinIcon}>Exclusions (optional)</AccordionTitle>,
            content: (
              <div className="space-y-3">
                <p className={`text-xs ${theme.text.muted}`}>Hide this size from customers in the selected countries/states/cities/zip codes.</p>
                <Dropdown label="Exclude Countries" options={countryOptions} value={size.excludeCountries} onChange={(v) => patch({ excludeCountries: v })} multiple searchable clearable />
                <Dropdown label="Exclude States" options={stateOptions} value={size.excludeStates} onChange={(v) => patch({ excludeStates: v })} multiple searchable clearable />
                <Dropdown label="Exclude Cities" options={cityOptions} value={size.excludeCities} onChange={(v) => patch({ excludeCities: v })} multiple searchable clearable />
                <TagInput label="Exclude Zip Codes" placeholder="Type a zip code and press Enter" value={size.excludeZipCodes} onChange={(v) => patch({ excludeZipCodes: v })} badgeVariant="red" />
              </div>
            ),
          },
        ]}
      />
    </div>
  );
};

export default SizeEditor;
