import { useState } from 'react';
import Button from '../../../../components/common/Buttons';
import Badge from '../../../../components/common/Badge';
import Accordion from '../../../../components/common/Accordion';
import EmptyState from '../../../../components/common/EmptyState';
import VariantEditor from './VariantEditor';
import { emptyVariant } from '../utils/productDraft';
import theme from '../theme/theme';

const PlusIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
  </svg>
);

const ColorDot = ({ color }) => (
  <span
    className="w-3 h-3 rounded-full border border-black/10 flex-shrink-0"
    style={{ backgroundColor: color || '#d1d5db' }}
    aria-hidden="true"
  />
);

/**
 * Step 2: the variants tree. Requires at least one color to be set on the
 * product (step 1) before variants can be added, matching the server-side
 * rule that every variant.color must match one of product.colors.
 */
const VariantsStep = ({
  draft,
  onChange,
  colorOptions,
  sizeOptions,
  getSizeMasterById,
  unitOptions,
  countryOptions,
  stateOptions,
  cityOptions,
  isBulkPricingFeatureOn,
  isSizeCodeAutoGenerated,
  isVariantCodeAutoGenerated,
  maxVariants,
}) => {
  const [openKeys, setOpenKeys] = useState(draft.variants.length > 0 ? [draft.variants[0].clientId] : []);

  const addVariant = () => {
    const variant = emptyVariant();
    onChange({ ...draft, variants: [...draft.variants, variant] });
    setOpenKeys((prev) => [...prev, variant.clientId]);
  };
  const updateVariant = (index, next) => onChange({ ...draft, variants: draft.variants.map((v, i) => (i === index ? next : v)) });
  const removeVariant = (index) => onChange({ ...draft, variants: draft.variants.filter((_, i) => i !== index) });

  const atLimit = typeof maxVariants === 'number' && draft.variants.length >= maxVariants;

  if (draft.colors.length === 0) {
    return (
      <EmptyState
        title="Add colors first"
        description="Go back to Basic Details and add at least one color before creating variants."
        size="sm"
      />
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <p className={`text-sm font-semibold ${theme.text.heading}`}>Variants</p>
          <Badge variant="gray" size="sm">{draft.variants.length}</Badge>
        </div>
        <Button type="button" size="sm" variant={theme.button.primary} leftIcon={<PlusIcon />} onClick={addVariant} disabled={atLimit}>
          Add Variant
        </Button>
      </div>
      {atLimit && <p className={`text-xs ${theme.text.muted}`}>Maximum of {maxVariants} variants reached for your plan.</p>}

      {draft.variants.length === 0 ? (
        <EmptyState title="No variants yet" description="Add a variant to start adding sizes and pricing." size="sm" />
      ) : (
        <Accordion
          allowMultiple
          openKeys={openKeys}
          onChange={setOpenKeys}
          variant="separated"
          items={draft.variants.map((variant, index) => ({
            key: variant.clientId,
            title: (
              <span className="flex flex-wrap items-center gap-2">
                <ColorDot color={variant.color} />
                <span className="font-medium">{variant.color || variant.displayName || 'Variant'}</span>
                {variant.isDefaultVariant && <Badge variant="blue" size="sm">Default</Badge>}
                <span className="text-gray-400 font-normal">
                  {variant.sizes.length} size{variant.sizes.length === 1 ? '' : 's'}
                </span>
              </span>
            ),
            content: (
              <VariantEditor
                variant={variant}
                onChange={(next) => updateVariant(index, next)}
                onRemove={() => removeVariant(index)}
                colorOptions={colorOptions}
                sizeOptions={sizeOptions}
                getSizeMasterById={getSizeMasterById}
                unitOptions={unitOptions}
                countryOptions={countryOptions}
                stateOptions={stateOptions}
                cityOptions={cityOptions}
                isBulkPricingFeatureOn={isBulkPricingFeatureOn}
                isSizeCodeAutoGenerated={isSizeCodeAutoGenerated}
                isVariantCodeAutoGenerated={isVariantCodeAutoGenerated}
              />
            ),
          }))}
        />
      )}
    </div>
  );
};

export default VariantsStep;
