import { useState } from 'react';
import InputField from '../../../../components/common/InputField';
import Dropdown from '../../../../components/common/DropDown';
import Switch from '../../../../components/common/Switch';
import Checkbox from '../../../../components/common/Checkbox';
import Button from '../../../../components/common/Buttons';
import Badge from '../../../../components/common/Badge';
import Accordion from '../../../../components/common/Accordion';
import DescriptionListEditor from './DescriptionListEditor';
import BulkPricingListEditor from './BulkPricingListEditor';
import SizeEditor from './SizeEditor';
import SectionCard from './SectionCard';
import { SwatchIcon, LayersIcon } from './icons';
import { emptySize } from '../utils/productDraft';
import theme from '../theme/theme';

const TrashIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
  </svg>
);
const PlusIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
  </svg>
);

/**
 * Editor for one product variant: its own fields, plus an accordion of
 * SizeEditor instances for variant.sizes.
 */
const VariantEditor = ({
  variant,
  onChange,
  onRemove,
  colorOptions,
  sizeOptions,
  getSizeMasterById,
  unitOptions,
  countryOptions,
  stateOptions,
  cityOptions,
  isBulkPricingFeatureOn,
  isSizeCodeAutoGenerated,
  isVariantCodeAutoGenerated,
}) => {
  const [openSizeKeys, setOpenSizeKeys] = useState([]);
  const patch = (fields) => onChange({ ...variant, ...fields });
  const isExisting = !!variant._id;

  const addSize = () => {
    const size = emptySize();
    patch({ sizes: [...variant.sizes, size] });
    setOpenSizeKeys((prev) => [...prev, size.clientId]);
  };
  const updateSize = (index, nextSize) => patch({ sizes: variant.sizes.map((s, i) => (i === index ? nextSize : s)) });
  const removeSize = (index) => patch({ sizes: variant.sizes.filter((_, i) => i !== index) });

  return (
    <div className="space-y-4">
      <SectionCard
        icon={<SwatchIcon />}
        title="Variant Details"
        actions={
          <Button type="button" isIconOnly size="sm" variant={theme.button.ghost} ariaLabel="Remove variant" onClick={onRemove}>
            <TrashIcon />
          </Button>
        }
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Dropdown
            label="Color"
            placeholder="Optional"
            options={colorOptions}
            value={variant.color || ''}
            onChange={(val) => patch({ color: val || null })}
            clearable
          />
          <InputField label="Display Name" placeholder="Optional" value={variant.displayName} onChange={(e) => patch({ displayName: e.target.value })} />
        </div>
        <Switch label="Default variant for this product" checked={variant.isDefaultVariant} onChange={(e) => patch({ isDefaultVariant: e.target.checked })} color={theme.switch.color} />
        {!isVariantCodeAutoGenerated && !isExisting && (
          <InputField label="Variant Code" value={variant.variantCode} onChange={(e) => patch({ variantCode: e.target.value })} required />
        )}
      </SectionCard>

      <Accordion
        allowMultiple
        variant="separated"
        items={[
          {
            key: 'overrides',
            title: (
              <span className="flex items-center gap-2">
                <LayersIcon />
                Overrides (description, disclaimer, bulk pricing)
              </span>
            ),
            content: (
              <div className="space-y-3">
                <Checkbox label="Same description as product" checked={variant.isDescriptionSameFromProductBasicDetails} onChange={(e) => patch({ isDescriptionSameFromProductBasicDetails: e.target.checked })} />
                <DescriptionListEditor label="Additional Description" value={variant.variantAdditionalDescription} onChange={(v) => patch({ variantAdditionalDescription: v })} />

                <Checkbox label="Same disclaimer as product" checked={variant.isDisclaimerSameFromProductBasicDetails} onChange={(e) => patch({ isDisclaimerSameFromProductBasicDetails: e.target.checked })} />
                <InputField label="Additional Disclaimer" value={variant.variantAdditionalDisclaimer} onChange={(e) => patch({ variantAdditionalDisclaimer: e.target.value })} />

                <Checkbox label="Same bulk pricing as product" checked={variant.isBulkPricingSameFromProductBasicDetails} onChange={(e) => patch({ isBulkPricingSameFromProductBasicDetails: e.target.checked })} />
                <BulkPricingListEditor
                  label="Additional Bulk Pricing"
                  value={variant.variantAdditionalBulkPricing}
                  onChange={(v) => patch({ variantAdditionalBulkPricing: v })}
                  disabled={!isBulkPricingFeatureOn}
                />
              </div>
            ),
          },
        ]}
      />

      <div>
        <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
          <div className="flex items-center gap-2">
            <p className={`text-sm font-semibold ${theme.text.heading}`}>Sizes</p>
            <Badge variant="gray" size="sm">{variant.sizes.length}</Badge>
          </div>
          <Button type="button" size="xs" variant={theme.button.secondary} leftIcon={<PlusIcon />} onClick={addSize}>
            Add Size
          </Button>
        </div>
        {variant.sizes.length === 0 && (
          <p className={`text-sm ${theme.text.muted} rounded-xl border border-dashed border-gray-200 px-4 py-6 text-center`}>
            Add at least one size for this variant.
          </p>
        )}
        <Accordion
          allowMultiple
          openKeys={openSizeKeys}
          onChange={setOpenSizeKeys}
          variant="separated"
          items={variant.sizes.map((size, index) => ({
            key: size.clientId,
            title: (
              <span className="flex flex-wrap items-center gap-2">
                <span className="font-medium">{size.sizeName || 'New size'}</span>
                {size.sku && <span className="text-gray-400 font-normal">SKU {size.sku}</span>}
                {size.isDefaultSize && <Badge variant="blue" size="sm">Default</Badge>}
              </span>
            ),
            content: (
              <SizeEditor
                size={size}
                onChange={(next) => updateSize(index, next)}
                onRemove={() => removeSize(index)}
                sizeOptions={sizeOptions}
                getSizeMasterById={getSizeMasterById}
                unitOptions={unitOptions}
                countryOptions={countryOptions}
                stateOptions={stateOptions}
                cityOptions={cityOptions}
                isBulkPricingFeatureOn={isBulkPricingFeatureOn}
                isSizeCodeAutoGenerated={isSizeCodeAutoGenerated}
              />
            ),
          }))}
        />
      </div>
    </div>
  );
};

export default VariantEditor;
