/**
 * Every field on the CompanySettings form, keyed to its draft shape - mirrors
 * SIMPLE_FIELDS in backend/services/companySettingsService.js (currencyId is
 * intentionally omitted: there's no CurrencyMaster admin/list endpoint yet
 * for a dropdown to read from).
 */
export const emptyDraft = () => ({
  adminName: '',
  adminEmail: '',
  adminWhatsappNumber: '',
  adminPhoneNumber: '',
  adminAddress: '',
  adminCity: '',
  adminState: '',
  adminPincode: '',
  companyName: '',
  instagramId: '',
  facebookId: '',

  privacyPolicy: '',
  cancelPolicy: '',
  termsAndConditions: '',
  aboutUs: '',

  showAnnouncements: true,
  isAnnouncementRotationOn: false,
  showBanners: false,
  isBannerRotationOn: false,
  isTaxRegistrationOnSignupEnabled: false,
  showReviewsToCustomers: true,

  isProductCodeAutoGenerated: true,
  isVariantCodeAutoGenerated: true,
  isSizeCodeAutoGenerated: true,
  shouldProductsBeHiddenWhenLocationsAreExcluded: true,
  useShortNameForBrand: false,

  allowOutOfStockProductsAdding: false,

  fewItemsReturnOnly: false,
  fewItemsExchangeOnly: false,
  isOrderCancellationAllowed: false,
  orderCancellationNotAllowedAfterStep: '',
  isOrderNumberAutoGenerated: true,

  senderEmail: '',
  ccList: [],
  bccList: [],

  isPaymentGatewayFeatureOn: true,
  bankAccountHolderName: '',
  bankName: '',
  bankAccountNumber: '',
  ifscCode: '',
  branchName: '',
  swiftCode: '',
  bankAccountType: '',

  isFreeCashFeatureOn: false,
  isFreeCashStackingAllowed: false,
  isMultipleFreeCashUsageAllowed: false,
  isStoringRemainingFreeCashAmountAllowed: false,
  returnFreeCashOnOrderReturn: false,
  refundWholeFreeCashAmount: false,
  amountToRefund: '',

  timeForAbondonedCartReflection: 30,
  abondonedCartOnlyForLoggedInUsers: true,

  companyLogo: null,
  paymentScanner: null,
  partnerCertificate: null,
});

/**
 * Converts a CompanySettings doc from GET /get-company-settings into draft
 * shape for the form. companyLogo/paymentScanner/partnerCertificate stay as
 * their existing { url, imageAssetId } (or null) - the form only replaces
 * them with a new File on submit if the admin picks one.
 */
export const mapApiSettingsToDraft = (doc) => ({
  adminName: doc.adminName || '',
  adminEmail: doc.adminEmail || '',
  adminWhatsappNumber: doc.adminWhatsappNumber || '',
  adminPhoneNumber: doc.adminPhoneNumber || '',
  adminAddress: doc.adminAddress || '',
  adminCity: doc.adminCity || '',
  adminState: doc.adminState || '',
  adminPincode: doc.adminPincode || '',
  companyName: doc.companyName || '',
  instagramId: doc.instagramId || '',
  facebookId: doc.facebookId || '',

  privacyPolicy: doc.privacyPolicy || '',
  cancelPolicy: doc.cancelPolicy || '',
  termsAndConditions: doc.termsAndConditions || '',
  aboutUs: doc.aboutUs || '',

  showAnnouncements: !!doc.showAnnouncements,
  isAnnouncementRotationOn: !!doc.isAnnouncementRotationOn,
  showBanners: !!doc.showBanners,
  isBannerRotationOn: !!doc.isBannerRotationOn,
  isTaxRegistrationOnSignupEnabled: !!doc.isTaxRegistrationOnSignupEnabled,
  showReviewsToCustomers: !!doc.showReviewsToCustomers,

  isProductCodeAutoGenerated: !!doc.isProductCodeAutoGenerated,
  isVariantCodeAutoGenerated: !!doc.isVariantCodeAutoGenerated,
  isSizeCodeAutoGenerated: !!doc.isSizeCodeAutoGenerated,
  shouldProductsBeHiddenWhenLocationsAreExcluded: !!doc.shouldProductsBeHiddenWhenLocationsAreExcluded,
  useShortNameForBrand: !!doc.useShortNameForBrand,

  allowOutOfStockProductsAdding: !!doc.allowOutOfStockProductsAdding,

  fewItemsReturnOnly: !!doc.fewItemsReturnOnly,
  fewItemsExchangeOnly: !!doc.fewItemsExchangeOnly,
  isOrderCancellationAllowed: !!doc.isOrderCancellationAllowed,
  orderCancellationNotAllowedAfterStep: doc.orderCancellationNotAllowedAfterStep || '',
  isOrderNumberAutoGenerated: !!doc.isOrderNumberAutoGenerated,

  senderEmail: doc.senderEmail || '',
  ccList: Array.isArray(doc.ccList) ? doc.ccList : [],
  bccList: Array.isArray(doc.bccList) ? doc.bccList : [],

  isPaymentGatewayFeatureOn: !!doc.isPaymentGatewayFeatureOn,
  bankAccountHolderName: doc.bankAccountHolderName || '',
  bankName: doc.bankName || '',
  bankAccountNumber: doc.bankAccountNumber || '',
  ifscCode: doc.ifscCode || '',
  branchName: doc.branchName || '',
  swiftCode: doc.swiftCode || '',
  bankAccountType: doc.bankAccountType || '',

  isFreeCashFeatureOn: !!doc.isFreeCashFeatureOn,
  isFreeCashStackingAllowed: !!doc.isFreeCashStackingAllowed,
  isMultipleFreeCashUsageAllowed: !!doc.isMultipleFreeCashUsageAllowed,
  isStoringRemainingFreeCashAmountAllowed: !!doc.isStoringRemainingFreeCashAmountAllowed,
  returnFreeCashOnOrderReturn: !!doc.returnFreeCashOnOrderReturn,
  refundWholeFreeCashAmount: !!doc.refundWholeFreeCashAmount,
  amountToRefund: doc.amountToRefund ?? '',

  timeForAbondonedCartReflection: doc.timeForAbondonedCartReflection ?? 30,
  abondonedCartOnlyForLoggedInUsers: !!doc.abondonedCartOnlyForLoggedInUsers,

  companyLogo: doc.companyLogo || null,
  paymentScanner: doc.paymentScanner || null,
  partnerCertificate: doc.partnerCertificate || null,
});

// Mirrors BANK_TRANSFER_FIELDS in backend/services/companySettingsService.js.
// companySettingsService.checkPaymentDetailsEntitlements treats ANY of these
// being present in the request body (even as an empty string - it only
// checks `!== undefined`) as "the admin is touching the Bank Transfer
// group", and 403s the ENTIRE save if the vendor isn't entitled to it. Since
// the draft always carries these keys (even '' when the section is hidden),
// they must be left out of the payload entirely for a vendor who isn't
// entitled - otherwise every save fails, not just ones that actually touch
// bank details. Confirmed live: an unrelated "Show Announcements" toggle
// 403'd with "This feature is temporarily unavailable" until this was fixed.
const BANK_TRANSFER_FIELDS = [
  'bankAccountHolderName', 'bankName', 'bankAccountNumber', 'ifscCode',
  'branchName', 'swiftCode', 'bankAccountType',
];

/**
 * Builds the { fields, files } payload the API layer expects from a draft.
 * companyLogo/paymentScanner/partnerCertificate are only ever included in
 * `files` when the admin picked a brand new File - the pre-existing
 * { url, imageAssetId } objects are display-only and never sent back.
 *
 * @param {Object} draft
 * @param {Object} [options]
 * @param {boolean} [options.bankTransferEnabled] - CompanyMaster.showPaymentQRCodeAndBankDetails
 */
export const buildSavePayload = (draft, { bankTransferEnabled = false } = {}) => {
  const {
    companyLogo, paymentScanner, partnerCertificate,
    ccList, bccList,
    orderCancellationNotAllowedAfterStep,
    amountToRefund,
    // Destructured out (not spread into `rest`/`fields` below) regardless of
    // bankTransferEnabled - see BANK_TRANSFER_FIELDS comment above.
    // eslint-disable-next-line no-unused-vars
    bankAccountHolderName, bankName, bankAccountNumber, ifscCode,
    // eslint-disable-next-line no-unused-vars
    branchName, swiftCode, bankAccountType,
    ...rest
  } = draft;

  const fields = {
    ...rest,
    // '' -> null is fine for these two: their Joi schemas explicitly treat
    // an empty string as "clear it". amountToRefund's schema has no such
    // allowance (plain Joi.number().allow(null), no '' handling) and an
    // empty string would fail validation outright - so when it's blank the
    // key is left out entirely below instead, and the backend's own
    // normalizeFreeCashReturnFields resets it to null there whenever
    // returnFreeCashOnOrderReturn/refundWholeFreeCashAmount call for it.
    orderCancellationNotAllowedAfterStep: orderCancellationNotAllowedAfterStep || null,
    ccList: (ccList || []).filter(Boolean),
    bccList: (bccList || []).filter(Boolean),
  };

  if (bankTransferEnabled) {
    BANK_TRANSFER_FIELDS.forEach((field) => {
      fields[field] = field === 'bankAccountType' ? (draft[field] || null) : draft[field];
    });
  }

  if (amountToRefund !== '') {
    fields.amountToRefund = Number(amountToRefund);
  }

  const files = {};
  if (companyLogo instanceof File) files.companyLogo = companyLogo;
  if (paymentScanner instanceof File) files.paymentScanner = paymentScanner;
  if (partnerCertificate instanceof File) files.partnerCertificate = partnerCertificate;

  return { fields, files };
};
