const mongoose = require('mongoose');

const companySettingsSchema = new mongoose.Schema({
    vendorId: {
        type: mongoose.Types.ObjectId,
        required: true,
        unique: true,
        index: true
    },
  // The vendor's own base/fallback currency - shown to guests and to any
  // logged-in user whose own country has no CurrencyMaster configured.
  // A logged-in user's own country's currency takes precedence over this
  // when resolving what to charge/display (see resolveOrderCurrency in
  // orderService.js).
  currencyId: {
    type: mongoose.Types.ObjectId,
    ref: 'CurrencyMaster',
    default: null
  },
  // Personal Information
  adminName: {
    type: String,
    required: [true, 'Admin name is required'],
    trim: true
  },
  adminWhatsappNumber: {
    type: String,
    trim: true
  },
  adminPhoneNumber: {
    type: String,
    trim: true
  },
  adminAddress: {
    type: String,
    trim: true
  },
  adminCity: {
    type: String,
    trim: true
  },
  adminState: {
    type: String,
    trim: true
  },
  adminPincode: {
    type: String,
    trim: true
  },
  adminEmail: {
    type: String,
    required: [true, 'Admin email is required'],
    trim: true,
    lowercase: true
  },
  companyName: {
    type: String,
    trim: true,
    default: ''
  },
  companyLogo: {
  type: String,
  default: ''
  },
  instagramId: {
    type: String,
    trim: true
  },
  facebookId: {
    type: String,
    trim: true
  },
  paymentScanner: {
    type: String,
  },
  
  // Policies (stored as HTML from React Quill)
  privacyPolicy: {
    type: String,
    default: ''
  },
  cancelPolicy: {
    type: String,
    default: ''
  },
  termsAndConditions: {
    type: String,
    default: ''
  },
  aboutUs: {
    type: String,
    default: ''
  },
  createdBy: {
    userID: mongoose.Types.ObjectId,
    vendorID: mongoose.Types.ObjectId,
  },
  updatedBy: {
    userID: mongoose.Types.ObjectId,
    vendorID: mongoose.Types.ObjectId,
  },
  isAnnouncementFeatureOn: {
    type: Boolean,
  },
  isAnnouncementRotationOn: {
    type: Boolean,
    default: false
  },
  // Start of product
  showReviewsToCustomers: {
      type: Boolean,
      default: true
  },
  isProductCodeAutoGenerated: {
    type: Boolean,
    default: true
  },
  isVariantCodeAutoGenerated: {
    type: Boolean,
    default: true
  },
  isSizeCodeAutoGenerated: {
    type: Boolean,
    default: true
  },
  shouldProductsBeHiddenWhenLocationsAreExcluded: {
    type: Boolean,
    default: true
  },
  // End of product

  // Start of Brand
  // When true, a size's resolved brand display is its brandShortName -
  // falling back to brandName whenever the selected brand has no short
  // name set (never surfaced as null/empty). When false, brandName is
  // always shown. See resolveBrandDisplayName in brandMasterService.js.
  useShortNameForBrand: {
    type: Boolean,
    default: false
  },
  // End of Brand

  // Stat of Cart
  allowOutOfStockProductsAdding: {
    type: Boolean,
    default: false
  },
  // End of Cart

  // Start of Return/Exchange
  // Only meaningful when isReturnFeatureOn/isExchangeFeatureOn (WebsiteMaster
  // + CompanyMaster) are both on for this vendor. When OFF, a customer can
  // only request a return/exchange for the whole order at once (auto-limited
  // to whichever items are still within their own product-level return/
  // exchange window - see orderReturnService/orderExchangeService).
  fewItemsReturnOnly: {
    type: Boolean,
    default: false
  },
  fewItemsExchangeOnly: {
    type: Boolean,
    default: false
  },
  // End of Return/Exchange

  // Start of Announcements
  showAnnouncements: {
    type: Boolean,
    defaullt: true
  },
  // End of Announcements

  // Start of Order
  isOrderCancellationAllowed: {
    type: Boolean,
    default: false
  },
  // Once an order's current step reaches this reserved step code, a
  // customer can no longer cancel it themselves (e.g. "DISPATCHED" means
  // cancellation closes the moment the order ships). null = no cutoff -
  // cancellable at any step up to the COMPLETED/DELIVERED terminal lock
  // (see orderStepConstants.js).
  orderCancellationNotAllowedAfterStep: {
    type: String,
    enum: ['ACCEPTED', 'REJECTED', 'COMPLETED', 'DELIVERED', 'DISPATCHED', 'READY_FOR_DELIVERY'],
    default: null
  },
  isOrderNumberAutoGenerated: {
    type: Boolean,
    default: true
  },
  // End of Order

  // Start of Email
  // "From" address used when sending email through emailService.js. Falls
  // back to adminEmail when unset - see sendEmail in emailService.js.
  senderEmail: {
    type: String,
    trim: true,
    lowercase: true,
    default: null
  },
  // Always cc'd/bcc'd in addition to whatever the calling module passes -
  // see sendEmail in emailService.js.
  ccList: {
    type: [String],
    default: []
  },
  bccList: {
    type: [String],
    default: []
  },
  // End of Email

  // Start of Email Template
  // One EmailTemplateMaster tagged per module - e.g. { module: 'order',
  // templateId: <the vendor's own template> }. At most one entry per module
  // (enforced in companySettingsService.assignEmailTemplate, not at the
  // schema level). See resolveTemplateForModule in
  // emailTemplateMasterService.js for how this is actually consumed - a
  // missing/removed entry, or the referenced template being deleted, falls
  // back to the platform's DefaultEmailTemplateMaster for that module.
  emailTemplateAssignments: {
    type: [{
      module: { type: String, required: true, trim: true },
      templateId: { type: mongoose.Types.ObjectId, ref: 'EmailTemplateMaster', required: true }
    }],
    default: []
  },
  // End of Email Template
}, {
  timestamps: true
});

module.exports = mongoose.model('CompanySettings', companySettingsSchema);